### ISSUE TITLE
 Upvotes cannot be negative

### ISSUE THREAD

**Issue by lokeshsingh3721** [scorelab/Codelabz#1002]
**Describe the bug**

Clicking on the "decrement upvote" button results in the upvote count going below zero, which is not intended behavior.

**To Reproduce**

1. Go to 'Home'
2. Click on 'decrement upvote'
3. See error

This is also happening in the post details component .

1. Go to 'Home'
2. Click on 'Any post'
3. Click on 'Decrement upvote'

**Expected behavior**

The upvote count should decrement by one when the "decrement upvote" button is clicked, but it should not go below zero. The count should stop at zero.

**Screenshots**

https://github.com/scorelab/Codelabz/assets/71646466/f36b91b8-4085-41ad-b77a-302913efb602

**Desktop (please complete the following information):**

- OS: [iOS]
- Browser [ chrome, safari]
- Version [Chrome 118 on macOS (Ventura)]

**Comment by PoulavBhowmick03** [comment]
Hey Lokesh, I have made an issue for this, you can see #995 for more details. I am waiting for the mentor's comment to raise a PR for this

**Comment by Huzaif-Ahmed** [comment]
@PoulavBhowmick03  i am already working on this issue

https://github.com/scorelab/Codelabz/issues/887

i already implemented comment like system and currently working on implmenting tutuorial like system

**Comment by lokeshsingh3721** [comment]
Ok closing this issue
