### ISSUE TITLE
Full Screen Button Functionality

### ISSUE THREAD

**Issue by LakshayDhiman023** [scorelab/Codelabz#1006]
**Describe the bug**
On tutorial Page, full screen button works fine but if esc key is used to exit full screen mode, full screen button does not changes its functionality and still shows exit full screen mode option.

**To Reproduce**

1. Go to 'tutorials on home page'
2. Click on 'any tutorial or create a new tutorial'
3. Click on Full Screen Button and use esc key to exit full screen.
4. Hover over full screen button again.

**Expected behavior**
It should not show exit full screen behavior if esc is used to exit the full screen mode.

**Screenshots**
[Bug Video](https://github.com/scorelab/Codelabz/assets/143027595/13b15790-5fd5-42df-8946-ec051b5eab63)

**Comment by DevanshSK** [comment]
@LakshayDhiman023 Can you assign me this issue?
