### ISSUE TITLE
User can upvote and downvote multiple times

### ISSUE THREAD

**Issue by Aditya-Sakpal** [scorelab/Codelabz#1013]
**Describe the bug**
A user can upvote and downvote multiple times  , which is in appropriate

**To Reproduce**

1.Complete the Login process 
2.Create an org in the dashboard
3.Go to the created org
4.Go to the feed section 
5.Now you can see that you can upvote and downvote multiple times

**Expected behavior**
A user can upvote and downvote only once

**Video Reference**

https://github.com/scorelab/Codelabz/assets/112710558/cc29fbf3-354b-438a-a7ac-68553b189a6f

**Comment by DevanshSK** [comment]
@Aditya-Sakpal Can you assign me this issue?

**Comment by rohitPandey469** [comment]
I think its already issued in #995 , however creating separate issues will be efficient.
