### ISSUE TITLE
Org Comments Details aren't visible

### ISSUE THREAD

**Issue by Aditya-Sakpal** [scorelab/Codelabz#1015]
**Describe the bug**
Details of the comments like title , description ,date , name ,etc  under the organization aren't visible.

**To Reproduce**

1. Complete the login process
2. Create an org in the dashboard
3. Go to the created org
4. Go the feeds section
5. Now you can see that the details aren't visible for the comments

**Expected behavior**
Details like name , date,tags,description ,title ,etc should be visible under the org section

**Video Reference**

https://github.com/scorelab/Codelabz/assets/112710558/6505d699-b7b2-4e52-b131-e7d52edad917

**Comment by rohitPandey469** [comment]
I was just going though issues when I found this one
@Aditya-Sakpal You are using the fixed data already provided to populate the cards and then render it - that's what's this issue about.
But I had done something more efficient in #1144 where I am filtering out all the tutorials with the current user's uid or in general rendering those tutorials which are created by the user. Do check it out too @ABHISHEK-PANDEY2 Sir!!!

**Comment by Aditya-Sakpal** [comment]
Hey bro nice job , but these same cards are used for comments as well .The areas where comments are meant to be ,you have placed tutorials over there bro.

**Comment by rohitPandey469** [comment]
Hey, showing just comments...umm..I am not pretty sure but don't look good to me , I have stated in my PR that later on in development I'll show everything for a user like linkedin if he have post/tutorials then those at the top if no post then his comments on tutorial...it's that I wasn't focusing on thinking it this way that we can use the same cards for showing comments aswell... really appreciated. 
So the needed implementation is, using same Cards and showing posts + comments of specific user. That's great if u wanna work on it go ahead I'll try it aswell...for some reference you can view my changed files however I don't think you may need it... keep grinding brother <3
