### ISSUE TITLE
Improve UI of Navbar [ user logo ]

### ISSUE THREAD

**Issue by DIWAKARKASHYAP** [scorelab/Codelabz#1017]
**Is your feature request related to a problem? Please describe.**
When the display size falls between small and medium, the user's logo in the navbar descends below the search bar, resulting in an undesirable appearance for the navbar and affect UI

**Describe the solution you'd like**
Remove the user's logo when the screen size is below medium on devices.

**Describe alternatives you've considered**
We can relocate the user's logo to a different position, such as near the burger icon, to preserve its functionality 

**Additional context**
https://github.com/scorelab/Codelabz/assets/94478026/8bea1f83-6406-4486-936d-28f8b57a7b4e

**Comment by DevanshSK** [comment]
@DIWAKARKASHYAP Can you assign me this issue, i can work on this issue?

**Comment by DIWAKARKASHYAP** [comment]
Hello @DevanshSK,

I apologize, but unfortunately, I don't have the access to assign issues as I'm just a contributor like yourself and not a maintainer. I've already submitted a pull request. You may consider exploring another issue for your contribution, or if you prefer, you can raise a new issue.

Currently, the product is in its development phase, and numerous issues are being addressed. If you encounter any problems or difficulties, I'd be more than happy to assist you.
