### ISSUE TITLE
Add a confirmation modal window whenever user wants to follow someone and also add an unfollow button

### ISSUE THREAD

**Issue by PoulavBhowmick03** [scorelab/Codelabz#1020]
**Is your feature request related to a problem? Please describe.**
Currently in the home page when user follows someone, they are unable to unfollow them. This does not seem convenient for a regular user

**Describe the solution you'd like**
I would like to add two things
1. An unfollow option which appears when the user follows someone
2. A modal window which asks for confirmation if user wants to unfollow that individual

**Describe alternatives you've considered**
Nothing as such, we can also ask the user for confirmation if they want to follow someone but that would be very hectic for any user.

https://github.com/scorelab/Codelabz/assets/133862694/950d71af-019a-4fe2-ba8b-bf3d18651c4c

**Comment by PoulavBhowmick03** [comment]
I would like to work on this issue I created

**Comment by DevanshSK** [comment]
@PoulavBhowmick03 Can you assign me this issue?

**Comment by KhushPatel2026** [comment]
@PoulavBhowmick03 I would like to work on this issue.

**Comment by PoulavBhowmick03** [comment]
@ABHISHEK-PANDEY2 @Maahi10001 @Sarfraz-droid Can this be assigned? So that I can work on this
