### ISSUE TITLE
Display the user profile avatar in small devices

### ISSUE THREAD

**Issue by PoulavBhowmick03** [scorelab/Codelabz#1041]
**Is your feature request related to a problem? Please describe.**
Currently whenever we view the website in mobile mode or small screens, the profile avatar visible in the large screen is not visible.
**Describe the solution you'd like**
I would like to put the profile avatar in the sliding navbar which comes up on clicking the hamburger icon on the top right

**Describe alternatives you've considered**
An alternative could be displaying the profile avatar outside of the navbar, but that won't look much pleasant in the UI side of things

I have added the relevant screenshots
## In large screen
![image](https://github.com/scorelab/Codelabz/assets/133862694/a2ffef84-d1de-4916-b4b4-91050a3bde69)
## In small screen
![image](https://github.com/scorelab/Codelabz/assets/133862694/7f40d549-eb4b-4046-9edb-8b642163e589)

**Comment by PoulavBhowmick03** [comment]
I would like to work on this issue I created

**Comment by soulmini** [comment]
@charithccmc i wanna work on it can assign me

**Comment by PoulavBhowmick03** [comment]
> @charithccmc i wanna work on it can assign me

Hey! I am sorry but I want to work on this and so I created this issue.. and was waiting to be assigned, you can search for some other issues which aren't being worked on and work on those! Happy contributing <3
