### ISSUE TITLE
[Doc Update] Resolve CORS Issues: Configure Firebase Storage for Tutorial Images in Your Firebase Project

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#1053]
**Describe the bug**
The app currently lacks a configuration for uploading images to Firebase Storage. Users encounter CORS (Cross-Origin Resource Sharing) issues while attempting to upload tutorial images. This issue was identified during the process of uploading images for tutorials, and its functionalities are addressed in PR #1052 with associated issue #1029. To resolve this, an update to the documentation is necessary to guide users through the basic setup required for enabling successful image uploads to Firebase.

**To Reproduce**
Will be easily implmentable when PR #1052 is merged 

1. Upload a tutorial image within the tutorial creation process.
2. Create a tutorial using the uploaded image.
3. Encounter CORS-related errors in console.
4. To avoid it need to do some basic setup to https://console.cloud.google.com

**Expected behavior**
To resolve this issue, a basic Firebase Storage setup needs to be implemented to allow the successful uploading of tutorial images. Users should follow the provided documentation to configure Firebase Storage for their project, ensuring a smooth image upload process without CORS issues.

**Desktop (please complete the following information):**
- OS: Windows
- Browser Chrome Firefox

**Additional context**
This issue is discovered during the image upload process for tutorials, emphasizing the necessity of providing clear guidance to users for setting up Firebase Storage to handle image uploads effectively.

**Comment by Huzaif-Ahmed** [comment]
Heyy! i have been working with siimilar issue  somewhere else and i am done with it . i know its an issue generated by you but i would love to contribute towards it @rohitPandey469 @shivareddy6 @Sarfraz-droid please assign it to me

**Comment by rohitPandey469** [comment]
Hey @Huzaif-Ahmed! 🚀 Thanks for the superhero offer! 🦸‍♂️ I'm in bug-bashing mode, unleashing coding chaos! If you've got wild ideas or ninja hacks, hit me up – let's make this bug scream in madness! 🤘🎩🔥
And tbh It's just an update to doc...

**Comment by Huzaif-Ahmed** [comment]
Sure Rohit would you like to connect on discord ?
