### ISSUE TITLE
Implement Edit description functionality [Tutorial]

### ISSUE THREAD

**Issue by manzil-infinity180** [scorelab/Codelabz#1065]
<img width="966" alt="Screenshot 2024-01-11 at 6 23 15 PM" src="https://github.com/scorelab/Codelabz/assets/119070053/6cb26215-00f2-4b6e-bb22-4d9f3d487eec">

https://github.com/scorelab/Codelabz/assets/119070053/d701e5e6-e4aa-4103-a1bd-9b6597af607c

**Comment by aakash2330** [comment]
please assign this to me .
