### ISSUE TITLE
Home Page Not Responsive

### ISSUE THREAD

**Issue by Keshav-0907** [scorelab/Codelabz#1066]
**Describe the bug**
The Dashboard's Home page is not responsive

**To Reproduce**
Visit `/` in mobile view

1. Go to `/`
2. Switch to Mobile View
3. See error

**Expected behavior**
The Page should be responsive 

**Screenshots**

<img width="228" alt="Screenshot 2024-01-12 at 2 00 11 AM" src="https://github.com/scorelab/Codelabz/assets/91189139/c9bb7733-7603-4eac-a07a-d9f6be8e936f">

**Desktop (please complete the following information):**

- OS: macOS
- Browser : Brave
- Version :  v1.61.109

**Comment by rohit9625** [comment]
Are you working on this issue @Keshav-0907?

**Comment by Keshav-0907** [comment]
> Are you working on this issue @Keshav-0907?

Yes @rohit9625

**Comment by aneekamangal07** [comment]
Hii, can I work on this issue?
