### ISSUE TITLE
[ Fix : SocialIcons Component Not Redirecting to Saved Links ]

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#1069]
**Describe the bug**
On the /profile page, the SocialIcons component is intended to display the social links of the current user. However, it currently does not redirect to the links when clicked; instead, they function as buttons.

**To Reproduce**

1. Go to 'http://localhost:5173/profile'
2. Click on any social link, assuming that the user has saved their social links in 'http://localhost:5173/user-dashboard/profile'.
3. No redirection

**Expected behavior**
Upon saving the link at 'http://localhost:5173/user-dashboard/profile', the application should update the state across the entire app. Subsequently, the SocialIcons component should be populated with the links retrieved from the redux store.

**Screenshots**
![image](https://github.com/scorelab/Codelabz/assets/123815256/f7457550-b10c-4ea8-94aa-28e1c081f603)
_Here in social icons_

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Additional context**
Need to update the SocialIcons component with links, extracted from redux store.

**Comment by nakul30** [comment]
can you assign this issue to me
