### ISSUE TITLE
Make the profile follow, share, report button functional in the Frontend

### ISSUE THREAD

**Issue by PoulavBhowmick03** [scorelab/Codelabz#1072]
**Is your feature request related to a problem? Please describe.**
Currently, if we go to the profile section, the follow, share and report buttons do not function. They are static

![image](https://github.com/scorelab/Codelabz/assets/133862694/1261bbeb-e995-4198-b232-477469014ac7)

**Describe the solution you'd like**
I would like to make the follow button functional, so that on clicking follow, it makes it to following and changes the color
Also, on clicking the report button, a modal pops up to ask for the reason and a description
In the share button, we show a dummy link for now, allowing users to copy the link.

**Describe alternatives you've considered**
A continuation of this would be integrating it to the backend to make it completely functional which I intend to do in the future

**Comment by rohitPandey469** [comment]
Hey @PoulavBhowmick03, I've got a super exciting idea for you! How about creating separate tickets for each task? It's going to be incredibly efficient, and everyone can dive right in and tackle a smaller part. 🚀 Let's make this process a breeze! 😃
