### ISSUE TITLE
User Settings in the sidemenu redirects to a blank page 

### ISSUE THREAD

**Issue by Keshav-0907** [scorelab/Codelabz#1075]
**Describe the bug**

When the `User Settings` option in the side menu is clicked, it currently redirects to a blank page. To enhance user experience, consider redirecting to `/user-dashboard/profile` instead, avoiding the display of a blank page.

https://github.com/scorelab/Codelabz/assets/91189139/fdd2ad20-54c8-4280-8817-9f92ff5aa5b9

**To Reproduce**

1. Go to `/`
2. Click on 'User Settings' in the side menu
3. See error

**Expected behavior**
 The expected behavior is to be redirected to `/user-dashboard/profile` rather than showing a blank page.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser : Brave
- Version : v 1.61.109

**Comment by rohitPandey469** [comment]
@Keshav-0907  Do you not believe that the app is intended to be designed in such a manner? It appears to be in an unfinished state. In that case, why are there two options for the same route? and I think it should redirect to /settings as what User Settings name suggest
