### ISSUE TITLE
Tutorial Search functionality not working 

### ISSUE THREAD

**Issue by Aditya-Sakpal** [scorelab/Codelabz#1086]
**Describe the bug**
Tutorial search is not working . When the user tries to search a tutorial with title or summary it displays the following message :- 'No CodeLabz with the given query' even though the tutorial is present  

**To Reproduce**

1. Complete the login process
2. Go the dashboard and fill the details and create an org
3. Come to /tutorials and create few tutorials .
4. Now in the search bar try to search the tutorials using their title and summary , you can see the following message :- 'No CodeLabz with the given query'

**Expected behavior**
When the user searches for the tutorial the desired tutorial should be displayed below 

**Video Reference**

https://github.com/scorelab/Codelabz/assets/112710558/020b8ca9-c2ab-4af1-89d6-7d6164f259b4

**Comment by soham2312** [comment]
@Aditya-Sakpal This search is for the search of tutorial for each organizations or it for searching the organizations I am confused about it please correct me if I am wrongly understanding something

**Comment by Aditya-Sakpal** [comment]
This search functionality is for searching the desired tutorials using title or summary

**Comment by soham2312** [comment]
ok thanks
