### ISSUE TITLE
[Fix]:  Delete Button Not Functioning on Notification Page

### ISSUE THREAD

**Issue by shikhar-4739** [scorelab/Codelabz#1087]
**Describe the bug**
Experiencing an issue on the notification page where the delete button fails to remove notifications as expected. Upon clicking the delete button, the notification remains visible on the page.

**To Reproduce**

1. Navigate to the notification page.
2. Click on the delete button for a specific notification.
3. Observe that the notification does not get deleted.

**Expected behavior**
Upon clicking the delete button, expecting the notification to be promptly removed from the notification page.

**Screenshots**

https://github.com/scorelab/Codelabz/assets/135845175/53e0a2ad-1f15-47de-b96e-4af7bcd854c6

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Microsoft Edge

**Additional context**
After clicking the delete button, the notification remains visible on the notification page.

**Comment by nayan911** [comment]
@Sarfraz-droid @shikhar-4739 @Maahi10001 can you assign me the issue??
