### ISSUE TITLE
Adding New emails, changing primary email, changing backup email in user-dashboard/email section 

### ISSUE THREAD

**Issue by LakshayDhiman023** [scorelab/Codelabz#1109]
**Is your feature request related to a problem? Please describe.**
On emails section in user-dashboard. We have non working add new email function. Also we can change primary and backup email address but it is not stored in firebase. Primary Email and backup emails are just hardcoded in file emailAddressConfig

https://github.com/scorelab/Codelabz/assets/143027595/92a03cd4-4bf4-4d66-bf0a-5b97b3adfca9

**Describe the solution you'd like**
My solution is to make storage of primary and backup emails on firebase and functioning to change primary and backup email address.

**Describe alternatives you've considered**

**Additional context**

**Comment by Huzaif-Ahmed** [comment]
I would like to work over this issue please assign it to me

**Comment by lavish123409** [comment]
As it is silent here, I would like to work on this issue.

As per my research, I think I need to add a button with required backend call [here](https://github.com/scorelab/Codelabz/blob/3b0952cd27b0d58641b0f318ce77e2341fb8c94d/src/components/Forms/UserEmail/index.jsx#L58). But, I am having doubt that where do we have to save the data in firebase and what do we have to do after saving it?

If these queries can be answered, then I can start working on this issue.

**Comment by lavish123409** [comment]
Is there anyone else working on this issue or any existing PR which closes the issue @LakshayDhiman023 ?
