### ISSUE TITLE
[Bug]: Drag and Drop not functioning in new Tutorial via "Add Images"

### ISSUE THREAD

**Issue by shikhar-4739** [scorelab/Codelabz#1112]
**Describe the bug**
When try to drag and drop an image within the project, the image fails to drop in the intended location and open in a new Tab. This issue is affecting the expected functionality of the drag-and-drop feature, hindering a crucial aspect of the project's usability.

**To Reproduce**

1. Go to the new tutorial page
2. Click on the "ADD IMAGES" button 
3. Try to drag an image from its original location.
4. Release the mouse button to drop the image.

**Expected behavior**
The dragged image should be successfully dropped in the designated location, and the project should respond accordingly.

**Screenshots**

https://github.com/scorelab/Codelabz/assets/135845175/31cdc84d-637a-4289-9fce-d8b1f6dc7cc3

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Microsoft Edge 

**Additional context**
The image does not drop as expected, and the drop zone does not register the drag-and-drop action.

**Comment by rohitPandey469** [comment]
When you hover your mouse just above the Browse or Choose files button then it's getting dropped but not in the entire section like whole sidebar thing and it's the restriction here

**Comment by aakash2330** [comment]
please assign this to me .
