### ISSUE TITLE
Responsiveness of the frontpage

### ISSUE THREAD

**Issue by Hardik-2311** [scorelab/Codelabz#1122]
<img width="261" alt="Screenshot 2024-01-18 180933" src="https://github.com/scorelab/Codelabz/assets/126074137/a0533acf-0658-443b-bed9-f36536d5d82a">

The purpose of this report is to address and provide solutions for the responsiveness issues observed in front page/main page of the project.

and some spacing issues in this http://localhost:5173/user-dashboard/profile page 

if you allow me i can make changes so that the site look feasible in mobile version

**Comment by Keshav-0907** [comment]
Their is already a issue for this  #1066

**Comment by Hardik-2311** [comment]
so can i work on this or not?

**Comment by SyedImtiyaz-1** [comment]
Can you please assign this to me?

**Comment by dheeraj0342** [comment]
@ABHISHEK-PANDEY2  please look this PR
