### ISSUE TITLE
[ Feat : Enhanced Saving Mechanisms in QuillEditor i.e. Debouncing, Manual Trigger, and Popup Reminders ]

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#1131]
**Is your feature request related to a problem? Please describe.**
In the QuillEditor, the yjs doc update function is triggered as soon as changes are made to the editor. This function makes a call to Firebase to update or set the document. However, if the user frequently types, it might cause unnecessary operations and potential performance issues.

**Describe the solution you'd like**
To address this issue, we can implement a combination of strategies:
1. **Delayed Saving (Debouncing):** Introduce a delayed saving mechanism (debouncing) so that the save operation is not triggered immediately on each change. We can set a delay of anywhere between 1-15 seconds, ensuring that the save operation is performed only after a period of inactivity.
2. **Manual Save Trigger:** Provide a "Save" button or another manual trigger to allow users to control when the changes are persisted to Firestore. This can be a button or an event (e.g., ctrl+S) that triggers the save operation.
3. Popup Reminder: Utilizing the popup mechanism introduced in the PR #1130 to display a reminder when changes are not saved. This can serve as a visual prompt, encouraging users to manually save their work.

**Describe alternatives you've considered**
As an alternative or additional measure, consider implementing a keydown event (e.g., ctrl+S) or a dedicated button for manual saving. This can offer users a quick way to save their changes without waiting for the delayed saving interval.

**Additional context**
Feedback from maintainers is appreciated. A combination of delayed saving, manual triggers, and popup reminders could provide users with flexibility and control over the saving process while mitigating unnecessary Firestore calls. Adjusting the delayed saving time can further optimize the user experience.

**Comment by prince-patel23** [comment]
Hi there! 👋 I'm new to the project and excited to contribute. **I would like to take on this issue**. It seems like a great opportunity to learn and make a meaningful impact.

_@rohitPandey469 , could you please assign this issue to me? I'll get started on implementing the proposed solutions: delayed saving (debouncing), manual save triggers, and popup reminders. I'll make sure to keep you updated on my progress._

**Looking forward to contributing to the QuillEditor project**

**Comment by rohitPandey469** [comment]
Hey @prince-patel23, I am also here to contribute and as you can see what's this issue about, if you have an idea or a way you can go ahead and implement it. No one's stopping you here and ask the maintainers @ABHISHEK-PANDEY2 @shivareddy6 @Sarfraz-droid about working on this issue.

**Comment by prince-patel23** [comment]
Hi @ABHISHEK-PANDEY2, @shivareddy6, @Sarfraz-droid! 👋 I'm keen to contribute to QuillEditor and interested in addressing issue **#1131**  for optimizing the doc update function.  **assign this issue to me, i can solve it and i am   Excited to learn and contribute!** 
*

**Comment by rohitPandey469** [comment]
@prince-patel23 Hi, here we would need multiple solutions cause everyone can have different ideas or ways and I have just mentioned some of the methods in the issue itself if you can go ahead and find a good approach do share and work on it. Happy coding :)

**Comment by prince-patel23** [comment]
Hi @rohitPandey469 ,

Thanks for reaching out! I'm excited to dive into the QuillEditor project and address the optimization issue with Firebase integration. Before I begin implementation**, I'll need some time to thoroughly review the codebase. Once I've familiarized myself, I'll start working on the implementation(max 3 days).**

Best,
@prince-patel23

**Comment by prince-patel23** [comment]
I noticed you're having trouble accessing the live project through the link in the README.md file.It don't work so what should i do to ! 

@rohitPandey469

**Comment by rohitPandey469** [comment]
@prince-patel23  The project is not live yet, it's just a dummy link... Solve Issues on localhost
