### ISSUE TITLE
[Bug]: Button Click on Select tags Does Not Trigger 

### ISSUE THREAD

**Issue by shikhar-4739** [scorelab/Codelabz#1132]
**Describe the bug**
 Clicking on the "Select tag" icon does not trigger the expected behavior of opening the tag selection modal. Users are unable to access the modal to choose additional tags for inclusion, impacting the intended functionality of the tag system in the project.

**To Reproduce**

1. Go to http://localhost:5173/org/settings/codelabzorg
2. Click on select tags icon
3. See error there is no response on clicking the button

**Expected behavior**
clicking the "Select tag" icon triggers the modal to appear, the user can select a tag, and the modal closes while adding the chosen tag to the visible tag section in the main view.

**Screenshots**

https://github.com/scorelab/Codelabz/assets/135845175/e1b73bd1-4efe-4c72-8185-f0b51ee060d3

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Microsoft Edge

**Additional context**

**Comment by Shashank-9680** [comment]
@shikhar-4739 Is this issue still open
