### ISSUE TITLE
[ Fix : Missing 'Bookmarks' Functionality - Unavailable Page at '/bookmarks' ]

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#1135]
**Describe the bug**
There is "No" Bookmarks function or "No" Bookmarks page, I would like to think currently it's not implemented...then it would have been a feature request however I am stating it here as a bug.

**To Reproduce**

1. Go to 'http://localhost:5173'
2. Click on 'Bookmarks' in the Sidebar.
3. Navigate to '/bookmarks'
4. No page is found.

**Expected behavior**
A page showing all the bookmarked tutorial should have displayed here at '/bookmarks'

**Screenshots**
It's broken
![image](https://github.com/scorelab/Codelabz/assets/123815256/65348c4d-2c2e-4cd1-89b4-498112bf7baf)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Additional context**
**We can do it by storing a field called bookmark on 'users profiles' and have the ids of all the bookmarked tutorials** and if we want to make it both ways or bidirectional then can have a field in tutorials for all the users who have bookmarked it, however it won't be a really scalable approach.
I am open to ideas do suggest me

**Comment by Shashank-9680** [comment]
@rohitPandey469 Is this issue still open

**Comment by rohitPandey469** [comment]
I was going through previous issues when I found that the bookmark toggle functionality had already mentioned in issue #1043 and it's corresponding PR, however the guy had made only the toggle thing work in that PR and in this PR I have did, adding a new field `bookmark` and then changing its value on each click and and then rendering the bookmarked tutorials in /bookmarks page... so my point is they are not the same or a copy of the previous PR :)
