### ISSUE TITLE
[ Feat : Interactive Sorting for 'Featured,' 'New,' and 'Top' Tutorials btn's in ActivityList ]

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#1138]
**Is your feature request related to a problem? Please describe.**
Currently, the activityList (i.e., "Featured," "New," "Top") lacks 'onClicks' that would filter tutorials data, instead just toggling between classes. I am considering making it work as the names suggest, showcasing "Top" tutorials, "Featured" tutorials, and "New" tutorials. By default, it's in the "New" format.

**Describe the solution you'd like**
Implementing a simple sorting mechanism:

1. **For New:**
   - The current format is already in the desired style.

2. **For Top:**
   - Sort based on likes or introduce an additional variable called ratings (incremented by 1 for each like and 2 for each comment). Alternatively, introduce a "view" variable and increase it with each click. To allow newer tutorials to rise in the rankings, I am thinking of applying a time decay factor function.

3. **For Featured:**
   - Mark tutorials by a specific author or someone noteworthy with a "tick" in their profile as featured. Developers can update this feature, and tutorials created by these users will automatically be featured. Additionally, could consider using ratings to influence the featured ranking.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Users will have a "tick" in their profile, indicating that they are authorized to be featured. Developers will update this information, and tutorials created by these users will be featured + Ratings will also contribute to the featured ranking of tutorials.

**Comment by rohitPandey469** [comment]
@ABHISHEK-PANDEY2 @Shiva-Nanda @Sarfraz-droid  do let me know about this modification.

**Comment by Shashank-9680** [comment]
@rohitPandey469 Is this issue still open

**Comment by vipulthakurr** [comment]
Is this issue still open,If yes I would like to work on this

**Comment by rohitPandey469** [comment]
@Shashank-9680 @vipulthakurr Hi, there's no PR corresponding to this issue so it's still open and this issue will allow multiple solutions. So, understand it and make it work in most optimized and clean way. Be sure, to communicate your ideas in threads. Happy coding :)
