### ISSUE TITLE
[Bug]:  Enable Tab Scroll for Better Navigation in "My Feed" section on Mobile Devices

### ISSUE THREAD

**Issue by shikhar-4739** [scorelab/Codelabz#1139]
**Describe the bug**
This issue addresses the current lack of scrollability for tabs within the 'My Feed' section when accessed on mobile devices. Presently, navigating through multiple tabs in the 'My Feed' option on mobile is challenging due to the absence of a scroll feature. 

**To Reproduce**

1. Go to 'My Feed' section
2. Access Tabs on mobile 
3. Scroll horizontally to see error

**Expected behavior**
Tabs within the 'My Feed' section on the mobile version should be scrollable. When there are multiple tabs, users should be able to scroll horizontally to access all tabs easily. This scroll functionality ensures a smoother and more user-friendly navigation experience, particularly on smaller screens.

**Screenshots**

https://github.com/scorelab/Codelabz/assets/135845175/80008461-344d-45dd-8c02-155ec48ba03b

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Microsoft Edge

**Additional context**
The goal is to enhance the mobile user experience by implementing scrollable tabs, allowing users to easily navigate through the content in the 'My Feed' section on smaller screens

**Comment by PoulavBhowmick03** [comment]
Hey @shikhar-4739  I am sorry but I had already created an issue regarding this problem 2 weeks ago. I would suggest as the project maintainers say to once just have a look at the issues before you create any issue.

**Comment by Shashank-9680** [comment]
@shikhar-4739 Is this issue still open
