### ISSUE TITLE
Bug: Unlimited string input makes website to overflow

### ISSUE THREAD

**Issue by DhairyaMajmudar** [scorelab/Codelabz#1147]
**Describe the bug**
If an user enters a lot of characters in the input fields of tutorial section, it causes the website to overflow in the x direction.
**To Reproduce**

1. Go to tutorial creation section 
2. Start making tutorial and enter a lots of characters in the input fields
3. Create the tutorial.

**Expected behavior**
The website must not overflow and for that, there must be a limit of characters in the input field.

**Screencast**

[Screencast from 2024-01-26 22-38-20.webm](https://github.com/scorelab/Codelabz/assets/124715224/681ef10a-6d4a-4523-a37f-54edf54829ad)

**Desktop (please complete the following information):**

- OS: Linux ( Debian )
- Browser Firefox
- Version Latest

**Smartphone (please complete the following information):**

- Device: N/A
- OS:  N/A
- Browser  N/A
- Version  N/A

**Additional context**
 N/A

**Comment by DhairyaMajmudar** [comment]
Hi @shivareddy6 @Maahi10001  I am currently working on this bug, My approach will be to limit the input characters limit to 25 for title section and 100 for summary section.

**Comment by rohitPandey469** [comment]
Hey @DhairyaMajmudar, I'm not a fan of restricting how long titles and summaries can be, unless we're running out of space in the database. Finding super long words on a learning platform is as rare as finding a unicorn, unless it's a spelling bee thing. And if a sentence is too long, it just goes to the next line, no biggie! You can see it for yourself in video #1151.

**Comment by DhairyaMajmudar** [comment]
Hi @rohitPandey469, my concern about restricting the characters is to prevent overflow, in the above-attached video you can see how the website is overflowing in x direction due to long strings in title.

**Comment by rohitPandey469** [comment]
Long Strings but witn no spaces... try one long string with spaces @DhairyaMajmudar

**Comment by DhairyaMajmudar** [comment]
Yes @rohitPandey469 in that case the line is wrapping to the new line, But we have to also consider the case if the user intentionally / non-intentionally writes the long strings w/o spaces.
