### ISSUE TITLE
To remove the console Warnings/Errors.

### ISSUE THREAD

**Issue by DhairyaMajmudar** [scorelab/Codelabz#1149]
**Describe the bug**
The console on inspect is showing warnings because of
- missing `key` 
- MUI props used in the wrong way
- Missing MUI props
- Key indexing done in wrong way
- React not imported from 'react'  

**To Reproduce**
Open the Console using inspect tools the warnings can be seen.

**Expected behavior**
To remove the warnings as much as possible from the console .

**Screenshots**

![image](https://github.com/scorelab/Codelabz/assets/124715224/8718ea46-2fb5-40ef-988e-0106d017ce71)

**Desktop (please complete the following information):**

- OS: Linux ( Debian )
- Browser Firefox
- Version Latest

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser N/A
- Version N/A

**Additional context**
N/A

**Comment by DhairyaMajmudar** [comment]
This warning can be removed by adding `key` prop in the `RightMenu.jsx` file.

**Comment by sanyamk0** [comment]
Hey @DhairyaMajmudar I want to work on this issue 
Please assign me this to work on it

**Comment by DhairyaMajmudar** [comment]
Thanks @sanyamk0 for showing your interest but I am working on this issue. Pls. look for another issue : )

**Comment by sanyamk0** [comment]
Sure!! @DhairyaMajmudar
