### ISSUE TITLE
[ Feat : Truncating the title's and summary's when the Cards are side by side ]

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#1151]
**Is your feature request related to a problem? Please describe.**
The current display of Tutorial Cards (i.e., cards containing the 'title' and 'description' of a tutorial) is visible in the following locations:
1. Homepage => "/"
2. Tutorials page => "/tutorials"
3. Potentially on the Profile Page in later stages of development => "/profile"

However, there are UI challenges associated with the display of Tutorial Cards:
- On the "/tutorials" page, where most cards are shown, longer titles or summaries can disrupt the UI layout. To address this, we propose truncating the title and summary to a fixed max width and max height (e.g., 250x290, similar to platforms like Udemy).
- On the Homepage or Profile Page, where cards with and without pictures are used, varying heights which is already present is enhancing the visual appeal, as the cards are not side by side. So if want fixed height then can add a show more or expand btn.

**Describe the solution you'd like**
1. For the "/tutorials" page, truncate the title and summary, fixing the max width and max height (e.g., 250x290).
2. If fixing the height on Home Pages, consider adding a "Show More" or "Expand" button to handle longer content.

**Describe alternatives you've considered**
Truncating the summary on the Homepage as well and incorporating a "Show More" or "Expand" button for longer content.

**Additional context**

https://github.com/scorelab/Codelabz/assets/123815256/7a43601f-9002-4913-ac3d-3a4626b85484

Truncating the title's and summary when the cards are side by side in "/tutorials".

**Comment by rudrakushwaha** [comment]
Hey @rohitPandey469 I want to contribute to the to the scorelab, also I have setup the codelabz in my local system. I have signed up to the codelabz but cannot signin after sign up . What's the problem?

**Comment by DhairyaMajmudar** [comment]
Hi @rudrakushwaha for sign up you have to run the emulators again using the make commands.
Hope this help : )

**Comment by rudrakushwaha** [comment]
@DhairyaMajmudar I had run the emulators that's why the signup window worked and a success message was shown after my successful signup but after that when I am trying to sign in, it does not directing me to anywhere but only the signin page itself.

**Comment by rudrakushwaha** [comment]
![image](https://github.com/scorelab/Codelabz/assets/113119934/d1b5e7f8-b5f1-418f-ad66-3f340b6ba9a6)
![image](https://github.com/scorelab/Codelabz/assets/113119934/9d44c907-0aeb-4beb-916d-1cebce4152f3)

Hey @rohitPandey469 , @DhairyaMajmudar I saw through this issue to truncate the strings but after I setup the envirnment and log in I do not see any such tutorials posts in the homepage neither I am able to create any tutorial as I see no option in the select section. What's the issue ?

**Comment by rudrakushwaha** [comment]
https://github.com/scorelab/Codelabz/assets/113119934/efd8400e-e95f-4830-a710-a4472add3799

**Comment by Sujal267** [comment]
Is the issue still open? Can I work on it?

**Comment by rohitPandey469** [comment]
@rudrakushwaha 
1. Log In with dummy accounts that are provided already i.e. codelabz or Sarfraz or Mahendar Id, these Id will show up when you try to log in and if they don't show then run this command in cmd  inside codelabz project `fireabse emulators:start --import=testdata`
2. After logging in you will have a organization to select instead of `No Options`, while creating tutorial.
Then go ahead and work on this issue. Happy coding :)

**Comment by rohitPandey469** [comment]
@Sujal267, there's no PR corresponding to this issue, so it's still open.

**Comment by Sujal267** [comment]
> @Sujal267, there's no PR corresponding to this issue, so it's still open.

I have already made a PR

**Comment by rohitPandey469** [comment]
@Sujal267 Nice, link it here then.

**Comment by Sujal267** [comment]
[PR](https://github.com/scorelab/Codelabz/pull/1174#issue-2126818642)

**Comment by rohitPandey469** [comment]
In the body of the PR write somewhere Fixes #PR_NUMBER, bot will automatically link it with this issue
