### ISSUE TITLE
incorrect Initial Display on User Settings Page

### ISSUE THREAD

**Issue by YashGupt29** [scorelab/Codelabz#1162]
**Describe the bug**
issue Description:
Upon clicking "User Settings" in the sidebar, the expected behavior is for the page to start with the selected profile as indicated in the sidebar. However, the current behavior displays the text "User Settings" instead of the user's profile, which can be confusing and counterintuitive for users.
**To Reproduce**
Steps to Reproduce:
Navigate to the sidebar.
Click on "User Settings".
Observe the initial display of the page.

**Expected behavior**
The page should begin by displaying the selected profile, reflecting the user's intention in accessing the settings.
**Screenshots**

[Screencast from 03-02-24 03:14:23 PM IST.webm](https://github.com/scorelab/Codelabz/assets/136692180/80e2a847-b392-4bc7-8035-7dca09c1cf5f)
solution 
[Screencast from 03-02-24 03:14:55 PM IST.webm](https://github.com/scorelab/Codelabz/assets/136692180/d9553e82-f420-4672-adac-6974c0facc93)

**Comment by r-nikhilkumar** [comment]
Hey there, I'm interested to solve this issue, but I'm not clearly getting it can you plz explain in more details
