### ISSUE TITLE
Down Votes for a particular tutorial goes to negative

### ISSUE THREAD

**Issue by wilsonfurtado2000** [scorelab/Codelabz#1175]
**Describe the bug**
Whenever a user downvotes a tutorial the down vote count goes to negative and does not stop at zero.
**To Reproduce**

1. Click on the profile icon on the top right corner and select "My Profile" from the drop down 
2. Go to any of the tutorials and downvote the tutorials
3. you will be able to see the down votes going in negative

**Expected behavior**
The downvote count should not go below zero

**Screenshots**
<img width="1296" alt="Screenshot 2024-02-09 at 11 49 59 AM" src="https://github.com/scorelab/Codelabz/assets/72563697/ab7a5789-ec79-45ea-9eab-6b278a8c0b8b">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Safari
- Version v4.5.2

**Comment by lavish123409** [comment]
As no one has commented yet, I would like to work on this issue.
