### ISSUE TITLE
Social media Icons not working 'My profile' page

### ISSUE THREAD

**Issue by wilsonfurtado2000** [scorelab/Codelabz#1202]
**Describe the bug**
Currently in the 'My profile' page the social media icons are not working
**To Reproduce**

1. Login/Register
2. Click on the top right profile icon
3. Select My profile from the dropdown
4. click on the social media icons

**Expected behavior**
On clicking on the social media icon it should direct to the respective site, if the user has provided a link to the social media accounts , then these social media icons shouldn't be displayed 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rohitPandey469** [comment]
Appreciate it @wilsonfurtado2000 but this issue has already been resolved, check issue #1069 and corresponding PR.
If you want, you can solve for something else like if any social_url is empty ( say git or facebook or linkedin...) then do not show that Icon at My Profile Page and if present then show it.
