### ISSUE TITLE
[Fix]: Clicking on Delete Button Does Not Initiate Account Deletion

### ISSUE THREAD

**Issue by shikhar-4739** [scorelab/Codelabz#1207]
**Describe the bug**
Currently, clicking on the "Delete" button in the user settings does not trigger any action, resulting in no response from the application. This issue prevents users from initiating the account deletion process, impacting their ability to manage their account preferences and privacy settings effectively.

**To Reproduce**

1. Go to user settings
2. Click on "Delete Account" Button
3. See error

**Expected behavior**
Upon clicking the "Delete Account" button, the application should display a confirmation modal and after that initiate the account deletion process.

**Screenshots**

https://github.com/scorelab/Codelabz/assets/135845175/68f21854-cd34-4aff-ba49-beb5a4958acc

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Microsoft Edge

**Additional context**

**Comment by kushalShukla-web** [comment]
i like to take this issue
