### ISSUE TITLE
Password can be copied to Confirm password Field . 

### ISSUE THREAD

**Issue by kushalShukla-web** [scorelab/Codelabz#1213]
**Describe the bug**
So basically when we are trying to create a new account , the user can easily copy the password from new password field . what i want here is like when user try to copy paste password in new password field , then it should avoid doing so . 

**To Reproduce**

1. Go to 'Create account '
2. try type some password on new password and copy that password on confirm password field , you will see you can do this . 

**Expected behavior**
wanted to avoid doing so .
**Screenshots**
![Screenshot from 2024-02-20 04-51-19](https://github.com/scorelab/Codelabz/assets/85934954/074e33f2-f55e-40e1-a011-be0b8a248d6f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kushalShukla-web** [comment]
im working on it , create pull request today only

**Comment by rohitPandey469** [comment]
@kushalShukla-web Try exploring issues with the UI in login or signup form as well.

**Comment by kushalShukla-web** [comment]
@rohitPandey469 can you give those UI issues link here .

**Comment by kushalShukla-web** [comment]
okay will go through
