### ISSUE TITLE
Google OAuth API Key Expired

### ISSUE THREAD

**Issue by uzair-ali10** [scorelab/Codelabz#164]
**Description of the bug**
The API Key for Google OAuth Have expired 

**To Reproduce**
1. Go to [https://dev.codelabz.io/signup](https://dev.codelabz.io/signup)
2. Click on the goggle icon which is visible below create account button

**Expected behavior**
It should open a new tab which leads to Authorizing CodeLabz to their google account

**Screenshots**
![Screenshot from 2021-08-02 09 57 06](https://user-images.githubusercontent.com/72073401/127804788-b13a97c9-b719-4dbc-bb6e-256748a19d8c.png)

**Additional context**
The API Key for OAuth Should be renewed, I would love to solve up this issue

**Comment by rijusougata13** [comment]
hey @uzair-ali10 thanks for showing interest in this. This is hosted (that specific link)in different account and currently we dont have access to change the api.If you want to contribute in something else feel free to open an issue and work on it.

**Comment by uzair-ali10** [comment]
@rijusougata13 
Yea I figured that out that I might not gain access to wherever it is hosted. However, while trying to set up the project locally I encountered some errors and I've also opened up a separate issue for this #165 , Kindly have a look at it

**Comment by uzair-ali10** [comment]
@rijusougata13 
This same issue persists in signing up a user without any 3rd party service

https://user-images.githubusercontent.com/72073401/127808558-f301db72-8e8e-4658-9df7-7af4503fbc85.mp4

This is something critical as it blocks all the ways a new user can be signed-up

**Comment by rijusougata13** [comment]
Actually you are using email and password to sign up and it also using firebase auth behind. So its not working here. You have to manually use your firebase api in env and start this project in local, all of setup mentioned in readme. I'll try to contact who have proper access to this api and fix this issue.

**Comment by rijusougata13** [comment]
problem fixed. closing this isuue.
