### ISSUE TITLE
Could Not set up the project Locally

### ISSUE THREAD

**Issue by uzaxirr** [scorelab/Codelabz#165]
**Describe the bug**
An error occurred while trying to set-up the web-app locally 

**To Reproduce**
1. Clone the repo and navigate to the root directory
2. do `npm install`
3. See the error

**Expected behavior**
This should successfully install all the required node modules and build the app

**Screenshots**
![Screenshot from 2021-08-02 10 32 14](https://user-images.githubusercontent.com/72073401/127806880-5b40fd24-d3fa-438b-8af5-aaa61320a775.png)

**Desktop (please complete the following information):**
 - OS: Elementry OS (Based on Ubuntu 18.04)

**Comment by rijusougata13** [comment]
There is some dependency error , can you try to force install to fix the conflict and check if its fixed or not. you can refer 3rd line from the last in this error image.

**Comment by uzair-ali10** [comment]
@rijusougata13 
I tried force installation and spent almost 2 hours trying to resolve the conflict but all in vain
![Screenshot from 2021-08-02 15-02-47](https://user-images.githubusercontent.com/72073401/127842605-da26729e-3831-4bd0-8296-e041075f8df7.png)

Can u please try to set it up locally by yourself I'm sure you'll encounter the same issue

**Comment by rijusougata13** [comment]
> @rijusougata13
> I tried force installation and spent almost 2 hours trying to resolve the conflict but all in vain
> ![Screenshot from 2021-08-02 15-02-47](https://user-images.githubusercontent.com/72073401/127842605-da26729e-3831-4bd0-8296-e041075f8df7.png)
> 
> Can u please try to set it up locally by yourself I'm sure you'll encounter the same issue

Yes I am currently working on this project so I have  this locally(ubuntu 18) running , eventually I have installed it to a diffrent machine(win10) 2days ago and it working fine.
Can you post the screenshot after npm force install ? have you run ```npm start``` after  setting up .env file at root directory like mentioned in readme? 
After this please update you node and npm version to latest , delete node modules folder and rerun npm install.
sometimes its maybe issue with webpack if none of the previous method work try to install with yarn.

**Comment by satyaarthchhabra** [comment]
i also faced the same issue . then i tried to reconnect my internet and it work fine for me . hope this could help you
