### ISSUE TITLE
Org Profile Loading Issue and UI should fixed 

### ISSUE THREAD

**Issue by piyumaldk** [scorelab/Codelabz#185]
Loading screen keeps  loading hence data was not fetched 
![bug](https://user-images.githubusercontent.com/38649090/132550086-f04ddb1d-59f0-4ab8-8ea8-39f77db2befc.png)

**Comment by satyaarthchhabra** [comment]
hi @piyumaldk  . can i work on this issue

**Comment by rijusougata13** [comment]
> hi @piyumaldk . can i work on this issue

hi @satyaarthchhabra  . It is fixed by this #186  PR.
