### ISSUE TITLE
'New Codelab' Button on the Home page

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#187]
Buttons in the HomePage are not working like Save and New CodeLabz

New CodeLabz button are working 'My tutorials' but on Home its not working.

I would really like to work on this issue

**Comment by rijusougata13** [comment]
go ahead

**Comment by Sarfraz-droid** [comment]
Hi, On adding a new codelabz. it just redirects to localhost:3000... what could be the issue?? 
thanks 

![2021-12-02-18-20-03](https://user-images.githubusercontent.com/73013838/144425748-f0dd58ec-9e86-4eca-8517-3c299ee33702.gif)

**Comment by rijusougata13** [comment]
Its definitely an issue. You can open a issue regarding this
