### ISSUE TITLE
Fix context-menu icons

### ISSUE THREAD

**Issue by kailash360** [scorelab/Codelabz#188]
**Describe the bug**
The icons on the context menu are not aligned properly with the following text. 

**To Reproduce**
1. Go to the top-right section of the page
2. Click on the image of the user
3. Context menu pops below the image

**Expected behavior**
The icons should be aligned with the text

**Screenshots**
![image](https://user-images.githubusercontent.com/75155230/143781223-d03b6de6-1cd7-4d95-bab7-46fd7732aaac.png)

**Comment by kailash360** [comment]
Can I work with this issue?

**Comment by rijusougata13** [comment]
yep go ahead

**Comment by kailash360** [comment]
@rijusougata13, I have created PR #189 for this issue
