### ISSUE TITLE
Fix of Database Url in firebase Config

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#190]
**Describe the bug**
I have been getting issues while setting the app up on development. The issue was the my project id was different from the database url

**Screenshots**
Old 
![image](https://user-images.githubusercontent.com/73013838/144382994-76bdc832-4d20-45be-b289-a35d74b7762e.png)

New
![image](https://user-images.githubusercontent.com/73013838/144383043-539e7bab-fb68-44f8-bb4a-2b7d71807351.png)

**Additional context**
I have fixed the issue. I ll put up a PR as soon as I get any approval

**Comment by kushalShukla-web** [comment]
Can I work on this
