### ISSUE TITLE
Organisation not setting up in local machine

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#191]
Even thourgh I have an organisation in my databse for the user. Still my local app is showing organisations as false. Is this an issue or a bug with my environment??

Firebase Database
![image](https://user-images.githubusercontent.com/73013838/144436977-f6b9473a-ec6b-4709-9acb-cdcddcab2c4c.png)

App
![image](https://user-images.githubusercontent.com/73013838/144437043-03edbec6-5cc0-42cc-abe3-188274f249e7.png)

**Comment by rijusougata13** [comment]
This is a bug I think. you can go ahead and create a PR.

**Comment by karthxk07** [comment]
@Sarfraz-droid @Maahi10001 Sir, Is this issue resolved, i see this closed due inactivity. Can i work on this ?
