### ISSUE TITLE
New CodeLab Button is overlapping from 1019px

### ISSUE THREAD

**Issue by Janvi-Thakkar** [scorelab/Codelabz#193]
I was testing the codeLabz site for responsiveness. I found many components are not responsive. One of the main bugs is that the New CodeLab button is overlapping from 1019px. It is not available for the width of 600px to 960px.

**To Reproduce**
1. Go to CodeLabz size when with window width<960px
2. Try to observe the behavior of the New CodeLab button
3. You will observe the bug.

We should have a responsive navbar.

**Comment by rijusougata13** [comment]
Thanks @Janvi-Thakkar  for raising the issue. You can go ahead a send a pr.

**Comment by Janvi-Thakkar** [comment]
Sure. working on it

**Comment by Janvi-Thakkar** [comment]
I have made the pull request. Please review it. @rijusougata13 @thisuraseniya
