### ISSUE TITLE
Back to Home button from login page not available for screen-width<960px

### ISSUE THREAD

**Issue by Janvi-Thakkar** [scorelab/Codelabz#196]
**Describe the bug**
There is no option for user to go back to home screen once user goes to login screen for screen-width<960px

**To Reproduce**
1. Click on login button given on home screen
2. Please ensure that screen width< 760px
3. There is no option to go back to home

**Expected behavior**
User should be able to go back to home screen

**Comment by ARKEOLOGIST** [comment]
Some screenshots would be nice.

**Comment by kushalShukla-web** [comment]
guys i wanna work on this issue
