### ISSUE TITLE
Big Errors on login page should be small and concise to make user aware about the problem

### ISSUE THREAD

**Issue by Janvi-Thakkar** [scorelab/Codelabz#197]
**Describe the bug**
If an error is coming on login page, it should be represented in meaningful sentence to user 

**To Reproduce**
1. Go to login screen
2. Facebook and Google login is creating error for me

**Expected behavior**
error should be small and concise to make user aware about the problem

**Screenshots**
![image](https://user-images.githubusercontent.com/55620053/148270690-ef566951-1090-44e7-8743-1db9c1549a92.png)

**Comment by srrathi** [comment]
Hello @rijusougata13 , Is this issue still open ? I will like to work on it.

**Comment by kushalShukla-web** [comment]
yep im also getting this error
