### ISSUE TITLE
Extra whitespace occurs to the right of the top navbar for certain resolutions

### ISSUE THREAD

**Issue by ARKEOLOGIST** [scorelab/Codelabz#198]
**Describe the bug**
Extra space occurs to the right of the navbar for screen sizes in between 600px to 707px and for sizes lesser than 572px. 

**To Reproduce**

1. Click on 'Login' on the home screen
2. Resize the screen and notice the gap to the right

**Expected behavior**
There should not be any overflow of any kind.

**Screenshots**

![extra_space](https://user-images.githubusercontent.com/34165124/148660537-46f9e214-1558-45a4-9b2e-cd44a06b8416.PNG)
![spacing_extra](https://user-images.githubusercontent.com/34165124/148660540-bb800143-b402-4844-9d7d-6eee2227a8db.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Brave 
 - Version: 1.34.80

**Comment by kushalShukla-web** [comment]
hey can i work on this issue ?
