### ISSUE TITLE
Add functionality to like and comment buttons

### ISSUE THREAD

**Issue by menakinako** [scorelab/Codelabz#204]
**Is your feature request related to a problem? Please describe.**
Yes...In the home page, all the like buttons, and comments are hardcoded, also clicking the buttons has no effect.

**Describe the solution you'd like**
 I would like to add functionality to the like and comment buttons. On clicking the like button the like value will increase to 1 and for comments, I would like to add a comment section on clicking the comment button where one can add any comment messages.

**Describe alternatives you've considered**
Instead of a hardcoded value for the like button, I will add functionality that only if the user is logged in, he/she can like the post which will increase the like value to 1 and also can add any comment in the comment section. 

**Additional context**

https://user-images.githubusercontent.com/72397937/151964419-7bb175bc-e183-4d1f-beba-6e5310cb70c0.mp4

@rijusougata13 Can I work on this issue?

**Comment by aliraza944** [comment]
Hi, If no one is assigned to this issue I would love to have a go on it.
