### ISSUE TITLE
createMuiTheme error

### ISSUE THREAD

**Issue by sakkshm26** [scorelab/Codelabz#206]
**Describe the bug**
createMuiTheme (imported from **"@material-ui/core/styles")** is deprecated. 

**To Reproduce**
1. Go to the project folder in your IDE
2. Open src/helpers/themes.js
3. See error

**Expected behavior**
**createMuiTheme** is no longer used, it should be replaced with **createTheme**.

**Screenshots**

![Screenshot (461)](https://user-images.githubusercontent.com/87091886/152341254-c5b4277d-87ee-4c3a-b30f-dcac994faf02.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 97.0.4692.99

**Comment by kushalShukla-web** [comment]
this issue is still open
