### ISSUE TITLE
New CodeLab button is not working

### ISSUE THREAD

**Issue by Janvi-Thakkar** [scorelab/Codelabz#211]
**Describe the bug**
New Codelab button on should add post in feed. so that website would become dynamic and interactive for users.

**To Reproduce**
1. Go to Home page
2. Click on New Codelab button in navbar
3. button is not in action

**Expected behavior**
New Codelab button on should add post in feed.

**Comment by Yash621** [comment]
@Janvi-Thakkar can i work on this ?

**Comment by Janvi-Thakkar** [comment]
@Yash621 Thank you for showing interest. I am working on it already. I was exploring if I could link this button with any available page and I found one. So, I will send PR soon.
