### ISSUE TITLE
Popular Events box not responsive between 750px and 865px

### ISSUE THREAD

**Issue by sakkshm26** [scorelab/Codelabz#215]
**Describe the bug**
The Popular Events box is not responsive between screen width 750px and 865px.

**To Reproduce**
1. Go to localhost:3000 (CodeLabz home page)
2. Reduce and set the screen width between 750px and 865px.
3. See the Popular Events box

**Expected behavior**
This section should be responsive for all the widths.

**Screenshots**

![Screenshot (462)](https://user-images.githubusercontent.com/87091886/153029443-ac521ab8-9426-4892-95b1-122839e699bb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 97.0.4692.99

**Comment by kushalShukla-web** [comment]
hey i can do this
