### ISSUE TITLE
[GSoC 2020] CodeLabz Pre GSoC Task

### ISSUE THREAD

**Issue by charithccmc** [scorelab/Codelabz#225]
CodeLabz Pre GSoC Task

1.  Provide your new material ui design for CodeLabz front end using design tools([Figma](https://www.figma.com/), or etc) . Design follwing componets

> >Home Page, News Feed, User Profiles, User Setings, Organization Profiles, Organization Setings (~175 hours)

2. Setup CodeLabz Design Systems using storybook ([Storybook Design Systems](https://storybook.js.org/tutorials/design-systems-for-developers/))

**Comment by shahaab** [comment]
Hey @charithccmc, I made a few changes to the design a month ago on the existing landing page. I would like to get your feedback on it. 
link to the figma file : https://www.figma.com/file/3UqPxwzhNUmY36UpjY0gLz/Landing-page?node-id=0%3A1 
![CodeLabz](https://user-images.githubusercontent.com/41134301/154813101-5ef387f9-d460-49d0-b7ba-6ea70648c019.png)

There are a few sections that require major redesigns such as the Explore Codelabz and the landing page. I'm working on creating a completely new UI design from scratch.
(i) Adding new features on the landing page that are a must such as having trending now, best of this month, featured on Codelabz.
(ii) Browse section which will have all the courses according to their category.
(iii) Notification section.
(iv) My courses ( which would include all the saved classes, my history).
(v) A section that will give organizations a well-documented format as to how the course must be structured.
Thus making Codelabz easy to navigate and more user-friendly.

Please let me know if there are any further changes to be made.

@charithccmc I would like to work on this task.

**Comment by charithccmc** [comment]
@shahaab pls design all the componets

**Comment by shahaab** [comment]
@charithccmc Sure! Here is the link to the Figma file where I will be working. https://www.figma.com/file/KLksVAax8A1npzbg64rQGe/Components-design?node-id=0%3A1

**Comment by Janvi-Thakkar** [comment]
@charithccmc Is there any strict color theme to be followed or I can decide myself?

**Comment by charithccmc** [comment]
yes

**Comment by charithccmc** [comment]
@Janvi-Thakkar current color are ok for us but you can use any.

**Comment by Janvi-Thakkar** [comment]
@charithccmc, got it. Thank You!

**Comment by Gaurav4code** [comment]
In this design, I have tried something different from the existing design. 
a) Changed the font to DM Sans
b) Change the color combination.
c) Using feather icons.
![Screenshot 2022-02-22 092655](https://user-images.githubusercontent.com/85581658/155098035-0d3d0d5c-972e-4b49-ae10-3589794bab05.jpg)
Click here to see the Figma file.
https://www.figma.com/file/J6VYaqtc2exZWcphxVJxKb/Untitled?node-id=2%3A2

**Comment by IITvamp** [comment]
@charithccmc can you please tell which page you are referring to as the user setting page?
![image](https://user-images.githubusercontent.com/77586067/155146065-4515e5fb-2748-4f53-b631-42c4365dd9e0.png)

is this the page? or the edit profile form? or some other page.

**Comment by IITvamp** [comment]
@charithccmc 
here is link to prototype of my design
https://www.figma.com/proto/GjgFiL00DX1GfoO6UUefSH/CodeLabz?page-id=0%3A1&node-id=42%3A2405&viewport=241%2C48%2C0.35&scaling=scale-down-width

**Comment by charithccmc** [comment]
Pls don't share your Figma here, It's included in your proposal and share with me via Gitter (https://gitter.im/charithccmc)

**Comment by sahilsaini110** [comment]
@charithccmc Is it necessary to make it look like a typical E-learning website, or may we attempt something different?

**Comment by charithccmc** [comment]
@sahilsaini110 pls follow the existing design

**Comment by sahilsaini110** [comment]
@charithccmc I have sent you my design of codelabz please review.
In gitter chat.

**Comment by charithccmc** [comment]
Pls complete task 1 and 2, after that we will review your work

**Comment by charithccmc** [comment]
Tip for task 2:
Storybook+React+Figma: https://www.youtube.com/results?search_query=design+system+storybook+

**Comment by IITvamp** [comment]
@Janvi-Thakkar I think he is asking to create a storybook for the design we have created in task 1 for Codelabaz. @charithccmc  please confirm.

**Comment by charithccmc** [comment]
@IITvamp yes

**Comment by charithccmc** [comment]
@Janvi-Thakkar current storybook is outdated, you need to create a new storybook for your design.

**Comment by Janvi-Thakkar** [comment]
@charithccmc @IITvamp got it. Thank You!
