### ISSUE TITLE
alignItems and maxWidth error in console

### ISSUE THREAD

**Issue by sakkshm26** [scorelab/Codelabz#226]
**Describe the bug**
Some errors related to alignItems and maxWidth are visible in console.

**To Reproduce**
1. Go to [localhost:3000](http://localhost:3000/)
2. Click on Inspect
3. Go to Console
4. See errors

**Expected behavior**
The errors should be resolved.

**Screenshots**

![Screenshot (466)](https://user-images.githubusercontent.com/87091886/154856569-ca0e43d8-7c5a-41ce-b5bd-71a2177d99dc.png)
![Screenshot (467)](https://user-images.githubusercontent.com/87091886/154856579-55801ff3-2514-4eb5-88ba-bb53027c0b09.png)
![Screenshot (468)](https://user-images.githubusercontent.com/87091886/154856585-64dc8c35-65b1-4b65-8be5-ae37194d5ea2.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 97.0.4692.99

**Comment by Janvi-Thakkar** [comment]
@sakkshm26 I think this is sub-issue covered by the issue #217

**Comment by sakkshm26** [comment]
Yes, but there are many errors in the console, so I'm trying to divide them into smaller issues so that they can be reviewed easily.

**Comment by Janvi-Thakkar** [comment]
That's true, I would suggest renaming issue #217. So maybe other people don't get confused by that.

**Comment by sakkshm26** [comment]
Shall I divide the console errors into different issues or combine them in the same one @rijusougata13?
