### ISSUE TITLE
Unwanted files and correction in file-naming

### ISSUE THREAD

**Issue by aswin2108** [scorelab/Codelabz#229]
**Description of the issue:**
    Some unwanted files in React Boilerplate application are still there in the repo. 
Files like 
+ `logo.svg` 
+ `favicon.ico` etc
has a react logo! 
Also in [readme.md](https://github.com/scorelab/Codelabz#readme) its saying to refer to `.env.example` file to fill in `.env` file while cloning but in the repo the `.env.example` is misspelled as `.env.sample` so its a mismatch. I would like to work on this issue.

Can anyone pls assign this issue to me so that I work on this issue, and make this my first contribution to this project? @charithccmc 

**ScreenShot of one such file:**

![image](https://user-images.githubusercontent.com/72661784/156926773-f323534a-713d-4de4-9dbf-56270b1aa06a.png)

**Comment by kushalShukla-web** [comment]
hey i have managed to create a pull request . u can close this issue
