### ISSUE TITLE
husky hooks 

### ISSUE THREAD

**Issue by priyang12** [scorelab/Codelabz#230]
## Add husky hooks for the same Prettier formatting for everyone.

Feature
Use Prettier to automatically format the JavaScript and use husky and lint-staged to add a precommit script that runs Prettier and your tests when you commit. Same Prettier formatting will be applied to everyone.

Additional context
This will help different developers to develop the code and when pushing the code to repo it will look the same for all the developers. For Open-Source having consistently formatted code is important for readability and maintainability. 
In pull request [PR-203](https://github.com/scorelab/Codelabz/pull/203) formating problem can be avoided.

**Comment by akib22** [comment]
I want to work on this issue. @charithccmc @rijusougata13 can you please assign it to me?
