### ISSUE TITLE
Link for Tutorials does not work sometimes

### ISSUE THREAD

**Issue by sakkshm26** [scorelab/Codelabz#236]
**Describe the bug**
The link for the Tutorials does not work when the user clicks around the text.

**To Reproduce**
1. Go to localhost:3000 (CodeLabz home page).
2. Click on the icon beside the profile icon.
3. Click around the text "Tutorials".

**Expected behavior**
The link should work whenever the user clicks inside the section.

**Video**

https://user-images.githubusercontent.com/87091886/158992037-6134e4d3-0c1b-4c93-97d6-90fba5fae5ba.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 97.0.4692.99

**Comment by kushalShukla-web** [comment]
hey can i work on this
