### ISSUE TITLE
Tutorial Save Button Bug 

### ISSUE THREAD

**Issue by Maahi10001** [scorelab/Codelabz#242]
**Describe the bug**
The Bug is Save Button isn't working  and responding

**To Reproduce**
1. Go to 'website'
2. Click on '.tutorial'
3. Scroll down to 'input field'  after entering the all detials try click on save

**Expected behavior**
The details need to be save and reflected in the site

**Video- check the video for bug**
https://files.gitter.im/5eb21f15d73408ce4fe2cb37/unym/CodeLabz---Google-Chrome-2022-04-01-23-27-46.mp4

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]

**bug-video--**
https://user-images.githubusercontent.com/80961448/161370072-08e3c3ce-43fb-44f7-b64d-4d23a41d2441.mp4

**Comment by anwersayeed** [comment]
@charithccmc  I want to work on this issue, please assign this issue to me.

**Comment by Maahi10001** [comment]
I have resolved the error @anwersayeed  @charithccmc   I can close the issue right?

**Comment by kushalShukla-web** [comment]
is this issue still open ?
