### ISSUE TITLE
There can be a custom Right side and left side Bar with related menu's for codelabz

### ISSUE THREAD

**Issue by Maahi10001** [scorelab/Codelabz#246]
**Is your feature request related to a problem? Please describe.**
Currently the Right side and left side bar of site are just Staic text they can be designed as custom components

**Describe the solution you'd like**
Designing custom Right side Bar and Left side Bar 

**Additional context**
.
![image](https://user-images.githubusercontent.com/80961448/161441188-69b22b36-d191-4752-a8e2-35c3c16d91df.png)

I Just added My custom right and left bar which are okayish then before  I guess.

**Comment by kushalShukla-web** [comment]
hey so did u make these changes , cause im not able to find them

**Comment by Maahi10001** [comment]
> hey so did u make these changes , cause im not able to find them

i changed them in my local.
