### ISSUE TITLE
Unable to sign in Sign-up

### ISSUE THREAD

**Issue by itsmedeepak** [scorelab/Codelabz#247]
**Describe the bug**
User not able login or signup. After creation of account a verification mail sent to user account but error occured here because user didn't get any verification mail

**To Reproduce**
1. Go to 'http://localhost:3000/signup'
2. Click on 'login'
3. See error

**Expected behavior**
Able to sign in sign-up

**Screenshots**
![image](https://user-images.githubusercontent.com/74102432/162019366-5e4552e9-f8d9-4703-9322-2ac7bb7ba017.png)

**Desktop (please complete the following information):**
 - OS: Windows/Ubuntu
 - Browser : chrome

**Comment by Maahi10001** [comment]
Hey @itsmedeepak  as @Janvi-Thakkar  Said Go to the console of your Firebase database of the project .There you can change  plan to firebase From "spark" to "Blaze" plan 
1. Log in to the Firebase Console. In the lower left, you will see that your project is listed on the Spark plan. Click the upgrade button.
2. Select the Blaze plan
3. Select a billing account. Then click Continue and Purchase. And there you go on the Blaze plan.
