### ISSUE TITLE
forced requiring of profile fields

### ISSUE THREAD

**Issue by priyansh71** [scorelab/Codelabz#254]
**Describe the bug**
Edit profile requires mandatory addition of all profile links and fields, which can be annoying if user does not wish to provide all of them.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the homepage and click on the login button.
2. Login with your account and click user avatar on the top right.
3. Press the edit profile button.
4. Fill only some of the required text fields and click on the save button.
5. Saving and exiting is not allowed as all fields are required.
6. See the error.

**Expected behaviour**
If a user wishes to fill only some of the required fields and save, he should be allowed to do that.

**Screenshots**

<img width="606" alt="Screenshot 2022-04-11 at 01 32 24" src="https://user-images.githubusercontent.com/77532581/162638327-2d0ccb21-b645-47b3-a4d9-76750a87460e.png">

**Desktop :**
 - OS: macOS Monterey 12.1.0
 - Browser: Google Chrome
 - Version : 97.0

**Comment by Ashwin-hp** [comment]
Can I work on this issue?
