### ISSUE TITLE
UI/UX of the profile section 

### ISSUE THREAD

**Issue by priyansh71** [scorelab/Codelabz#259]
**Is your feature request related to a problem? Please describe.**
- It doesn't feel user friendly to have editing profile options at two different place, separately for image and information editing.
- User Profile design leaves a lot of whitespace on the right side, as all the content feels congested on the left.
- In case of Mobile view, the Profile picture looks too large.

**Screenshots** : 

<img width="1435" alt="Screenshot 2022-04-12 at 12 58 39" src="https://user-images.githubusercontent.com/77532581/162905437-018641b4-5db3-40c9-bc5f-e834eb811e8f.png">

![WhatsApp Image 2022-04-12 at 13 00 39](https://user-images.githubusercontent.com/77532581/162905523-ac22fd75-ac63-4b11-9848-dcea4f9d3371.jpeg)

**Describe the solution you'd like**
- The ```Edit profile Picture``` button can be moved to the ```Options``` menu.
- The design of the Profile section can changed to accomodate information and the image uniformly and avoid congestion.
- The image can be converted into an avatar with responsive size for mobile devices.

**Comment by shahaab** [comment]
There is a new profile section now and this is not required anymore!!
