### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by Abhiavati20** [scorelab/Codelabz#262]
Before registering a user, the platform should verify his/her email by mailing a link to verify his email. Once the user mail is verified then only he can join the community

**Comment by anshyyy** [comment]
Is this issue still open ?

**Comment by dasanik2001** [comment]
I would like to work on this issue. Please assign the same to me !

**Comment by Mayshank18** [comment]
Hey @charithccmc @kasundezoysa @anshyyy  If no one has been assigned this issue you can hand it over to me. I have already solved an issue related to email verification before in a live project.

**Comment by anshyyy** [comment]
@Mayshank18 @dasanik2001 I checked their website and this features has been implemented already. :)

**Comment by soulpredator0** [comment]
I know the full concept of email verification, please assign this issue to me.
