### ISSUE TITLE
UI/UX of codelabz 

### ISSUE THREAD

**Issue by Abhiavati20** [scorelab/Codelabz#263]
This is my personal opinion that I feel the UI of codelabz is not consistent thoroughly. 
The UI is very much similar to the UI of dev.to [
![Screenshot from 2022-04-12 20-59-09](https://user-images.githubusercontent.com/67231117/162999034-854ec506-1a93-4afc-9eca-d71c00a0eae6.png)
](url)
![Screenshot from 2022-04-12 20-59-04](https://user-images.githubusercontent.com/67231117/162999050-570ae6b5-0668-4487-8a2d-c9f9490006a7.png)

**Comment by kushalShukla-web** [comment]
Can I work on it or u working

**Comment by Abhiavati20** [comment]
> Can I work on it or u working

Yes, Absolutely you can work on it.

**Comment by kushalShukla-web** [comment]
hey i want to work on this
