### ISSUE TITLE
new design for codelabz card

### ISSUE THREAD

**Issue by IITvamp** [scorelab/Codelabz#275]
**Is your feature request related to a problem? Please describe.**

- current design of the Codelab card is a little outdated.
- current card has issues for the posts which are written for an organization as the avatar image of the user is placed over the avatar image of the organization.

**Screeenshots**
![image](https://user-images.githubusercontent.com/77586067/163999473-ba0671b5-e5f2-41f9-854b-6617ab76872a.png)

![image](https://user-images.githubusercontent.com/77586067/164000033-2454de54-78f9-47ad-9935-38047946b7a4.png)
Image of the card written for an organization (Score Lab)

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/77586067/164000330-356cc472-4cbf-4cbd-944a-4918ea3545be.png)
new image of the Codelab card

![image](https://user-images.githubusercontent.com/77586067/164000354-b9501209-b326-4cd6-9083-b8f741f2ecb8.png)
Image of the card written for the organization.
this card beautifully displays all the information about the user and the organization

**Comment by shahaab** [comment]
Hey @kushalShukla-web, I have actually redesigned and built the component. (Issue #291)

**Comment by kushalShukla-web** [comment]
ohkay np
