### ISSUE TITLE
alignment issue in the rightmenu of mainnavbar

### ISSUE THREAD

**Issue by IITvamp** [scorelab/Codelabz#279]
**Describe the bug**
Icon and Icon text is not  aligned horizontally on the rightmenu of mainnavbar

**To Reproduce**
1. Go to main homepage
2. Click on the avatar icon.
![image](https://user-images.githubusercontent.com/77586067/166097076-e7674e24-a11f-4342-af4b-ff33023a22d7.png)

`<CodeOutlinedIcon />` and "My Tutorials" are not perfectly aligned horizontally

**Expected behavior**
Icons and name string should be perfectly aligned.
![image](https://user-images.githubusercontent.com/77586067/166097123-e05f0fab-05a0-40d8-a54a-f94c503fc878.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device: Realme
 - OS: Android
 - Browser: chrome

**Comment by Ashwin-hp** [comment]
@IITvamp Anybody working on this issue? Please assign this to me.
