### ISSUE TITLE
bug in the profile page ui/ux

### ISSUE THREAD

**Issue by IITvamp** [scorelab/Codelabz#283]
**Describe the bug**
on small screens, the **options** button on the profile page moves to the mid of the profile page header instead of remaining in the right corner.

**To Reproduce**
1. Go to the profile page
2. right-click on the mouse and click on inspect button.
3. change the pixel of the screen to see the bug.

**Expected behavior**
options button should remain in the right-most corner in all the screen sizes for better visual.

**Screenshots**
in xs screens
![image](https://user-images.githubusercontent.com/77586067/167201358-41961f3d-1742-4ab2-87d7-48de7b945b25.png)

in small screens
![image](https://user-images.githubusercontent.com/77586067/167201432-27d18daa-08cd-4016-b03b-3b6d5d2c4035.png)

in large screens
![image](https://user-images.githubusercontent.com/77586067/167201485-f5c30ec9-5580-4045-b5e0-d68fd5a7c6ef.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome, brave

**Comment by kushalShukla-web** [comment]
hi @IITvamp 
can i work on this ??

**Comment by kushalShukla-web** [comment]
hey btw when im try to login in local website  of codelabz , i can't . so how can i fix this bug if i cant see the UI .
![Screenshot (140)](https://user-images.githubusercontent.com/85934954/178698987-1d2a41ca-0234-4eef-a423-a3e03d3adb29.png)
/
