### ISSUE TITLE
Including new Menu items for home page 

### ISSUE THREAD

**Issue by Maahi10001** [scorelab/Codelabz#285]
**Describe the solution you'd like**
including the menu item such as main menu, reading list, contact us, term of use and rearranging the left anf right menu bars 
 and we can add functionality to them.

**Current look**
![image](https://user-images.githubusercontent.com/80961448/167544179-b8bd4fe0-695f-43a9-92da-413cea16749a.png)
 **New Look**
![image](https://user-images.githubusercontent.com/80961448/167544222-597ae308-9429-4e23-acb7-245909896093.png)

**Comment by Amishakumari544** [comment]
@Niweera can I work on this if no one is working??

**Comment by Niweera** [comment]
> @Niweera can I work on this if no one is working??

can you communicate with others on https://gitter.im/scorelab/CodeLabz gitter channel?

**Comment by Amishakumari544** [comment]
Yeah sure, I am already there.

**Comment by Maahi10001** [comment]
> @Niweera can I work on this if no one is working??

@Amishakumari544  actually the menu items have changed and designed by @shahaab  and @Janvi-Thakkar are working on it.

**Comment by Amishakumari544** [comment]
> > @Niweera can I work on this if no one is working??
> 
> @Amishakumari544 actually the menu items have changed and designed by @shahaab and @Janvi-Thakkar are working on it.

Oki
