### ISSUE TITLE
Develop Organization Users component

### ISSUE THREAD

**Issue by Janvi-Thakkar** [scorelab/Codelabz#289]
As per Figma designs, create Organization Users' component for different users such as Admins, contributors, subscribers, etc.

![Screenshot (893)](https://user-images.githubusercontent.com/55620053/173424501-ec3dc86a-48e8-4c5e-8bcd-07195bc6f0b7.png)

Reference for the design: https://www.figma.com/file/65I2EqaTgwUnYHUeWLfvJr/components?node-id=0%3A1

**Comment by kushalShukla-web** [comment]
Hey I like to work on this issue
