### ISSUE TITLE
Change createMuiTheme to createTheme

### ISSUE THREAD

**Issue by Amishakumari544** [scorelab/Codelabz#317]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/49230384/175760220-f0ec6a15-9407-4f53-9194-8cdef187d812.png)
![image](https://user-images.githubusercontent.com/49230384/175760225-011f7bb4-c319-4bef-9ba5-cf3a24ed4b75.png)
![image](https://user-images.githubusercontent.com/49230384/175760287-32610eeb-76f7-4647-8f82-75a0abfc59cf.png)

We should rename it to follow the convention of mui.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/49230384/175760321-61569972-7452-444a-bd0d-7fe18c208f6e.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by DivyanshuSonwal** [comment]
Hi @Niweera Can I work on this issue?

**Comment by Sarfraz-droid** [comment]
This will be fixed with #303
