### ISSUE TITLE
Create firebase function for searching posts by keywords

### ISSUE THREAD

**Issue by Janvi-Thakkar** [scorelab/Codelabz#387]

**Comment by mridullpandey** [comment]
HI janvi i would like to work on this.
Please do assign this to me

**Comment by Janvi-Thakkar** [comment]
Hello @mridullpandey, Thank you for showing your interest. As of now, this issue is open for GSoC project work.

**Comment by sulogna2001** [comment]
Hey @mridullpandey  I would like to work on this issue, Please do assign this to me
