### ISSUE TITLE
Add Table of Contents in Readme.md

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#405]
Add Table of Contents in ```Readme.md```

# Example : 

### Table of contents
1. [Introduction](#introduction)
2. [Some paragraph](#paragraph1)
    1. [Sub paragraph](#subparagraph1)
3. [Another paragraph](#paragraph2)

## This is the introduction <a name="introduction"></a>
Some introduction text, formatted in heading 2 style

## Some paragraph <a name="paragraph1"></a>
The first paragraph text

### Sub paragraph <a name="subparagraph1"></a>
This is a sub paragraph, formatted in heading 3 style

## Another paragraph <a name="paragraph2"></a>
The second paragraph text

**Comment by nitinmewar** [comment]
can I work on it?

**Comment by kushalShukla-web** [comment]
Hey if no one working on this , may i ??

**Comment by Sarfraz-droid** [comment]
> Hey if no one working on this , may i ??

@nitinmewar is working on it

**Comment by nitinmewar** [comment]
@kushalShukla-web I am done with it. just having some problems while committing.

**Comment by nitinmewar** [comment]
@Sarfraz-droid I was really close to make a PR. I will solve this by tomorrow evening.

**Comment by Sarfraz-droid** [comment]
> @Sarfraz-droid I was really close to make a PR. I will solve this by tomorrow evening. 

Sure.👍

**Comment by Sarfraz-droid** [comment]
Closed with #418
