### ISSUE TITLE
Redesign My Codefeed Page.

### ISSUE THREAD

**Issue by Maahi10001** [scorelab/Codelabz#407]
**Expected behavior**
Recreate the design for my code feed as grid from nav bar is removed(ex:-use tiles)

**Comment by shahaab** [comment]
![my codefeed (1)](https://user-images.githubusercontent.com/41134301/187773921-88627775-742e-42f6-a446-888aa683f169.png)

**Comment by shahaab** [comment]
@charithccmc @Niweera please review it.
Check out the current version over here: https://dev.codelabz.io/dashboard/my_feed
