### ISSUE TITLE
Add .firebaserc in gitignore

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#416]
Since ```.firebaserc``` is a part of a firebase projects, So there are unwanted changes in every firebase project initialization. A solution would be to add this in ```.gitignore```

**Comment by kushalShukla-web** [comment]
Hey can i work on this

**Comment by kushalShukla-web** [comment]
by the way the file is already added in gitignore .

**Comment by Sarfraz-droid** [comment]
Oh, yea.. just clear the cache and add a pr, ```.firebaserc``` is still in git since it hasn't been removed yet

**Comment by kushalShukla-web** [comment]
I got it
