### ISSUE TITLE
Add More Users and Organisations in Firebase Emulator

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#417]
- [ ] Add More users and organisations in firebase emulator.
- [ ] Update the documentation accordingly

**Comment by kushalShukla-web** [comment]
Hey can I work on this

**Comment by legendarykamal** [comment]
Hi, I would like to work on this issue

**Comment by Sarfraz-droid** [comment]
@legendarykamal are you still working on it?

**Comment by shivareddy6** [comment]
Heyy can i work on this

**Comment by Maahi10001** [comment]
> Heyy can i work on this

i guess you can work on it @legendarykamal is not respondeding.

**Comment by Sarfraz-droid** [comment]
Closed with #482
