### ISSUE TITLE
Link Profile Page to Profile Settings

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#451]
**Is your feature request related to a problem? Please describe.**
There's no way to access the user settings right now.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/73013838/193530326-eb578d92-9876-4e5a-a51a-4911df5ece62.png)

- Add an MUI dropdown, that has **User Settings** tab.
- Link the **User Settings** tab to the profile settings route i.e.  _/user-dashboard/settings_

**Comment by Abhishek3223** [comment]
i would like to work on it . will  you please assign it to me ?
