### ISSUE TITLE
Implement Profile Photo URL for User

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#452]
**Is your feature request related to a problem? Please describe.**
Profile Photo URL hasn’t been implemented yet for user

**Describe the solution you'd like**
- Update the photoURL from FirebaseAuth
- Use the ```src\components\Profile\ChangeProfile\ChangeProfile.js``` and add it into user settings to  update the user profile

![image](https://user-images.githubusercontent.com/73013838/193536806-e5ea51cb-c7ad-4120-a5ee-504c47a315d5.png)

Task
- [ ] Use FirebaseAuth user.photoURL and replace it with dummy images
- [ ] Add Change Profile Component to user settings

**Comment by akankshat05** [comment]
@Sarfraz-droid can i work on this

**Comment by akankshat05** [comment]
> @akankshat05 any updates?

I'm working on it

**Comment by BabyElias** [comment]
@Sarfraz-droid Can I work on this issue?

**Comment by mohdhaider07** [comment]
@Sarfraz-droid  can I work on this

**Comment by BabyElias** [comment]
@mohdhaider07 I am working on this issue already. Can you please take up another issue? 
Thanks :)
