### ISSUE TITLE
Implement Switching Organizations in the “Switch Account Card”

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#454]
**Is your feature request related to a problem? Please describe.**
Implement Switch Accounts card to switch organizations 

![image](https://user-images.githubusercontent.com/73013838/193538768-dd3a4952-88c0-4fd8-abde-dd306d7c51ea.png)

**Comment by akankshat05** [comment]
@Sarfraz-droid Can i work on this?

**Comment by ABHISHEK-PANDEY2** [comment]
Hello @Sarfraz-droid,
I would like to work on the issue

**Comment by Sarfraz-droid** [comment]
Any Updates @ABHISHEK-PANDEY2

**Comment by ABHISHEK-PANDEY2** [comment]
@Sarfraz-droid I was working but was constantly facing issue with firebase emulators , not getting signed up so was not able to see the switch org page

**Comment by Sarfraz-droid** [comment]
Okay, you can communicate to the gitter channel for any help. unassigning since this issue needs some help

**Comment by Deeks900** [comment]
Could you please elaborate on this issue a little bit more:
In this dropdown, we should show all those organizations that this user has created. Is this the exact issue?

**Comment by Sarfraz-droid** [comment]
Yes

> Could you please elaborate on this issue a little bit more: In this dropdown, we should show all those organizations that this user has created. Is this the exact issue?

**Comment by Deeks900** [comment]
Could you please assign this issue to me

**Comment by sulogna2001** [comment]
hey @Sarfraz-droid  can I work on this issue?

**Comment by Deeks900** [comment]
I can fix this issue.
