### ISSUE TITLE
Differentiate “Settings” in Home Page to “User Settings” and “Organization Settings”

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#455]
**Is your feature request related to a problem? Please describe.**
- Remove settings from the Sidebar at Home page
- Add User Settings and Organization Settings Card instead

![image](https://user-images.githubusercontent.com/73013838/193542960-da39ef96-68ee-4143-ae71-f89724684d05.png)

**Comment by kushalShukla-web** [comment]
Wanted to work on

**Comment by Sarfraz-droid** [comment]
sure

**Comment by sameergupta4873** [comment]
i would to like work upon as well , could Assign please ??

**Comment by Sarfraz-droid** [comment]
@sameergupta4873 it has already been assigned to @kushalShukla-web

**Comment by kushalShukla-web** [comment]
Hey @sameergupta4873 I'm actually quite busy with my insem exam and after 10 only I will able to start contribution.

**Comment by kushalShukla-web** [comment]
bro here i have one doubt these changes are not present in my local host . i done git git pull upstream master to take all the changes in main branch but nothing happened

**Comment by Sarfraz-droid** [comment]
> bro here i have one doubt these changes are not present in my local host . i done  git pull upstream master to take all the changes in main branch to my local one  but nothing happened 

Please have a look at your local git branch.. these changes are present in the master branch

**Comment by shivareddy6** [comment]
Hey @Sarfraz-droid, its been inactive for so long, can I work on this?

**Comment by shivareddy6** [comment]
Should the changes be made just at home page or in user-dashboard too?
Changes at Home:
![68747470733a2f2f66696c65732e6769747465722e696d2f3633346437393434366461303337333938343964663536642f547748702f7468756d622f696d6167652e706e67](https://user-images.githubusercontent.com/74174769/199257325-81aa08b4-6550-4f37-abf0-5f3cdeb84124.png)

Changes at user-dashboard:
![68747470733a2f2f66696c65732e6769747465722e696d2f3633346437393434366461303337333938343964663536642f657552562f7468756d622f696d6167652e706e67](https://user-images.githubusercontent.com/74174769/199257451-c5d414bd-017d-4bb2-b75e-8d7e730275c8.png)

**Comment by shivareddy6** [comment]
@Sarfraz-droid, can you look into this?

**Comment by Sarfraz-droid** [comment]
Sure @shivareddy6 we can add that as a feature too

**Comment by iamsid0908** [comment]
hey, @Sarfraz-droid I am new in open source contribution can you please tell me how to start?

**Comment by Sarfraz-droid** [comment]
> hey, @Sarfraz-droid I am new in open source contribution can you please tell me how to start?

You can join our gitter channel at https://github.com/scorelab/Codelabz#community
