### ISSUE TITLE
Code Refactor for Sidebar Component

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#456]
**Issue**
Sidebar is a utility component. Avoid adding specific auth based checks on that component.
Add in where that component is used

[Component Uri](https://github.com/scorelab/Codelabz/blob/master/src/components/SideBar/sidelist.js)

**Comment by abdullahranginwala** [comment]
Hello! I'd love to work on this issue. Can you help me understand the issue a little better?

**Comment by Sarfraz-droid** [comment]
https://github.com/scorelab/Codelabz/blob/master/src/components/SideBar/sidelist.js

Here you have to remove the cases that are integrated with firebase.
- Sidebar is a utility component so specifics such as allowDashboard, logout, etc should be avoided.
- All you have to do is to remove these cases from the component


For example : 
```
                {item.link &&
// remove this part here
                  ((allowDashboard && item.name === "Profile") ||
                    item.name !== "Profile")
// till here
 && (
                    <MenuItem
                      key={item.link}
                      onClick={() => {
                        toggleSlider();
                        onStateChange(index);
                      }}
                    >
```

```
                {!item.link && item.onClick && 
// remove this part here
item.name !== "Logout" 
//
&& (
                  <MenuItem
                    key={item.name}
                    onClick={() => {
                      if (item.onClick) item.onClick(item);
                      onStateChange(item);
                    }}
                  >
```

Apart from that

at https://github.com/scorelab/Codelabz/blob/master/src/components/SideBar/index.js

```
// dynamically update the default menu according to user state using useMemo()
  const defaultMenu = [
    {
      name: "Home",
      img: Home,
      link: "/"
    },
    {
      name: "Notifications",
      img: Notification
    },
    {
      name: "Settings",
      img: Setting,
      link: "/user-dashboard/profile"
    },
    {
      name: "Organizations",
      img: Org,
      link: "/organization"
    },
    {
      name: "My Feed",
      img: MyFeed,
      link: "/dashboard/my_feed"
    },
    {
      name: "Profile",
      img: Profile,
      link: "/profile"
    },
    {
      name: "Bookmarks",
      img: Bookmark,
      link: "/bookmarks"
    },
    {
      name: "Tutorials",
      img: Tutorials,
      link: "/tutorials"
    },
    {
      name: "Logout",
      img: Logout,
      onClick: `${signOut}`
    }
  ];
```

**Comment by Sarfraz-droid** [comment]
> https://github.com/scorelab/Codelabz/blob/master/src/components/SideBar/sidelist.js
> 
> Here you have to remove the cases that are integrated with firebase.
> 
> * Sidebar is a utility component so specifics such as allowDashboard, logout, etc should be avoided.
> * All you have to do is to remove these cases from the component
> 
> For example :
> 
> ```
>                 {item.link &&
> // remove this part here
>                   ((allowDashboard && item.name === "Profile") ||
>                     item.name !== "Profile")
> // till here
>  && (
>                     <MenuItem
>                       key={item.link}
>                       onClick={() => {
>                         toggleSlider();
>                         onStateChange(index);
>                       }}
>                     >
> ```
> 
> ```
>                 {!item.link && item.onClick && 
> // remove this part here
> item.name !== "Logout" 
> //
> && (
>                   <MenuItem
>                     key={item.name}
>                     onClick={() => {
>                       if (item.onClick) item.onClick(item);
>                       onStateChange(item);
>                     }}
>                   >
> ```
> 
> Apart from that
> 
> at https://github.com/scorelab/Codelabz/blob/master/src/components/SideBar/index.js
> 
> ```
> // dynamically update the default menu according to user state using useMemo()
>   const defaultMenu = [
>     {
>       name: "Home",
>       img: Home,
>       link: "/"
>     },
>     {
>       name: "Notifications",
>       img: Notification
>     },
>     {
>       name: "Settings",
>       img: Setting,
>       link: "/user-dashboard/profile"
>     },
>     {
>       name: "Organizations",
>       img: Org,
>       link: "/organization"
>     },
>     {
>       name: "My Feed",
>       img: MyFeed,
>       link: "/dashboard/my_feed"
>     },
>     {
>       name: "Profile",
>       img: Profile,
>       link: "/profile"
>     },
>     {
>       name: "Bookmarks",
>       img: Bookmark,
>       link: "/bookmarks"
>     },
>     {
>       name: "Tutorials",
>       img: Tutorials,
>       link: "/tutorials"
>     },
>     {
>       name: "Logout",
>       img: Logout,
>       onClick: `${signOut}`
>     }
>   ];
> ```

@abdullahranginwala

**Comment by kushalShukla-web** [comment]
Wanted to work on

**Comment by abdullahranginwala** [comment]
Thank you! I have created a PR for this. Eager for your feedback!
