### ISSUE TITLE
Fix Organization Settings responsiveness

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#460]
**Describe the bug**
Organization settings not yet responsive.

**Solution**
- Shift the Sidelist component in organization settings to Custom Menu(List). (Show as flex in mobile view)
- remove unnecessary grid spaces in mobile view

**Screenshots**
![CdKcPIkrHs](https://user-images.githubusercontent.com/73013838/193666309-58c922e5-941d-4f9f-afb5-4955e48496c1.gif)

**Comment by akankshat05** [comment]
@Sarfraz-droid I would like to fix this

**Comment by vaibhav-xt** [comment]
I can fix this problem

**Comment by Sarfraz-droid** [comment]
sure

**Comment by Sarfraz-droid** [comment]
@vaibhav-xt are you still working on it?

**Comment by vaibhav-xt** [comment]
not brother @Sarfraz-droid

**Comment by PrathmeshAdsod** [comment]
Hey @Sarfraz-droid 
Is this issue still present their ? I can solve this if needed.

**Comment by PrathmeshAdsod** [comment]
Hey @Sarfraz-droid , please see issue #489 .I am getting lots of errors in installing node_modules in this project. I have tried lot of solutions but not solved yet.

**Comment by ABHISHEK-PANDEY2** [comment]
Hey @Sarfraz-droid Moving the side list means moving the sideNav(the one containing genral user password etc as link) ?
I am working on it 👍🏻

**Comment by ABHISHEK-PANDEY2** [comment]
I have tried solving the issue , here is a demo on it .. Should i change something ? @Sarfraz-droid 

https://user-images.githubusercontent.com/95560057/203297133-af6876bb-a68d-4ca1-a61a-00b8e307c014.mp4
