### ISSUE TITLE
Add Community Links to "Readme.md"

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#462]
Add a new title as "Community" at third index

The content should be as : 

# Community

Join and communicate with other members on our community. We communicate on gitter

[![Gitter](https://badges.gitter.im/scorelab/CodeLabz.svg)](https://gitter.im/scorelab/CodeLabz?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

## Code

```
Join and communicate with other members on our community. We communicate on gitter

[![Gitter](https://badges.gitter.im/scorelab/CodeLabz.svg)](https://gitter.im/scorelab/CodeLabz?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

```

**Update the Table of Contents accordingly**

**Comment by TilteD24** [comment]
Please assign this to me
