### ISSUE TITLE
Bad impression of CodeLabz website when user is not registered or logged in or No Upcoming Events are there.

### ISSUE THREAD

**Issue by PrathmeshAdsod** [scorelab/Codelabz#488]
**Describe the bug**
When user is not registered or logged in on website https://dev.codelabz.io/ in the Upcoming Events section dummy text is appearing  
"lorem lorem text lorem text text...." but this should not happen. This is totally bad user experience. If their are no Upcoming Events so their must be written as "No upcoming Events listed " like stuff. Same goes on Popular Events section also. Remove that dummy text or write something relevant there. 

**To Reproduce**
1. Go to https://dev.codelabz.io/
You will see the dummy text which is bad to see for user

**Expected behavior**
Remove that dummy text from Upcoming Events and Popular Events section. If events are their to mention then it should be seen to user even if he/she is not logged in or registered. Else if events are not their then it should just show No Upcoming Events yet and stuff like this and on popular Events section it should show simple text like No Popular Events or something like that.

**Screenshots**
![Screenshot (181)](https://user-images.githubusercontent.com/91672445/200257424-40a5b861-b8f5-4ca3-8e93-fa57270c1e9f.png)

**In this issue no need to see which device we are using.**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Sarfraz-droid** [comment]
Currently the UI has went through an overhaul in the development, but hasn't been deployed yet. Check out the wiki or more info!
