### ISSUE TITLE
Errors while running command npm install in this project . Not able to install node_modules folder with npm install 

### ISSUE THREAD

**Issue by PrathmeshAdsod** [scorelab/Codelabz#489]
**Describe the bug**
Errors coming while running command npm install in this project . 
1st]error
error resolve unable to resolve dependency tree npm install
2nd] error
 npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout

**_I tried lot of solutions from online but not worked for me. But other React-apps was successful._**
 - npm version 8.5.0
 - node version v16.14.2

**To Reproduce**
1. Fork repo if not done yet
2. Clone it if not done yet
3. run npm install in Codelabz folder

![Screenshot (184)](https://user-images.githubusercontent.com/91672445/200739948-e11af579-163e-4059-97c9-374533ddcf26.png)
![Screenshot (182)](https://user-images.githubusercontent.com/91672445/200740338-48406c26-e8de-4059-a3c3-0286514cbab0.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - npm version 8.5.0
 - node version v16.14.2

**Comment by Deeks900** [comment]
For removing this error: resolve unable to resolve dependency tree npm install
Try this command: npm install --save --legacy-peer-deps

Secondly, try downgrading your node version to 14

**Comment by PrathmeshAdsod** [comment]
I have run this command npm install --save --legacy-peer-deps ,  but not worked for me

**Comment by Deeks900** [comment]
Okay then try this command again with node version 14

**Comment by Sarfraz-droid** [comment]
For setup related issues,
Communicate on our gitter channel
