### ISSUE TITLE
Making organization manager specific in the URI

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#490]
**Is your feature request related to a problem? Please describe.**
To implement the switch accounts in #454. We have to first shift and make the organization manager distinct. Shifting organization settings route from `/organiation` -> `/org/settings/:orgid`

**Solution**
Keeping organization settings here as distinct `/org/settings/orgid` rather than `/organization` and making the necessary changes
![image](https://user-images.githubusercontent.com/73013838/201537579-5428d040-09aa-41e6-a787-357a5826dcd3.png)

Organization Profile Page -> `org/:orgid`
Organization Settings Page -> `org/settings/:orgid`

**Comment by Deeks900** [comment]
Could you please assign this issue
