### ISSUE TITLE
Bug : In User settings the menu disappears in small screens. 

### ISSUE THREAD

**Issue by ABHISHEK-PANDEY2** [scorelab/Codelabz#499]
**Describe the bug**
The user Setting menu disappears below 960px .
The social media section of settings page is not consistent with the design.
Profile Typography is not similar to other fonts in the website

**To Reproduce**
1. Go to user settings
2. reduce screen width bellow 900px 
3. The menu disappears 

**Expected behavior**
The menu bar should change into ha hamburger menu

**Screenshots**

The menubar disappears : 
![Screenshot_20221126_181214](https://user-images.githubusercontent.com/95560057/204090026-56707fb1-8436-4f94-af70-c85a0e181365.png)

![Screenshot_20221126_181250](https://user-images.githubusercontent.com/95560057/204090042-9e7ee8e4-fe41-43ce-aa45-70b8cc9e14ff.png)

The social media items are inconsistent , and contain a lot of spacing between them 

![Screenshot_20221126_181406](https://user-images.githubusercontent.com/95560057/204090084-be1eb598-a633-46cc-b230-eb93ef9c4b05.png)

![Screenshot_20221126_181438](https://user-images.githubusercontent.com/95560057/204090094-1abf8564-1af2-4363-8bd4-2f671a9e3b00.png)

The font for the profile card is different from others in the website:

![Screenshot_20221126_181519](https://user-images.githubusercontent.com/95560057/204090099-39199f32-7826-44c6-b357-9a2316282220.png)

**Desktop (please complete the following information):**
 - OS: windows
- Browser :Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ABHISHEK-PANDEY2** [comment]
These are some of the bugs i found , If it's all ok i would like to work on them @Sarfraz-droid

**Comment by ABHISHEK-PANDEY2** [comment]
for the connected links we could provide a small tick mark .

**Comment by Sarfraz-droid** [comment]
Sure! Go ahead

- [ ] The menubar disappearing from User Settings
- [ ] Inconsistent Social Media Icons
- [ ] Inconsisten font on User Profile

> These are some of the bugs i found , If it's all ok i would like to work on them @Sarfraz-droid
