### ISSUE TITLE
Github Actions for removing inactive issues and pull request

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#506]
refer to the link here : https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

**Comment by Amishakumari544** [comment]
Hi @Sarfraz-droid I want to work on this issue

**Comment by Sarfraz-droid** [comment]
Hi @Amishakumari544 Since it is a github action related issue. We need that urgently so that we can update the current issues and Pull Requests, I'll be creating a new action for the same.
