### ISSUE TITLE
No highlighting in the side bar for the current page

### ISSUE THREAD

**Issue by partik03** [scorelab/Codelabz#511]
**Describe the bug**
Not actually a bug but the sidebar does not highlights the current page the user is at,hence it does not give a really smooth User Experience.

**To Reproduce**
1. Go to '/'
2. Click on 'Any menu item of the side bar'
3. Check the issue

**Expected behavior**
I expected the current page to get highlighted in the side bar.

**Screenshots**
Current behavior 

[Screencast from 12-05-2022 05:02:05 PM.webm](https://user-images.githubusercontent.com/99184676/205627319-e3cb78ad-050b-43d2-86bc-9c22e50f3539.webm)

**Desktop (please complete the following information):**
 - OS: [Linux Pop os]
 - Browser [Firefox]
 - Version [22.04]

**Smartphone (please complete the following information):**
 - Device: [Oneplus Nord 2]
 - OS: [Oxygen Os]
 - Browser [Brave]

**Additional context**

**Comment by Maahi10001** [comment]
@partik03  can you record this for a few seconds more by testing in various screens like mobile and tab format

**Comment by partik03** [comment]
@Maahi10001 I updated the video
