### ISSUE TITLE
Login Signup buttons disappears from home screen for screen width 1280px - 970px

### ISSUE THREAD

**Issue by ABHISHEK-PANDEY2** [scorelab/Codelabz#516]
**Describe the bug**
Once you logout of the site , the signup and login button disappear  for width 1280px to 970px

**To Reproduce**
1. Click on logout
2. reduce screen width to < 1280px

**Expected behavior**
The login signup button should be visible.

**Video**

https://user-images.githubusercontent.com/95560057/205716239-ad7447fd-1095-4f6e-bccb-77ce4f89404e.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ABHISHEK-PANDEY2** [comment]
@Sarfraz-droid please review the issue , i would like to work on this.

**Comment by maddy020** [comment]
Hey @Sarfraz-droid Can I work on this issue if no one is there?

**Comment by Sarfraz-droid** [comment]
I think @ABHISHEK-PANDEY2 is working on it right now.
