### ISSUE TITLE
Making side navbar responsive

### ISSUE THREAD

**Issue by BabyElias** [scorelab/Codelabz#517]
The side navbar disappears for 950*750px.
We can make a side navbar like :
![image](https://user-images.githubusercontent.com/95405559/205806776-b462c37c-5cd8-488d-9f30-b384f99ae0a6.png)
![Screenshot (104)](https://user-images.githubusercontent.com/95405559/205807391-b03289b2-29b6-4d2e-b9ff-1964b48bc13c.png)
This will also reduce the space occupied by navbar, and make space for other components as well.

**Comment by Sarfraz-droid** [comment]
Currently the navbar is supported by a hamburger menu, so any changes in the the `Sidelist` component like this might add more complexities to other parts of the app. 
Thanks for the suggestion!

I'm closing this issue.
