### ISSUE TITLE
Updating the documentation

### ISSUE THREAD

**Issue by hs05june** [scorelab/Codelabz#518]
There were many problems which I faced while setting up the project locally. I expect new contributors may also face the same. Wanted to add them in the documentation. These include
1) version of node needed
2) way of adding firebase keys and urls
3) port taken problem for emulator

**Comment by hs05june** [comment]
Please review this issue. Assign it to me. Would work on it.

**Comment by Sarfraz-droid** [comment]
Some of the issues have been already solved with #510

**Comment by Sarfraz-droid** [comment]
Completed by #510
