### ISSUE TITLE
Lack of consistency of password pages across website.

### ISSUE THREAD

**Issue by ABHISHEK-PANDEY2** [scorelab/Codelabz#520]
**Describe the bug**
The password page in user setting has different layout than in organizations.

**To Reproduce**
1. Go to '[user's setting password](http://localhost:3000/user-dashboard/password)'
2. Check the layout in different widths
3. Now go to '[organization password](http://localhost:3000/org/settings/codelabzorg)'
4. Compare the layout of smaller widths

**Expected behavior**
Both pages should display similar layout , this would increases consistency 

**Video**

https://user-images.githubusercontent.com/95560057/205869210-240fb2fb-d5d3-4c7b-8b00-2e415f208d43.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sarfraz-droid** [comment]
This might've occurred due to the recent changes, however. We can come up with common components to remove duplicate code in the application. 
I'm a bit busy right now with work and exams. 
So we can come up with common folder structure for easy access

**Comment by ABHISHEK-PANDEY2** [comment]
I have understood the codebase , i can work on creating a common component for password pages , later you could review when you get free ?
And there are a lot of bugs encountered due to recent commits , the sideNav when clicked highlights the item , due to which it overlaps the main content in smaller screen width which makes text content unreadable . i can work on it too?
 @Sarfraz-droid

**Comment by Royal-Akash** [comment]
Hey @Sarfraz-droid Can I work on this issue if no one is working on that.
