### ISSUE TITLE
Improve UI of user profile page

### ISSUE THREAD

**Issue by BabyElias** [scorelab/Codelabz#525]
![image](https://user-images.githubusercontent.com/95405559/206119827-ef266aa7-1d1f-4687-b1d2-0f971b1a02f5.png)
Improve the alignment and layout of user cards.

**Comment by yuvrajrathva** [comment]
Hello @BabyElias, I want to work on this.

**Comment by BabyElias** [comment]
Hey @yuvrajrathva , I am a contributor myself. So waiting for this issue to be assigned to me.

**Comment by BabyElias** [comment]
Yup, sure.

**Comment by BabyElias** [comment]
@Sarfraz-droid
 https://www.figma.com/file/lvgdVcTR0PHJKQkOYFViUz/User-Profile-Page?node-id=0%3A1&t=OwHBxhoCYWOwPUI6-1

The improved UI.

**Comment by Sarfraz-droid** [comment]
@BabyElias We don't need as such UI overhaul for now.. This pretty much changes the whole layout of the profile page.
We have to make it consistent with the Organization page too
