### ISSUE TITLE
Unresponsive login screen

### ISSUE THREAD

**Issue by VenomFate-619** [scorelab/Codelabz#529]
**Describe the bug**
Go to the login page on the mobile layout, one can see that the page can be scrolled horizontally towards the right

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to loginpage
2. Go to mobile layout using devtool
3. Scroll to right

**Screenshots**
![image](https://user-images.githubusercontent.com/67755128/206831483-16ec79c5-0a57-44ca-9d1d-f9a2f294cc25.png)

![image](https://user-images.githubusercontent.com/67755128/206831567-dd169982-0f8c-48dd-8f34-835bd869717c.png)

**Desktop (please complete the following information):**
 - OS: PopOS
 - Browser brave
 - Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)

**Comment by VenomFate-619** [comment]
I would like to fix this

**Comment by Ashwin-hp** [comment]
I would like to work on this. Please assign it to me.

**Comment by VenomFate-619** [comment]
@Sarfraz-droid I would like to fix this
