### ISSUE TITLE
Profile Settings Page needs few changes

### ISSUE THREAD

**Issue by Deeks900** [scorelab/Codelabz#530]
**Describe the bug**
On this route(http://localhost:3000/user-dashboard/profile) these issues are present:

The sidebar does not respond on this screen width (939 to 959).
Link:https://drive.google.com/file/d/14-VX8BWv8-HaF3jMWP1EPjLUU82I2xCd/view?usp=share_link

On the screen width 360 this UI needs improvement i.e all the boxes of equal width will look good.
Link:https://drive.google.com/file/d/1FeX6nqs4Gyjk3t_4XzfFmoEcIl0pSnMI/view?usp=share_link

On this screen width 1002 this sidebar is overlaping the Profile Heading
![image](https://user-images.githubusercontent.com/66011090/206850781-312c1ba6-20df-4542-b6f8-efebe23b90b0.png)

**To Reproduce**
1. Go to http://localhost:3000/user-dashboard/organizations
2. Try minimizing the screen to the widths mentioned above in issues.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Deeks900** [comment]
I want to work on this issue. Please assign.

**Comment by Sarfraz-droid** [comment]
- [ ] The sidebar does not respond on this screen width (939 to 959).
- [ ] On the screen width 360 this UI needs improvement i.e all the boxes of equal width will look good.
- [ ] On this screen width 1002 this sidebar is overlaping the Profile Heading

**Comment by Phani4658** [comment]
Can i work on this ?

**Comment by Deeks900** [comment]
@Phani4658 I am already working on this
