### ISSUE TITLE
Improvement in SearchBar

### ISSUE THREAD

**Issue by hs05june** [scorelab/Codelabz#534]
Even little long queries in search bar will cause this.
[Video](https://user-images.githubusercontent.com/103871275/207284701-52d92926-ddfd-418d-b8d6-fd03540dfbfe.webm)
Which is not a good user experience.

**Comment by yuvrajrathva** [comment]
Hello @hs05june can I work on this issue.

**Comment by hs05june** [comment]
I am a contributor myself. You may look for other issues and add them over here.
