### ISSUE TITLE
mouse hover div effect

### ISSUE THREAD

**Issue by snkt-08** [scorelab/Codelabz#536]
I have an idea about our upcoming events and discussion boxes,
I just give effect on it of Mouse Hover div effect 

After effect it looking attractive.

I request you please give me permission to do that.

![mouse hover div effect](https://user-images.githubusercontent.com/119801129/207395826-5c3f3cfa-c535-454b-9d10-62dab994f777.png)

**Comment by shahaab** [comment]
Hey @snkt-08, The UI has been updated, please install the Codelabz repository locally and let us know if you find any issues.
