### ISSUE TITLE
Menu Button not working in Mobile Screen

### ISSUE THREAD

**Issue by akashadr** [scorelab/Codelabz#537]
Bug_Report - [includes in repository]

Would you like to work on the issue?

 Yes ✅
 No
 Other:

Menu Button not working in Mobile Screen.

https://user-images.githubusercontent.com/75382310/208032390-c5029940-b1ae-4819-aefc-60d47fb5622f.mp4

**Comment by shahaab** [comment]
The menu button doesn't work regardless of the screen size. Do fix it ASAP, I have assigned it to you @akashadr. All the best 👍

**Comment by Sarfraz-droid** [comment]
@shahaab This will be issue for https://github.com/scorelab/scorelab.github.io. Still I don't think we have its codebase open source. We might have to connect to org admins to work on this bug.

But the codebase doesn't belong to Codelabz.
Closing this issue here
