### ISSUE TITLE
Some buttons in the navbar are not available/appearing for some screen sizes.

### ISSUE THREAD

**Issue by Pushpendra766** [scorelab/Codelabz#538]
**Describe the bug**
1. Login and Signup buttons are not appearing when the screen size is <1280 and >960, i.e. in the range (960, 1280).
2. Side bar buttons not available for screen size in the range 750<screen-size<960

**To Reproduce**
1. Run the CodeLabz app in your localhost.
2. Go to console and inspect.
3. Go to responsive section and change the screen size anywhere between 1280 and 960.
4. See that Login and Signup buttons are not appearing.
5. Change the screen size anywhere between 960 and 750.
6. See that sidebar buttons are not appearing.

**Expected behavior**
Login, Signup and Sidebar buttons should be available for all screen size so that user can login/signup and access 
to there account.

**Screenshots**
![image](https://user-images.githubusercontent.com/56391001/208132147-b262a11a-d3bc-46d0-94dd-be6b201084cf.png)
![image](https://user-images.githubusercontent.com/56391001/208142220-b9f73965-8adc-46bc-a71f-64eeddfc64ca.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Brave]
 - Version [v1.46.144]

**Comment by Pushpendra766** [comment]
I would like to solve this issue please assign it to me.

**Comment by ABHISHEK-PANDEY2** [comment]
@Pushpendra766 @Sarfraz-droid i have raised this issue earlier #516  and worked on it . but it was just a single line change i waited for solving other bug and pushing the commit together with it

**Comment by Pushpendra766** [comment]
@ABHISHEK-PANDEY2 Okay, I am working on the second issue.
