### ISSUE TITLE
Improvement in UI of Homepage

### ISSUE THREAD

**Issue by Pushpendra766** [scorelab/Codelabz#540]
In the current UI of homepage, the width for main content in screen size range (960, 1280) is very less. 
![image](https://user-images.githubusercontent.com/56391001/208477216-ced4c518-88ba-4b58-aa61-b00d3822d7f7.png)
It can be improved by using only icons at the place of icons+text for sidebar.
![image](https://user-images.githubusercontent.com/56391001/208477517-b13a4b32-cd4b-4870-a3c8-83dca240761a.png)
We can also decrease the width of right sidebar, for even more space for the main content.
![image](https://user-images.githubusercontent.com/56391001/208494647-7c9d8bd2-bede-46b1-a5a9-08e08ff40206.png)

**Comment by Pushpendra766** [comment]
I would like to work on this issue, please assign it to me.

**Comment by shahaab** [comment]
Thanks for mentioning the issue, I have assigned it to you @Pushpendra766
