### ISSUE TITLE
Some UI Improvements

### ISSUE THREAD

**Issue by hs05june** [scorelab/Codelabz#547]
Currently
1) Navigation button of the side bar isn't working
https://user-images.githubusercontent.com/103871275/209440000-8cc0898c-3350-4dfe-a1b5-aa18e40ade7b.mp4

2) There are limited ways to navigate from Explore Codelabz page,  There should be a sidebar on this page also
https://user-images.githubusercontent.com/103871275/209440123-ee1d4f1f-9293-44f1-885e-f6217df75880.mp4

**Comment by Sarfraz-droid** [comment]
Hi, the explore codelabz page will be updated with a new UI. So don't work on that for now.

The notification button hasn't been implemented yet, so it doesn't have any changes on-click
