### ISSUE TITLE
Improved hover and active effects for the sidebar

### ISSUE THREAD

**Issue by huzaifmalik786** [scorelab/Codelabz#548]
**Describe the solution you'd like**
Improved hover and active effects for the sidebar in both cases when we are displaying either text in the sidebar or we are displaying only icons.

**Additional context**
The hover and active effects can be improved by making them more attractive. The border of the menu items can be given some border radius or the active state can be given some colors.

![Screenshot (5)](https://user-images.githubusercontent.com/100015095/209444992-506644b2-c24a-4f22-a5e5-ad867691559f.png)
![Screenshot (6)](https://user-images.githubusercontent.com/100015095/209444995-ef4b6603-18fd-4ead-a364-db2c0b4356eb.png)
![Screenshot (7)](https://user-images.githubusercontent.com/100015095/209445184-942823b5-be46-4647-b082-cf586e9f2074.png)

**Comment by huzaifmalik786** [comment]
@Sarfraz-droid please assign this issue to me so that I can create a pull request for it.

**Comment by shahaab** [comment]
@huzaifmalik786  Choose a different color scheme, this doesn't look good. 
Also, the padding is excessive on the right side of the icon. ![image](https://user-images.githubusercontent.com/41134301/209447158-a97045f0-0e30-48e4-9763-847299f12ee8.png)

**Comment by Sarfraz-droid** [comment]
@shahaab the collapsed sidebar will be removed by #546

**Comment by huzaifmalik786** [comment]
@shahaab I have added the styles for the icons seperately so the excessive padding will be removed when we will disable the text appearance. For the color, i have now changed it to a little more light blue to match it with the color combination of the home page.

**Comment by huzaifmalik786** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/100015095/209450090-30f789df-143c-448d-9e8c-8c4d048756a5.png)

@shahaab have a look.

**Comment by shahaab** [comment]
> @shahaab the collapsed sidebar will be removed by #546

Okay

**Comment by shahaab** [comment]
> ![Screenshot (13)](https://user-images.githubusercontent.com/100015095/209450090-30f789df-143c-448d-9e8c-8c4d048756a5.png)
> 
> @shahaab have a look.

looks better, @Sarfraz-droid @charithccmc @Niweera what do you guys think?
