### ISSUE TITLE
New Tutorial Modal Bug

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Codelabz#554]
**Describe the bug**
In the New Tutorial Modal, "User Name Here" is present instead of the display name of user's name.

![image](https://user-images.githubusercontent.com/91831606/209543351-3ad19188-d77e-4c25-964f-c3ddd35d9026.png)

**To Reproduce**
1. Go to http://localhost:3000/tutorials
2. Click on "ADD NEW CODELABZ" button

**Expected behavior**
![image](https://user-images.githubusercontent.com/91831606/209544609-7369bdbf-2c81-45be-9e86-fc20829dd123.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

**Comment by mohdhaider07** [comment]
Can I work on this issue

**Comment by YaSh8202** [comment]
Sorry @mohdhaider07, but I am currently working on it.
