### ISSUE TITLE
Duplicate keys in Styles

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#557]
- [ ] Duplicate key "border radius" at Codelabz/src/components/ui-helpers/Inputs/SecondaryInput.js
- [ ] Duplicate key "border radius" at Codelabz/src/components/ui-helpers/Inputs/PrimaryInput.js
- [ ] Duplicate key "width" at Codelabz/src/components/ProfileBanner/profile/ProfileCardOne/styles.js

**Comment by YaSh8202** [comment]
I would like to request to be assigned to this issue.

**Comment by Ashwin-hp** [comment]
I would like to work on this issue. Please assign it to me.
