### ISSUE TITLE
The navbar of auth page is not up to the mark.

### ISSUE THREAD

**Issue by partik03** [scorelab/Codelabz#563]
**Describe the bug**
The navbar of the auth page has search bar which is unnecessary and also it is not responsive properly.

**To Reproduce**
1. Go to '/login'
2. Check Navbar
3. See error

**Expected behavior**

https://user-images.githubusercontent.com/99184676/209681782-0e56d6b8-08ec-4489-90fb-d673ad324c1c.mp4

**Screenshots**

https://user-images.githubusercontent.com/99184676/209681802-26c5fe15-44b0-4fcc-a8a7-05f29c68fa98.mp4

**Comment by mohdhaider07** [comment]
@partik03 I have already fixed this issue. And it is merged  can you please pull main branch again
