### ISSUE TITLE
Button text color white  should be better for UI

### ISSUE THREAD

**Issue by mohdhaider07** [scorelab/Codelabz#564]
**Describe the bug**
buttons text color are not consistent

Some buttons have text color white and some have black
**Expected behavior**
Button text color should be white

**Screenshots**
![Screenshot 2022-12-29 012202](https://user-images.githubusercontent.com/86488954/209865649-f23ac195-e05b-491b-baf8-606266234431.png)
![Screenshot 2022-12-29 012106](https://user-images.githubusercontent.com/86488954/209865654-9ec39dba-8c18-4b36-825a-998b16fa18b1.png)
![Screenshot 2022-12-29 011929](https://user-images.githubusercontent.com/86488954/209865661-3524c53e-6701-41c4-b20b-bb959b614c9c.png)
![Screenshot 2022-12-29 012000](https://user-images.githubusercontent.com/86488954/209865668-10bc2494-cdfe-4e7c-8483-fc79bbf6a4c8.png)

@Sarfraz-droid  can you please assign this to me 
I want to make button text color consistent

**Comment by Ashwin-hp** [comment]
@Sarfraz-droid I would like to work on this ,please assign it to me

**Comment by mohdhaider07** [comment]
@Sarfraz-droid  can you please Review my PR 
#576
