### ISSUE TITLE
Improved UI of signup page

### ISSUE THREAD

**Issue by 07suryansh** [scorelab/Codelabz#565]
**Describe the solution you'd like**
The UI of the signup page can be improved

<img width="1440" alt="Screenshot 2022-12-29 at 12 15 56 PM" src="https://user-images.githubusercontent.com/77867124/209914554-3d1030e2-c808-4d71-b517-fbb7b958d09c.png">

**Describe alternatives you've considered**
Picture of my design of improved UI
<img width="1440" alt="Screenshot 2022-12-29 at 11 43 50 AM" src="https://user-images.githubusercontent.com/77867124/209914660-fc2935d8-aa51-415c-b63c-22a57677a474.png">

@Sarfraz-droid can you please assign this to me.

**Comment by vanshdeepsingh-coder** [comment]
please assign it to me

**Comment by Maahi10001** [comment]
@07suryansh follow the same for both login and sign up pages

**Comment by 07suryansh** [comment]
> @07suryansh follow the same for both login and sign up pages

ok
