### ISSUE TITLE
Not Receiving Verification email after trying to sign in.

### ISSUE THREAD

**Issue by KshitizSareen** [scorelab/Codelabz#566]
**Describe the bug**
I was working on https://dev.codelabz.io/. I signed up, and then I tried to sign in. Once I tried to sign in, I received this prompt.

<img width="697" alt="Screenshot 2022-12-28 at 11 26 56 PM" src="https://user-images.githubusercontent.com/23134343/209917943-3c24fa9e-d79b-491b-88cb-502ea6affdea.png">

I did not receive any verification email. I clicked the resend verification email option multiple times but did not get any email. After clicking a few times, I received this error.

<img width="1439" alt="Screenshot 2022-12-28 at 11 28 54 PM" src="https://user-images.githubusercontent.com/23134343/209918094-4baeff48-6636-4b91-acff-f00f2ca6c7a6.png"> 

I cannot log in because I have not received a verification email.

**To Reproduce**
Create account.
Login using that account.
You will get a verification email option, but you won't be able to receive one.
Click the resend verification email option (HERE) many times, and then you will get the 400 error.

**Expected behavior**
I should receive a verification email, and once I verify my email, I should be able to sign in.

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [0.1.0]

**Comment by KshitizSareen** [comment]
I undestood why its not working! In the cloud function we are not able to receive a verification link. In the cloud function for sendemailverification, we are generating a link, but not sending one. We might have to use nodemailer to send an email. I think there is another 3rd party service that helps in generating emails. We could also look into that.

Please let me know what you think.

**Comment by Sarfraz-droid** [comment]
@KshitizSareen We will be working on a dedicated node server but it is not planned for now.
