### ISSUE TITLE
PNG is visible on small screen

### ISSUE THREAD

**Issue by mohdhaider07** [scorelab/Codelabz#578]
**Describe the bug**
PNG image Has to be Hidden on small screen

**To Reproduce**
We can show image on right side on medium, large screen but on small screen we should hide it

**Screenshots**
https://files.gitter.im/5eb21f15d73408ce4fe2cb37/nDJU/image.png
https://files.gitter.im/5eb21f15d73408ce4fe2cb37/d2SH/image.png

**Additional context**
@Maahi10001 can please assign this to me

**Comment by Smriti925** [comment]
Sir, can you please assign this issue to me?
