### ISSUE TITLE
Removal of extra Hamburger Icon

### ISSUE THREAD

**Issue by ShwetKhatri2001** [scorelab/Codelabz#582]
**Describe the bug**
On user settings page there is an extra Hamburger Icon on left side which works similar to main hamburger Icon present on top right.
It may confuse the user on the first look.

**To Reproduce**
1. Go to '/user-dashboard/user-settings'
2. You will see two hamburger icons for the mobile screen.

**Expected behavior**
the unnecessary icon on left can be removed because its taking up unnecessary space without any special task and also creating confusion with the main hamburger icon.

**Demo Video**

[Hamburger Icon removal.webm](https://user-images.githubusercontent.com/56475750/210155845-1901f659-5c91-4d6d-b461-ba2cfed04c98.webm)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by ShwetKhatri2001** [comment]
@Sarfraz-droid I'd like to work on this issue if it needs to be solved.

**Comment by Deeks900** [comment]
@ShwetKhatri2001 That hamburger Icon is not extra the left one will open the options of the user-settings page in the sidebar, whereas the hamburger icon on the top-right corner will open the sidebar having options that will help also in navigating to various pages of the application.

**Comment by ShwetKhatri2001** [comment]
Thanks for the clarification @Deeks900 . But there are not many UI indicators showing that difference.
I have a suggestion to change the left icon and open the sidebar from left to show options of the user-settings page.

A possible icon for replacement can be this,
![image](https://user-images.githubusercontent.com/56475750/210168418-4833648c-a902-4e7f-8127-413adf6ba670.png)
