### ISSUE TITLE
Hide carousel icons for zero organizations

### ISSUE THREAD

**Issue by ShwetKhatri2001** [scorelab/Codelabz#583]
**Describe the bug**
On `My Feed` Page, when we have no launched organizations, still left and right carousel icons are present unnecessarily.

**To Reproduce**
1. Go to `/dashboard/my_feed`
2. Check if you see left and right carousel icons if you have zero organizations

**Expected behavior**
A validation needs to be added to hide these left and right carousel icons when there are no launched organizations.

**Screenshots**

On Desktop

![image](https://user-images.githubusercontent.com/56475750/210156282-8cc01cd2-2847-497d-9022-6979406592c2.png)

On Mobile

![image](https://user-images.githubusercontent.com/56475750/210156297-1636d26c-9749-4d8b-abd8-26b04270dc10.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by ShwetKhatri2001** [comment]
@Sarfraz-droid I'd like to work on this issue if it needs to be solved.

**Comment by Maahi10001** [comment]
hey @ShwetKhatri2001  can you Describe alternatives you've considered ?  instead you can show "No data or no codelabz found " kind of thing??

**Comment by ShwetKhatri2001** [comment]
Yes, that's also a good idea. Along with hiding those icons, We can also show the message - No organizations found.

**Comment by ShwetKhatri2001** [comment]
@Maahi10001 Can I start working on this issue according to our previous conversation?
OR you have something else to share ?
