### ISSUE TITLE
No page for notifications.

### ISSUE THREAD

**Issue by Pushpendra766** [scorelab/Codelabz#586]
For now there is no page for notifications in Codelabz app.  We need a page for notifications, that includes different sections for different notifications like All, Reactions, Comments, Mentions.( Image attachment shows the Figma design for reference)
![image](https://user-images.githubusercontent.com/56391001/210162134-1c6b5c35-5448-44dd-bb33-f699567943bd.png)

**Comment by Pushpendra766** [comment]
I want to work on this issue, please assign.

**Comment by Maahi10001** [comment]
@Pushpendra766 figma design should be similar to the codelabz design.

**Comment by Pushpendra766** [comment]
Got it.
