### ISSUE TITLE
sidebar content should be down 

### ISSUE THREAD

**Issue by mohdhaider07** [scorelab/Codelabz#591]
**Describe the bug**
we should put sidebar content little bit lower,
 for better UI

**Screenshots**
![image](https://user-images.githubusercontent.com/86488954/210166627-229ce35f-b5b3-4fca-aaf6-254ec896d0ec.png)

**Additional context**
@Maahi10001 @Sarfraz-droid  assign this to me

**Comment by Maahi10001** [comment]
actually I think that's not important as of now coz we will be including more fields into  it in up coming
