### ISSUE TITLE
Show Popular Tags on mobile screens

### ISSUE THREAD

**Issue by ShwetKhatri2001** [scorelab/Codelabz#592]
**Describe the bug**
Popular Tags are not being shown on mobile screens because of space limitation

**To Reproduce**
1. Go to 'Home Page'
2. See the Popular Tags on the right side are available for desktop but not visible below 960px

**Expected behavior**
The tags should be visible for the mobile screens as well. 
For that a row having all tags in a horizontal scroll can be added below `Activity` row to have all tags in minimal space

**Screenshots**
Suggested UI is as follows

![image](https://user-images.githubusercontent.com/56475750/210170167-a4dd38d7-28ec-453a-b908-712b3ce29ae5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by ShwetKhatri2001** [comment]
@Sarfraz-droid I'd like to work on this issue and make this improvement in UI.

**Comment by Maahi10001** [comment]
> @Sarfraz-droid and @Maahi10001 I'd like to work on this issue and make this improvement in UI.

sure.
