### ISSUE TITLE
Make all buttons look similar

### ISSUE THREAD

**Issue by ShwetKhatri2001** [scorelab/Codelabz#594]
**Describe the bug**
There are many different types of buttons having different colors, which shows inconsistency in the UI

**Screenshots**
Different styles of buttons currently present,

![image](https://user-images.githubusercontent.com/56475750/210175666-7de0458d-7c85-45fe-ad98-41e2e7c9d69e.png)
![image](https://user-images.githubusercontent.com/56475750/210175700-046e822c-93d5-44f2-9069-c345afdc52f4.png)
![image](https://user-images.githubusercontent.com/56475750/210175652-2ff61aaf-1614-400b-82ab-222dd8bbe9ec.png)
 

**Expected behavior**
All buttons should look similar with respect to style. 
We can make all the main submit and save buttons similar to current `LOG IN` and `CREATE ACCOUNT` buttons because its looking more consistent with our theme

![image](https://user-images.githubusercontent.com/56475750/210175590-3625e5f9-e75a-4cc0-88c6-33a2a2e6b6aa.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by ShwetKhatri2001** [comment]
@Maahi10001 and @Sarfraz-droid I'd like to work on this issue if it needs to be solved.

**Comment by rohit-shah840** [comment]
@Sarfraz-droid I would like to work  on this issues ,Please assign it to me.

**Comment by ishangaur07** [comment]
i would like to work on it
