### ISSUE TITLE
Search Bar only working till half of the length

### ISSUE THREAD

**Issue by vanshdeepsingh-coder** [scorelab/Codelabz#603]
**Describe the bug**

When hovering mouse pointer on the search bar we cannot click the search bar until the hover is within half of the search bar length,
same goes for typing, typing continues only till half point of the search bar 

**Steps to reproduce the behavior:**

1. Hover your mouse on search bar exceeding half of the length 
2. Type a long string on search bar you will see characters will not go beyond half of the point

**Expected behavior**
Search bar should hover, clicked  and typed up till it's full length

**Screenshots**
![Screenshot (757)](https://user-images.githubusercontent.com/82263082/210361881-ed77d467-dce5-4bc2-b49b-28e788c0c8f6.png)

**Desktop:**

 - OS: Windows 11
 - Browser: Mozilla firefox
 - Version; 108.0.1

**Comment by shahaab** [comment]
@vanshdeepsingh-coder would you like to work on this issue?

**Comment by mohdhaider07** [comment]
@shahaab  can I work on it?

**Comment by vanshdeepsingh-coder** [comment]
@shahaab please assign it me

**Comment by vanshdeepsingh-coder** [comment]
@Sarfraz-droid @Maahi10001 please assign this issue to me

**Comment by shahaab** [comment]
> @shahaab can I work on it?
@mohdhaider07 you are working on issue #601 already please finish it, and as @vanshdeepsingh-coder found this issue I will assign it to him.

**Comment by vanshdeepsingh-coder** [comment]
@shahaab Dear sir, i tried changing searchbar.css file and also tried changing navbar.js in components but nothing is happening i am not able to find the search bar code can you please guide me

**Comment by shahaab** [comment]
Check this folder
https://github.com/scorelab/Codelabz/blob/master/src/components/NavBar/new/MainNavbar/index.js

**Comment by vanshdeepsingh-coder** [comment]
#612

**Comment by vanshdeepsingh-coder** [comment]
@shahaab please review my pull request #614

**Comment by vanshdeepsingh-coder** [comment]
@shahaab I have made the necessary changes please review it at #615

**Comment by vanshdeepsingh-coder** [comment]
@shahaab please review my pull request #620
