### ISSUE TITLE
changing text to button on /user-dashboard/email page

### ISSUE THREAD

**Issue by mohdhaider07** [scorelab/Codelabz#610]
**Describe the bug**
for submitting the form there is no button there is just text 

**Expected behavior**
there should be a button

**Screenshots**
![image](https://user-images.githubusercontent.com/86488954/210542076-4c64bbc8-725a-4b96-afe5-3eccab6d8e3e.png)

![image](https://user-images.githubusercontent.com/86488954/210542176-576437f6-1569-40f7-b0bd-ce148e22a0a3.png)

**Additional context**
@Sarfraz-droid @Maahi10001  assign this to me

**Comment by Sarfraz-droid** [comment]
multi-email support hasn't been implmented yet

**Comment by mohdhaider07** [comment]
> multi-email support hasn't been implemented yet

But there should be  button
