### ISSUE TITLE
Sidebar opening unexpectedly

### ISSUE THREAD

**Issue by ShwetKhatri2001** [scorelab/Codelabz#613]
**Describe the bug**
The sidebar on medium/tablet screens ( 750px - 960px ) is opening unexpectedly when we click anywhere on the screen and get closed on the second click

**To Reproduce**
1. Go to 'Home Page'
2. Resize the window between '750px - 960px'
3. Click anywhere and see the sidebar opening from the right side

**Expected behavior**
The sidebar should open only when we click on the hamburger icon and should remain closed otherwise.

**Demo Video**

https://user-images.githubusercontent.com/56475750/210588467-f3618785-e8e4-46a1-a967-bc5cb9909d03.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by ShwetKhatri2001** [comment]
@Maahi10001 @Sarfraz-droid I'd like to work on this issue.

**Comment by karthiknadar1204** [comment]
please assign this issue to me,i would like to work on it

**Comment by karthiknadar1204** [comment]
I would like to work on this issue,we would have to adjust the state of the event occuring to the correct condition.
please assign it to me
