### ISSUE TITLE
Navbar has a bug when user clicks on on "USER SETTING" 

### ISSUE THREAD

**Issue by mohdhaider07** [scorelab/Codelabz#618]
**Describe the bug**
Navbar has a bug when user clicks on on "USER SETTING", it does not gets close 

**Screenshots**
https://www.veed.io/view/39202b9f-07b9-4d47-a5d2-3c6832029aa5?source=compressor-sharing

**Additional context**
@Sarfraz-droid @shahaab @Maahi10001  assign this to me

**Comment by Maahi10001** [comment]
Your Screen shot is not visible ! use default screen snip for screen shot or use record it for gif or video so that you can upload them easily.
