### ISSUE TITLE
buttons in menu not working when clicking on white space

### ISSUE THREAD

**Issue by mohdhaider07** [scorelab/Codelabz#619]
**Describe the bug**

when I am clicking on the white space of "My tutorial" and  "My profile"
it is not working, it is working when i am clicking on text of the button

**To Reproduce**
1. http://localhost:3000/
2. Click on profile top-right of the screen
![image](https://user-images.githubusercontent.com/86488954/210718182-5c5e3877-c2f0-4276-b2fe-3f458416694a.png)
4. click on white space of the button
![image](https://user-images.githubusercontent.com/86488954/210718098-afb70de6-4627-47f2-b2b1-e1a621b623eb.png)

**Expected behavior**
button should work by clicking of text as well as white space

**Screenshots**

https://user-images.githubusercontent.com/86488954/210718756-04c2ebff-19d5-4828-bbee-42982073aa6e.mp4

**Desktop (please complete the following information):**
 - 
**Additional context**
@Sarfraz-droid @shahaab @Maahi10001  assign this to me

**Comment by karthiknadar1204** [comment]
please assign this issue to me,i can resolve it
