### ISSUE TITLE
Header taking up whole page on medium viewports

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Codelabz#622]
**Describe the bug**
On the home page, when the width of the page is less than 960 pixels, the header takes up the whole page, resulting in the main content being displayed below it.

**To Reproduce**
1. Go to 'http://localhost:3000/'
2. Set width dimension less than 960 and Reload the page.

**Expected behavior**
The header should take up only the space that is required to display its contents, rather than taking up the whole page.

**Screenshots**
https://user-images.githubusercontent.com/91831606/211006729-84088bbf-c0d9-4ea5-8499-cd7be97f0e72.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Comment by YaSh8202** [comment]
I want to work on this issue. Please assign it to me.

**Comment by shahaab** [comment]
Okay please fix it.
