### ISSUE TITLE
Last Sidebar Item Should Not Be Empty

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Codelabz#624]
**Describe the bug**
We have noticed that the last item in the sidebar is an empty button when the user is not logged in. This button should not be present in this case. Instead, the last item in the sidebar should be the login button, which allows the user to log in.

**To Reproduce**
1. Go to http://localhost:3000/
2. Ensure that you are not logged in
3. Observe the last item in the sidebar

**Expected behavior**
The Last Item in the Sidebar Should Be the Login Button or the Empty Button Should Be Removed

**Screenshots**
![image](https://user-images.githubusercontent.com/91831606/211134878-789233c9-5f13-428d-87f2-d404c8c7079d.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome

**Additional context**
This issue only occurs when the user is not logged in. If the user is logged in, the last item in the sidebar is displayed correctly.

**Comment by shahaab** [comment]
@YaSh8202 can you fix this as well or should I assign it to someone else?

**Comment by Shashank2104125** [comment]
@shahaaab, sir please assign it to me. I can resolve it without taking much time.

**Comment by Shashank2104125** [comment]
![Screenshot_20230107_080239](https://user-images.githubusercontent.com/97789487/211155968-1ee7c8b8-db1f-4fd0-8bf7-ac854c042c54.png)

**Comment by Shashank2104125** [comment]
@shahaab, sir the last one is for checking purpose for user is have an access for dashboard or not

**Comment by YaSh8202** [comment]
@shahaab Yes, I can fix it. Please assign the task to me.

**Comment by shahaab** [comment]
Okay, @Shashank2104125 fix this issue.

**Comment by Shashank2104125** [comment]
@shahaab sir, I'm open a PR please review it....

**Comment by Shashank2104125** [comment]
@Rahulsingh1939 if you have not assigned this issue then why you open a PR?? close it ...

**Comment by ABHISHEK-PANDEY2** [comment]
@shahaab @Shashank2104125 Is there a need of the menu items when user is logged out ? because clicking on any item redirects user to login page , so why not just remove the sidenav when user is logged out

**Comment by Shashank2104125** [comment]
> @shahaab @Shashank2104125 Is there a need of the menu items when user is logged out ? because clicking on any item redirects user to login page , so why not just remove the sidenav when user is logged out

@ABHISHEK-PANDEY2  Sir, when user is logout there is no any item but there is a empty place remains for it because the  items are render by using map function that's the issue. If it sounds you important then can I fix this issue?

**Comment by ABHISHEK-PANDEY2** [comment]
@Shashank2104125 i get it , i am just suggesting there is no need of a navbar if user is not logged in the first place , you could even remove the whole navbar , btw do as you think is the best 👍

**Comment by Shashank2104125** [comment]
@ABHISHEK-PANDEY2  Sir, please review it.

**Comment by ABHISHEK-PANDEY2** [comment]
@Shashank2104125 don't call me sir , and i am not a collaborator , wait for them they will review it 👍

**Comment by Shashank2104125** [comment]
@Maahi10001 Sir, please review it.

**Comment by Shashank2104125** [comment]
@Maahi10001  Sir, please review it

**Comment by Maahi10001** [comment]
> @Maahi10001 Sir, please review it

we will do it in a sequence please wait.
