### ISSUE TITLE
Open a modal for sharing button

### ISSUE THREAD

**Issue by SubratYeeshu** [scorelab/Codelabz#626]
**Is your feature request related to a problem? Please describe.**
I wanted to create a modal for the share button or add a feature to the sharing button to copy the link to clipboard or open a modal in which there will be options to share the blog via Whatsapp, Mail and other services.

**Describe the solution you'd like**
1. A working modal with options
2. Copy link to clipboard

**Describe alternatives you've considered**
Whichever is suggested by the maintainer

**Additional context**

![CodeLabz_Notification](https://user-images.githubusercontent.com/75444646/211146820-5b23f65b-53a1-483c-92da-b4ec73b3c699.gif)

**Comment by SubratYeeshu** [comment]
@shahaab Can you please assign it to, and suggest me whichever option is suitable

**Comment by SubratYeeshu** [comment]
@shahaab sir, Can you please assign it to me

**Comment by aham-18113** [comment]
@rijusougata13 @piyumaldk @Sarfraz-droid 
I want to fix this issue. Kindly assign it to me.

**Comment by SubratYeeshu** [comment]
@shahaab @Maahi10001 Sir

**Comment by dasanik2001** [comment]
@rijusougata13 @shahaab 
I want to work on this issue. Can this issue be assigned to me ?
You can let me know about the features to be implemented.
