### ISSUE TITLE
Notification Button does not work

### ISSUE THREAD

**Issue by vanshdeepsingh-coder** [scorelab/Codelabz#631]
**Describe the bug**
when clicking on notification button nothing happens atleast should open a new page or a side bar

**To Reproduce**
Click on the notifications button on the home page

**Expected behavior**
At least a window should open or a side bar

**Screenshots**
![Animation](https://user-images.githubusercontent.com/82263082/211207272-97fb14ec-9252-40dd-995f-fc399ca8c674.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Mozilla firefox
 - Version: 108.0.1

**Comment by vanshdeepsingh-coder** [comment]
@Maahi10001, @Sarfraz-droid please assign this issue to me

**Comment by Shashank2104125** [comment]
@Maahi10001, @Sarfraz-droid please assign this issue to me. I can fix this issue without taking much time.

**Comment by Shashank2104125** [comment]
@Maahi10001, @Sarfraz-droid sir!! please review this.

**Comment by vanshdeepsingh-coder** [comment]
@Shashank2104125 when not assigned why are you linking pull request on my issue please create your own

**Comment by vanshdeepsingh-coder** [comment]
@shahaab sir can you please assign this to me

**Comment by Maahi10001** [comment]
> @shahaab sir can you please assign this to me

notification button is not yet implement it is and enhancement feature which is not need as of now work on some other issue
