### ISSUE TITLE
Attach a label to improve the user experience 

### ISSUE THREAD

**Issue by SubratYeeshu** [scorelab/Codelabz#634]
**Describe the bug**
There is no label attached to New CodeLabz Button which is not a good experience. There should be a label to the button on the text, such that user can create a new tutorial just by clicking on the text.

**To Reproduce**
1. Go to http://localhost:3000/
2. Click on New Tutorial
3. See error

**Expected behavior**
Should behave same when the + button is clicked 

**Screens
![Attach_Label](https://user-images.githubusercontent.com/75444646/211245858-e922647b-37c2-44b3-854d-8e1414eae3f1.gif)
hots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Mozilla Firefox
 - Version 108.0.2

**Comment by SubratYeeshu** [comment]
@shahaab @Sarfraz-droid , Sir can you please assign this issue to me

**Comment by parteekcoder** [comment]
@Maahi10001 @shahaab @Sarfraz-droid i made a PR on this issue can you please review that
