### ISSUE TITLE
Missing of being selected feature in Popular Tags component 

### ISSUE THREAD

**Issue by Shashank2104125** [scorelab/Codelabz#641]
**Describe the bug**
There is not any changes in tags buttons when user selected it for filtering purpose.

**To Reproduce**
1. Go to http://localhost:3000/
2. Click on  Tags buttons
3. Observe the changes 

**Expected behavior**
There should be a some changes on buttons after selecting it,

**Screenshots**
![image](https://user-images.githubusercontent.com/97789487/211446262-b8c3f326-0d78-415a-afce-abf5bfb1270e.png)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser chrome

**Additional context**
This issue only occurs when the user is trying to apply filter using tags.

**Comment by Shashank2104125** [comment]
@shahaab @Sarfraz-droid @, Sir can you please assign this issue to me. I can resolve it without taking much time.

**Comment by Shashank2104125** [comment]
@shahaab @Sarfraz-droid , Sir can you please assign this issue to me. I can resolve it without taking much time.

**Comment by Sarfraz-droid** [comment]
@Shashank2104125 avoid working on any feature. Since we are currently fixing the dependency tree.
