### ISSUE TITLE
Sidebar taking less width space

### ISSUE THREAD

**Issue by vanshdeepsingh-coder** [scorelab/Codelabz#644]
**Is your feature request related to a problem? Please describe.**
Sidebar taking less width space on desktop which is kind of awkward

**Describe the solution you'd like**
Adjust the sidebar so that it looks good on desktop

**Screenshot**
![Screenshot (769)](https://user-images.githubusercontent.com/82263082/211981784-0ac4e701-cfed-4688-97bb-7622d879f1e6.png)

**Comment by vanshdeepsingh-coder** [comment]
@shahaab sir please assign this to me

**Comment by Phani4658** [comment]
@Sarfraz-droid Please assign this to me

**Comment by vanshdeepsingh-coder** [comment]
@Phani4658 please create your own issue

**Comment by vanshdeepsingh-coder** [comment]
@Maahi10001 sir can you please assign this issue to me
