### ISSUE TITLE
Remove warnings of the code

### ISSUE THREAD

**Issue by aaditya9899** [scorelab/Codelabz#645]
**Describe the bug**
Theres a lot of warning in the code which i think should be fixed to give it a clean look.

![Untitled](https://user-images.githubusercontent.com/38832156/212045476-46f8a200-90cb-49ec-ac6a-eafe69c80915.png)

Can i work on this?

**Comment by aaditya9899** [comment]
can it be assign to me ?

**Comment by Vivekkushwaha123** [comment]
I can fix this all issues. Can I complete  this

**Comment by rahulMaurya140** [comment]
Can I work in this issue?
