### ISSUE TITLE
Incorrect input validation on dashboard page for determining user's country

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Codelabz#646]
**Describe the bug**
On the dashboard page, there is a TextField Input Component that is used for users to enter their country. However, the input validation for this field is not properly implemented and users are able to enter any text other than a country name. This results in inaccurate data being stored in the system and can cause issues in the future.

https://user-images.githubusercontent.com/91831606/212218500-c4cbe59d-9189-4b01-9d5b-89e0f2818be6.mp4

**To Reproduce**
1. Go to 'http://localhost:300/login'
2. Create a new account and you will be redirected to dashboard page.
3. Entry any text other than a country name and fill in other inputs.
4. Click Save.

**Expected behavior**
Users should only be able to select a country from the options provided and the system should not allow any other text to be entered.

**Proposed Solution**
 We can use the AutoComplete Material Component to take input for the country, which will only allow users to select from a pre-defined list of options.

**Screenshots**

https://user-images.githubusercontent.com/91831606/212220357-835715db-bcca-4ed4-bc38-49a22ef640c7.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by YaSh8202** [comment]
I would like to request to be assigned to this issue.

**Comment by Vivekkushwaha123** [comment]
Can I fix this issue
