### ISSUE TITLE
sidebar opening on clicking anywhere in medium screen

### ISSUE THREAD

**Issue by mohdhaider07** [scorelab/Codelabz#651]
**Describe the bug**
sidebar opening on clicking anywhere in medium screen

**To Reproduce**
1. Go to http://localhost:3000/
2. Arrange the screen size to medium
3. click anywhere

**Expected behavior**
it should not open unless until user click on hamburger menu

**Screenshots**
https://user-images.githubusercontent.com/86488954/212669223-91e4ee3a-13da-47e9-ae0b-163662c7ce05.mp4

**Additional context**
@Maahi10001 @Sarfraz-droid Can you please assign this to me

**Comment by ShwetKhatri2001** [comment]
@mohdhaider07 and @Sarfraz-droid I also found the same issue 3 weeks ago and also noted the behavior in issue https://github.com/scorelab/Codelabz/issues/613. 
So, just clarifying to not have multiple people working on the same issue. Thanks.
