### ISSUE TITLE
Social Media Buttons div overlapping profile

### ISSUE THREAD

**Issue by hs05june** [scorelab/Codelabz#652]
**Describe the bug**

**To Reproduce**
1. Go to 'localhost:3000/profile'
2. Reduce width to 850px.

**Expected behavior**
Both the sections should have same margin between them. 
**Screenshots**

https://user-images.githubusercontent.com/103871275/212743361-9ad65fed-bd38-44c8-a5cc-99a2664b3f56.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser : Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by parteekcoder** [comment]
@Maahi10001 can you please assign this issue to me

**Comment by parthsali** [comment]
Hey @hs05june, I think I can fix this issue. Can you please assign me this issue?
