### ISSUE TITLE
Multiple time upvote and downvote in cards

### ISSUE THREAD

**Issue by its-akashjha** [scorelab/Codelabz#655]
**Describe the bug**
Whenever we clicked on the card of upvote and downvote button , count of upvote and downvote increases or decreases many times.

**To Reproduce**
1. Go to http://localhost:3000/
2. Scroll down and see the cards.
3. Click on upvote or downvote button, multiple times.

**Expected behavior**
One profile allows only one time they can either upvote or downvote.

**Screenshots**
![Screenshot (177)1](https://user-images.githubusercontent.com/82963534/212846481-b2f1b9fa-931b-41c5-9afd-ceea95113602.png)

![Screenshot (178)1](https://user-images.githubusercontent.com/82963534/212846610-95cf3d9b-8b8c-490f-9a7e-ba5e0ff38230.png)

**Desktop
 (please complete the following information):**
 - OS: window 11
 - Browser : chrome

**Comment by its-akashjha** [comment]
@shahaab @Maahi10001 @Sarfraz-droid please assign this issue to me.

**Comment by rahulMaurya140** [comment]
Please assign this issue to me.

**Comment by 980vermarajput** [comment]
Hey in this issue can anyone downvote the activity if has already upvoted

**Comment by Vivekkushwaha123** [comment]
Hi This issue is solved approve this PR https://github.com/scorelab/Codelabz/pull/702

**Comment by its-akashjha** [comment]
Hey @Vivekkushwaha123 I am already created PR of this issue. Please check PR #684 and close this PR.
