### ISSUE TITLE
Buttons in profile are not clickable

### ISSUE THREAD

**Issue by shivareddy6** [scorelab/Codelabz#656]
**Describe the bug**
Buttons in the profile page(shown below in the image) don't have any button animations (on click or hover).

**To Reproduce**
1. Go to home page
2. Click on user icon on top right and profile in the menu
3. the buttons present there are not clickable

**Expected behavior**
These buttons should show normal animations of a button (changing color on hover and click animation on click)

**Screenshots**
![image](https://user-images.githubusercontent.com/74174769/212976578-f056b6ce-aea8-492f-b691-32747ac81833.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Comment by shivareddy6** [comment]
@Sarfraz-droid, @Maahi10001 can I work on this?

**Comment by hs-07** [comment]
Hello @shivareddy6 
Is the issue still open? 
if u not working over it, I would like to contribute to this project by resolving the issue.
waiting for the reply...😊

**Comment by shivareddy6** [comment]
I've already raised a pr, waiting for them to merger.
