### ISSUE TITLE
Files are not getting uploaded by clicking on icons on the new tutorial form

### ISSUE THREAD

**Issue by partik03** [scorelab/Codelabz#659]
**Describe the bug*When someone clicks on the image and video icons in the new tutorial form,nothing happens not file get uploaded.

**To Reproduce**
1. Go to 'new tutorial form'
2. Click on 'image/video 
3. See error

**Expected behavior**

https://user-images.githubusercontent.com/99184676/213878770-777470b8-59ce-4fff-9250-5b7ab606d502.mp4

]

**Smartphone (please complete the following information):**

**Additional context**

https://user-images.githubusercontent.com/99184676/213878822-0d4ceb2f-8e31-4a32-9643-ed4f3bbfa4b6.mp4

**Screenshots**

https://user-images.githubusercontent.com/99184676/213878781-e20e6b26-9297-4bd5-bb62-6f3a4601f04f.

**Comment by Shofiya2003** [comment]
I would like to work on the issue. Could you please assign it to me.

**Comment by partik03** [comment]
@Shofiya2003 actually I have already solved this issue

**Comment by Shofiya2003** [comment]
> @Shofiya2003 actually I have already solved this issue

👍
