### ISSUE TITLE
Organizations page stuck on loading

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Codelabz#660]
**Describe the bug**
On clicking the "Organizations" button in the sidebar, the organization page opens as expected. However, if the user does not belong to any organization, the page is stuck on loading.

**To Reproduce**
1. Go to ''http://localhost:3000/"
2. Login to the application and ensure that the user does not belong to any organizations
3. Click on the "Organizations" button in the sidebar
4. Observe that the page is stuck on loading if the user does not belong to any organization

**Expected behavior**
When a user who does not belong to any organization clicks on the "Organizations" button in the sidebar, the page should display a message indicating that the user does not belong to any organization, rather than getting stuck on loading.

**Screenshots**

https://user-images.githubusercontent.com/91831606/213901727-6c32bafd-ceb9-4bda-b26d-f17500797715.mp4

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: chrome

**Comment by YaSh8202** [comment]
@Sarfraz-droid @Maahi10001 
I am interested in working on this issue and would like to request that it be assigned to me.

**Comment by gaurav-2-0-0-2** [comment]
@Sarfraz-droid 
is anyone working on this issue if not can you assign me this to me.
