### ISSUE TITLE
Menu pops up on clicking on tab buttons on home page

### ISSUE THREAD

**Issue by ABHISHEK-PANDEY2** [scorelab/Codelabz#662]
**Describe the bug**
Hamburger Menu pops on clicking tab button

**To Reproduce**
1. Go to home page
2. reduce screen width below 960px
3. Scroll down to bottom
4. Click tab button on upcoming events

**Expected behavior**
Menu should not appear 

**Video**

https://user-images.githubusercontent.com/95560057/213927997-664d4b0e-4cee-4e94-9eb3-8b98f2dac174.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ABHISHEK-PANDEY2** [comment]
@Sarfraz-droid @Maahi10001 i would like to solve the bug

**Comment by Vivekkushwaha123** [comment]
Hi, I tried to run your app but it is more then our but I'm unable to solve this issue can you please help me 
![image](https://user-images.githubusercontent.com/102899392/213929904-53740a91-5fb2-427a-a390-71c79f2fcb16.png)

**Comment by ABHISHEK-PANDEY2** [comment]
Hey, @Vivekkushwaha123 Join the gitter channel , mentors and other contributors would help you

**Comment by Vivekkushwaha123** [comment]
What is gitter channel?

**Comment by ABHISHEK-PANDEY2** [comment]
https://gitter.im/scorelab/CodeLabz @Vivekkushwaha123 join the channel and ask your doubts

**Comment by Maahi10001** [comment]
> Hi, I tried to run your app but it is more then our but I'm unable to solve this issue can you please help me 
> ![image](https://user-images.githubusercontent.com/102899392/213929904-53740a91-5fb2-427a-a390-71c79f2fcb16.png)
> 

Once check the code some unnecessary< is added i guess

**Comment by Maahi10001** [comment]
Hey @ABHISHEK-PANDEY2   it is kept temporary redirection as we don't have the screens for them.

**Comment by ABHISHEK-PANDEY2** [comment]
@Maahi10001 so, should i fix the bug ? or leave it ?

**Comment by Maahi10001** [comment]
> @Maahi10001 so, should i fix the bug ? or leave it ?

Close it for now.
