### ISSUE TITLE
Email and Password Card of user-dashboard doesn't fit on small screen

### ISSUE THREAD

**Issue by hs05june** [scorelab/Codelabz#665]
**Describe the bug**
The email and password cards are bigger than the screen width. They don't fit.

**To Reproduce**
1. Go to '/user-dashboard/password' or '/user-dashboard/email'
2. Reduce the screen width below 960px.
3. See the error

**Expected behavior**
The cards must fix in the screen. 

**Screenshots**
https://user-images.githubusercontent.com/103871275/213987685-e64c3bfe-1a57-4c5c-a9b7-03cbe717ec24.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 22.04

**Additional context**

**Comment by ABHISHEK-PANDEY2** [comment]
hey, @hs05june the bug does not happen on my end

**Comment by The-Priya-Saw** [comment]
can you please assign this issue to me.I would like to wok on this issue.

**Comment by itsharshitb** [comment]
Hey Please assigned it to me. I would love to contribute.
