### ISSUE TITLE
codelabz website is not responsive

### ISSUE THREAD

**Issue by weberankit** [scorelab/Codelabz#668]
bug---website codelabz is not responsive for the small devices (px less than 500)

**To Reproduce**
1. Go to https://dev.codelabz.io/
2. go to the developer tool and inspect
3. see responsiveness by adjusting px at less than 500px
4. See error --content should be in the middle of the screen

**Expected behavior**
content should be in the middle of the screen (less than 500px)
**Screenshots**

 Browser [Chrome]
error--
![chrome_icvKJHQvOT](https://user-images.githubusercontent.com/94105514/214054247-4b1db8b2-6371-4213-aaf7-6133246b5129.png)
expected-
![chrome_e8usELZPMY](https://user-images.githubusercontent.com/94105514/214054372-212b6b0e-4b77-4b5c-a7f7-d1856c5855be.png)

**Comment by weberankit** [comment]
plz check PR #669  and review the code

**Comment by ABHISHEK-PANDEY2** [comment]
Hey @weberankit this is not the latest version deployed , You can fork the current state of the repo and work on that , join the gitter here https://gitter.im/scorelab/CodeLabz channel If you wish to contribute
