### ISSUE TITLE
dashboard is not responsive

### ISSUE THREAD

**Issue by Sumit-pd** [scorelab/Codelabz#670]
**Describe the bug**
On going to the chrome developer tools and increasing the size of the inspect the " I want to create an organization" goes out of the box

**To Reproduce**
1. Go to 'localhost:3000/dashboard'
2. open chrome developer tools
3. increase the area of the inspect area of the developer tools 
4. when you reach 190 x 889 screen size you will see that the "I want to create a new organization " goes out of the box

**Expected behavior**
 want to create a new organization " should be remaining inside of the box

**Screenshots**
![Screenshot from 2023-01-23 21-15-38](https://user-images.githubusercontent.com/88550925/214085796-9e682218-2a64-4c2e-80e4-e33adbff7e64.png)
take a look at bottom left at "i want to create an orgainization"

**Desktop (please complete the following information):**
 - OS: ubantu 22.041
 - Browser : chrome

**Additional context**
@Maahi10001 @Sarfraz-droid assign this to me , I want to work on this

**Comment by Sumit-pd** [comment]
I want to work on this

**Comment by ABHISHEK-PANDEY2** [comment]
hey, @Sumit-pd The dashboard is responsive , i don't think there is a need to add responsiveness for width of 190px  mobile widths don't go below 300px

**Comment by debanjanbanerjee46** [comment]
I want to work on this

**Comment by MukulKolpe** [comment]
Hey @Maahi10001, can I work on this issue?

**Comment by Sumit-pd** [comment]
Resolving this issue as it has been resolved in the vite branch!
