### ISSUE TITLE
The description is not dynamic with user data

### ISSUE THREAD

**Issue by ABHISHEK-PANDEY2** [scorelab/Codelabz#671]
**Describe the bug**
The description is not dynamic with user data it is hard coded, but profile name is dynamic

**To Reproduce**
1. Go to 'user-dashboard/profile'
2. Update name and descrption
3. Go to '/profile'
4. Name is updated but description is not
5. The social links also doesnot work on profile

**Expected behavior**
The description and social links should update

**Screenshots**

![ttt](https://user-images.githubusercontent.com/95560057/214101435-6ba79733-d273-4aec-a557-a218ccbf58ec.png)

![ttttt](https://user-images.githubusercontent.com/95560057/214101454-3ec03b9f-96df-4406-b388-6f5cc14ecae8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ABHISHEK-PANDEY2** [comment]
@Maahi10001 @Sarfraz-droid please review the issue

**Comment by ABHISHEK-PANDEY2** [comment]
@LokeshPatil-loki I raised the issue and i am already working on it please don't raise pr's without getting assigned to an issue .

**Comment by LokeshPatil-loki** [comment]
@ABHISHEK-PANDEY2 Okay

**Comment by Maahi10001** [comment]
Duplicate issue.
