### ISSUE TITLE
Missing of onClick dropdown functionality in Tutorial cards

### ISSUE THREAD

**Issue by Shashank2104125** [scorelab/Codelabz#673]
**Describe the bug**
On going to the home page when click on options provided in tutorial cards there is no any options comes for further proceedings.

**To Reproduce**
1. Go to 'localhost:3000/'
2. Click on 'options provided in right-bottom side of  tutorial cards'

**Expected behavior**
when user click on these options there should be comes dropdown/box for further proceedings.

**Screenshots**

https://user-images.githubusercontent.com/97789487/214534821-6a7a6115-0fd3-4bfa-859f-0cce7a6ef6d9.mp4

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [chrome]

**Additional context**
@Maahi10001 @Sarfraz-droid assign this to me , I want to work on this

**Comment by Maahi10001** [comment]
drop down? can you please ellobrate how you gona  make it any design ?

**Comment by Shashank2104125** [comment]
@Maahi10001, Sir it will look like this..

https://user-images.githubusercontent.com/97789487/214854538-b6b213ec-bbb2-4fec-89fd-e30107960413.mp4

**Comment by Maahi10001** [comment]
> @Maahi10001, Sir it will look like this..
> 
>  Google.Summer.of.Code_.Making.@SinghinUSA.s.first.OPEN.SOURCE.contribution.-.YouTube.-.Google.Chrome.2023-01-26.19-26-25.mp4

video isn't playing just loading..

**Comment by Shashank2104125** [comment]
@Maahi10001 
when user click on three dots then dropdown will open like this..
![image](https://user-images.githubusercontent.com/97789487/214858865-dd43e382-d4e2-49d8-bfc4-dc91977109a5.png)

And when user click on the share option then it will open 
![image](https://user-images.githubusercontent.com/97789487/214859158-0cd5113e-c1be-4a4a-9df5-1f1e97c22f23.png)

**Comment by Shashank2104125** [comment]
@Maahi10001 Sir, assign this to me , I want to work on this

**Comment by Vivekkushwaha123** [comment]
Assign this to me I can do this

**Comment by Vivekkushwaha123** [comment]
Do you have any figma design how it should look
