### ISSUE TITLE
User Settings content is not on the correct route and causing empty page

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Codelabz#674]
**Describe the bug**
There is a bug in the application where the User Settings content is being displayed on the wrong route ('/user-dashboard/settings' instead of '/user-dashboard/user-settings'). This is causing the User Settings container that is accessible from the '/user-dashboard/user-settings' route to be empty, indicating that the user settings code has not been implemented. This bug is causing confusion for users and needs to be fixed in order to provide a clear and consistent user experience.

**To Reproduce**
1. Go to 'http://localhost:3000/'
2. Click on the User Settings sidebar button
3. Observe that the User Settings container is showing empty
4. Go to 'http://localhost:3000/profile'
5. Click on the three dots and then click on user settings
6. Observe that the route is '/user-dashboard/settings' and it is showing user settings

**Expected behavior**
The User Settings page should be accessible through the '/user-dashboard/user-settings' route and not be empty.

**Screenshots**

https://user-images.githubusercontent.com/91831606/214561112-01046676-c89c-4087-8f89-59f2e7020570.mp4

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome

**Additional context**
 you should be logged in to the application to reproduce this issue.

**Comment by YaSh8202** [comment]
I want to work on this issue. Please assign it to me.

**Comment by parteekcoder** [comment]
i am working on this issue

**Comment by Maahi10001** [comment]
> I want to work on this issue. Please assign it to me.

yes, proceed.
