### ISSUE TITLE
Basic Typos

### ISSUE THREAD

**Issue by Sumit-pd** [scorelab/Codelabz#677]
**Describe the bug**
some basic typos

**To Reproduce**
1. Go to 'localhost:3000'
2. Open Chrome 
3. click on console
4. use of '==" instead of '===" at various places

**Screenshots**
If applicable, add screenshots
![Screenshot from 2023-01-26 19-20-52](https://user-images.githubusercontent.com/88550925/214854987-fda76170-b91f-41e2-a8f9-3a089fb05def.png)
 to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Ubantu
 - Browser: Chrome
 - Version  22.04.1

**Additional context**
@Maahi10001  @Sarfraz-droid  assign this to me I want to work on this

**Comment by Sumit-pd** [comment]
I want to work on this!

**Comment by parteekcoder** [comment]
hey @Maahi10001 , I made a PR on this issue can you please review

**Comment by Maahi10001** [comment]
> hey @Maahi10001 , I made a PR on this issue can you please review

@Sumit-pd  has the precedence has he made an issue and don't work on issue before assigning it creates conflicts, thanks.

**Comment by Sumit-pd** [comment]
@Maahi10001 I have raised a pr regarding this #681 can you please review this!

**Comment by Darkmindzakshay** [comment]
i want to work on this issue

**Comment by Novice-expert** [comment]
i want to work on this issue, please assign it to me.

**Comment by itsharshitb** [comment]
Hey Please assigned it to me. I want to work on this so badly.

**Comment by hirentimbadiya** [comment]
is this issue still open , if it is i would like to fix this issue , can you assign me?

**Comment by someshshukla** [comment]
I would like to fix this issue, can you please assign this issue to me?

**Comment by tusharmangal** [comment]
I want to work on this!

**Comment by Sumit-pd** [comment]
resolving this issue as it has been solved in the vite branch!
