### ISSUE TITLE
Change label for profile settings

### ISSUE THREAD

**Issue by ShwetKhatri2001** [scorelab/Codelabz#678]
**Describe the bug**
We have two pages with label `Profile`. One is to show user profile details and another is to show profile settings.
Being a user it looks quite confusing when I click on `Profile` and it open profile settings page, not profile details page.
These pages need to be distinguished.

**To Reproduce**
1. Click `User settings` from left sidebar on home page
2. You see two buttons here `Profile` on sidebar and `Go to Profile` on top right corner.
These are the same labels for different pages

**Expected behavior**
`Profile settings` should be the label on all buttons opening profile settings page.
Also the route can be changed from `/user-dashboard/profile` to `/user-dashboard/profile-settings`, 
since we already have `/profile` route available.

**Screenshots**
[Issue Demo Video](https://share.vidyard.com/watch/MksZkzxBoZoczdksdzwarx)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by parteekcoder** [comment]
@Maahi10001 could please assign me this issue

**Comment by IswarPatro** [comment]
I have to work on this issue please assign me this issue.
