### ISSUE TITLE
replace ant design with material design

### ISSUE THREAD

**Issue by hiranthaR** [scorelab/Codelabz#68]
- [x] add needed dependencies
- [x] convert page: /
- [ ] convert page: /login
- [ ] convert page: /signup
- [ ] convert page: //forgotpassword
- [ ] convert page: /mnageusers
- [ ] convert page: /dashboard
- [ ] convert page: /dashboard/my_feed
- [ ] convert page: /profile
- [ ] convert page: /organization
- [ ] convert page: /tutorials
- [ ] convert page: /tutorials/:owner/:tutorial_id
- [ ] convert page: /user/:handle
- [ ] convert page: /org/:handle
- [ ] convert page: /editor
- [ ] convert page: * (not found)
- [ ] remove ant design

**Comment by rijusougata13** [comment]
@hiranthaR  can i also work on this?
