### ISSUE TITLE
Last Item of Sidebar Should Not Be Empty

### ISSUE THREAD

**Issue by Shashank2104125** [scorelab/Codelabz#680]
**Describe the bug**
We have noticed that the last item in the sidebar is an empty button when the user is not logged in. This button should not be present in this case. Instead, the last item in the sidebar should be the login button, which allows the user to log in.

**To Reproduce**
1. Go to http://localhost:3000/
2. Ensure that you are not logged in
3. Observe the last item in the sidebar

**Expected behavior**
The Last Item in the Sidebar Should Be the Login Button or the Empty Button Should Be Removed

**Screenshots**
![leftSideBar](https://user-images.githubusercontent.com/97789487/214860809-8e35a1a5-04ee-44e0-b7af-2f19947aec5d.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome

**Additional context**
This issue only occurs when the user is not logged in. If the user is logged in, the last item in the sidebar is displayed correctly.

**Comment by Shashank2104125** [comment]
I want to work on this issue. Please assign it to me.

**Comment by parteekcoder** [comment]
@Maahi10001 could you please assign me this issue

**Comment by Shashank2104125** [comment]
@Maahi10001 could you please assign me this issue.

**Comment by ABHISHEK-PANDEY2** [comment]
There is already an issue similar to this #624 , @Shashank2104125 you can work on that
