### ISSUE TITLE
Improved User Interface for post cards

### ISSUE THREAD

**Issue by huzaifmalik786** [scorelab/Codelabz#683]
**Is your feature request related to a problem? Please describe.**
Right now, the picture in the post card is displayed first and then the rest of the details are shown. It does not look more appealing to have user information, post content and all kind of available options displayed together.

**Describe the solution you'd like**
I have tried to make a better UI design for the post card and tried to make it look like posts on most of the social media platforms, displaying user details at the top and then the content, followed by different available options. Please look at the screenshots for better understanding. 

**Screenshots**

**Before:**
![Screenshot (21)](https://user-images.githubusercontent.com/100015095/214921809-601448d1-5bea-4cee-9597-0f2a42ebdbc8.png)

**After :** 
![Screenshot (22)](https://user-images.githubusercontent.com/100015095/214921881-71c42bda-cdc5-4d7a-a01a-730e9a82f599.png)

**Comment by huzaifmalik786** [comment]
@Maahi10001 I would to like to work on this. Please review and assign it to me.

**Comment by karthiknadar1204** [comment]
if this issue is still open,i would like to work on it,please assign it to me

**Comment by karthiknadar1204** [comment]
Please let me work on this issue
