### ISSUE TITLE
Site crashes when organization page is reloaded

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Codelabz#687]
**Describe the bug**
When the organization page is reloaded, the site crashes.

**To Reproduce**
1. Go to 'http://localhost:3000'
2. Click on the "Organizations" button
3. Select any organization, the organization page will open
4. Reload the page
5. Observe that the site crashes

**Expected behavior**
The site should not crash when the organization page is reloaded.

**Screenshots**

https://user-images.githubusercontent.com/91831606/215040642-18cb0a6b-b4b0-4971-bb37-f7d19be96439.mp4

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: chrome

**Additional context**
User should be logged in and should have at least one organization.

**Comment by parteekcoder** [comment]
hi can you please assign me this issue

**Comment by shivareddy6** [comment]
Actually i asked about this issue already in the gitter, and was waiting for their reply. I see that this is the issue for everyone so i request to assign this issue to me.

**Comment by YaSh8202** [comment]
Closing this issue as it has been resolved in draft #640.
