### ISSUE TITLE
Make side menu always available and back to top option on Home page

### ISSUE THREAD

**Issue by anshuman-8** [scorelab/Codelabz#689]
**Is your feature request related to a problem? Please describe.**
Every time a person scrolls down in the **Home page** they have to scroll all the way back up to access the side option menu, this can be very frustrating if they are scrolled very far down.

**Describe the solution you'd like**
It would be better if the side option stays on the left side through the scroll, and an option on the bottom right to bring the person on the page top. And this gives a better user experience.

**Describe alternatives you've considered**
Having all the options available to the user without scrolling to the top is a good experience. I have also considered of having a UI of like Twitter where only the middle main element is scrollable and everything else is fixed.

**Additional context**
As of now, we can have a UI of something sort of Twitter web (as it is possible with our design and has better UX). We can also, fixed the size of each Card which does not change with change in content size.

<img src="https://user-images.githubusercontent.com/90995338/215126398-1ffa64cf-b832-4d2e-9d08-99d716773c1a.png" alt="Home-screen" width="700">

**Comment by codewithbharat** [comment]
I would like to work on this issue... Please it to me

**Comment by karthiknadar1204** [comment]
can i work on this issue
