### ISSUE TITLE
Unused variables 

### ISSUE THREAD

**Issue by Sumit-pd** [scorelab/Codelabz#690]
**Describe the bug**
There are multiple variables that are unused in the file

**To Reproduce**
1. Go to terminal
2. start the development server by npm start
3. Check the console, there are various variable that are not used

**Screenshots**
![Screenshot from 2023-01-27 19-19-29](https://user-images.githubusercontent.com/88550925/215102479-da9e8504-b199-4b3f-91c2-726fc12d7142.png)

**Desktop (please complete
![simplescreenrecorder-2023-01-27_19 15 16](https://user-images.githubusercontent.com/88550925/215102064-ec6e9122-f67c-41d4-a9d3-f2a1c936b719.gif)
 the following information):**
 - OS: Ubantu
 - Browser : Chrome
 - Version : 22.04.1

**Additional context**
@Maahi10001 @Sarfraz-droid assign this to me I want to work on this

**Comment by Sumit-pd** [comment]
I want to work on this!

**Comment by Maahi10001** [comment]
pls make necessary changes in #677 both are similar
