### ISSUE TITLE
Add a social share component to share content

### ISSUE THREAD

**Issue by ShwetKhatri2001** [scorelab/Codelabz#692]
**Is your feature request related to a problem? Please describe.**
We have a share button for a blog currently which is not functional to share the content anywhere.

**Describe the solution you'd like**
I'd like to create a share component that can be used to share any content via email, message and to some social media platforms such as Facebook, LinkedIn, Twitter, etc.

The UI will be updated like this where we get some social buttons below when we click the share button,
![image](https://user-images.githubusercontent.com/56475750/215194181-8f53172a-6259-4839-8759-f0a6722eefbf.png)

**Comment by ShwetKhatri2001** [comment]
@Maahi10001 and @Sarfraz-droid I'd like to start adding this feature soon. 
Provide your views on this ( if any) .

**Comment by itsharshitb** [comment]
Hey! @ShwetKhatri2001 I would like to give it a try. Can you please assign it to me.

**Comment by Sulochan-khadka** [comment]
I am unable to find the website or environment to inspect. Either give me the environment or assign me the issue to directly work on it.

**Comment by ShwetKhatri2001** [comment]
@itsharshitb and @Sulochan-khadka 
Actually, I've started working on this issue. 
You guys can figure out and open new issues to work on by yourself. 

Thanks.

**Comment by Sulochan-khadka** [comment]
No problem . In case you get any other issue, consider me . I will definitely be obliged to work with.

**Comment by itsharshitb** [comment]
Sure

**Comment by someshshukla** [comment]
@Maahi10001 and @Sarfraz-droid can you assign me this issue?
