### ISSUE TITLE
Hamburger SideNav Not aligned and, exit (cross) button not available in SideNav 

### ISSUE THREAD

**Issue by Novice-expert** [scorelab/Codelabz#693]
**Describe the bug**
The Hamburger sideNav is not aligned properly and the exit button is not present to go back from Navbar, to the current page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'http://localhost:3000/'
2. Inspect to 960px.
3. Click on that Hamburger icon.
4. You will see an unaligned Navbar, with no cross(Exit) button to return to the current page.

**Expected behaviour**
An exit(cross) button should be there to close the Side Navbar back and return to the current page itself.

**Screenshots**
<img width="452" alt="Screenshot 2023-01-28 at 1 24 23 PM" src="https://user-images.githubusercontent.com/95133039/215254674-1a506df1-9562-4d5d-ac07-1d2631bd795c.png">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Comment by Novice-expert** [comment]
I'm interested in solving this issue, please assign it to me.

**Comment by git2chirag** [comment]
Hello there i am interested in solving this issue,please assign this issue this to me.

**Comment by tusharmangal** [comment]
I'm interested in solving this issue, please assign it to me.
