### ISSUE TITLE
fix alignment in signin logos

### ISSUE THREAD

**Issue by chandansgowda** [scorelab/Codelabz#695]
**Describe the bug**
Social SignIn (Google, Facebook, Twitter and Github) logos not aligned properly in login and create account page

**To Reproduce**
1. Go to [Login Page](https://dev.codelabz.io/login) or  [Registration Page](https://dev.codelabz.io/signup)
2. See SignIn with Social Accounts Logos

**Expected behavior**
All logos should be aligned properly.

**Screenshots**
<img width="617" alt="Screenshot 2023-01-29 at 9 20 55 AM" src="https://user-images.githubusercontent.com/41890434/215303974-0a72f1a0-37c4-42d6-bdbf-d856eca86c62.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Brave

**Comment by gurpreet-legend** [comment]
@chandansgowda, I would like to work on this

**Comment by Shashank2104125** [comment]
@Maahi10001 , @Sarfraz-droid  Sir, I would like to work on this, please assign it to me.

**Comment by Vivekkushwaha123** [comment]
![image](https://user-images.githubusercontent.com/102899392/215322818-919399f4-7c42-44ca-a153-9107a6cc7930.png)
getting this request will making push request

**Comment by Sulochan-khadka** [comment]
I think this should work fine
<img width="1440" alt="Screenshot 2023-02-03 at 7 59 28 PM" src="https://user-images.githubusercontent.com/122200551/216628647-b6ec0621-7c5a-48e2-bb50-17f59d7ab5e5.png">

kindly assign me this issue to work on. 

suggestion: The logo of Facebook has to change as it is not fitting perfect to the padding.

**Comment by Sulochan-khadka** [comment]
This should work.
Kindly assign me this issue
<img width="1440" alt="Screenshot 2023-02-03 at 8 12 59 PM" src="https://user-images.githubusercontent.com/122200551/216631663-30d26bca-1c1f-489e-bf7c-bd19dc0d19e5.png">
