### ISSUE TITLE
Activity List Topbar is not responsive

### ISSUE THREAD

**Issue by hs05june** [scorelab/Codelabz#699]
**Describe the bug**
As the device width decreases, New and Top button move to new line.

**To Reproduce**
1. Go to 'http://localhost:3000/'
2. Reduce device width'
3. See error

**Expected behavior**
Featured, New and Top button should remain in same line

**Screenshots**

https://user-images.githubusercontent.com/103871275/215779702-20e9a6dc-0dff-4bae-a8a2-aa22b62f7929.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version : 22.04

**Comment by Sulochan-khadka** [comment]
I am unable to open localhost 3000 . kindly put it to the live server so that I can inspect it.

**Comment by karthiknadar1204** [comment]
@Sulochan-khadka ,are you still working on this issue?
