### ISSUE TITLE
Responsiveness of Buttons on Organization Page at Small Screen Size

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Codelabz#701]
**Describe the bug**
On the organization page, the "Edit org", "More icon", and "Subscribe" button are not responsive at small screen sizes. Currently, the "Subscribe" button gets to the next line, instead of being on the same line as the other two buttons. This leads to a poor user experience, as the buttons are not optimally sized or positioned for small screens.

**To Reproduce**
1. Go to 'http://localhost:3000'
2. Click on 'Organizations'.
3. Select any organization.
4. Observe the "Edit org", "More Icon", and "Subscribe" buttons.

**Expected behavior**
Buttons should remain on the same line at all screen sizes, including small screens.

**Screenshots**

![localhost_3000_(iPhone SE)](https://user-images.githubusercontent.com/91831606/216013122-0f1cec83-6022-447a-a727-9dee14a2404c.jpg)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - Browser: chrome

**Additional context**
The user should be a member of at least one organization. If the user is not a member of any organization, they will not be able to see the buttons on the organization page.

**Comment by YaSh8202** [comment]
I want to work on this issue. Please assign it to me.

**Comment by itsharshitb** [comment]
Hey! @YaSh8202 I would like to give it a try. Can you assign it to me.

**Comment by Sulochan-khadka** [comment]
kindly post this to live server so that I can reproduce it and give you possible solutions; or assign me the issue to work on .

**Comment by karthiknadar1204** [comment]
if no one is working on this issue,please assign it to me
