### ISSUE TITLE
Improved User Interface for Popular Tags Section

### ISSUE THREAD

**Issue by Shashank2104125** [scorelab/Codelabz#703]
**Describe the bug**
Right now, when user is visited on popular tags section there is no any effect if user move cursor on given tags.

**To Reproduce**
1. Go to 'http://localhost:3000/'
2. Visit on popular tags and move cursor on different-different tags.

**Expected behavior**
Tags Buttons should show change in their previous state when cursor move on it.

**Screenshots**
before:

https://user-images.githubusercontent.com/97789487/216150339-f6ba9acf-8c2d-4f02-84ef-21c7cc7b1012.mp4

after:

https://user-images.githubusercontent.com/97789487/216147994-58025e4a-024c-4b9f-8f78-92082ffbcdab.mp4

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome

**Comment by Shashank2104125** [comment]
@Maahi10001 , @Sarfraz-droid  Sir, I want to work on this issue. Please assign it to me.

**Comment by himik-nainwal** [comment]
Hi, you can look at this feature in my  [portfolio](https://himiknainwal.tech). 
I believe I can be the right person to do this and implement it efficiently.
Please assign it to me.

**Comment by Sulochan-khadka** [comment]
I am unable to reproduce this . Therefore may you enable me to work on this by either assigning this issue to me or hosting it to web; so that I can work on it.

**Comment by Shashank2104125** [comment]
@Maahi10001 , @Sarfraz-droid Sir. Please assign it to me.

**Comment by Darkcoder011** [comment]
hello i will install your project in my vs code and it work well . we will do much more change in that pages just like tags Shadow and much more 

@Maahi10001  @Sarfraz-droid

**Comment by karthiknadar1204** [comment]
If this issue is still available,i would like to work on it
