### ISSUE TITLE
The ability to comment under codelabz tutorials

### ISSUE THREAD

**Issue by partik03** [scorelab/Codelabz#705]
**Is your feature request related to a problem? Please describe.**
Yeah whenever one tries to click on the comment icon on any tutorial nothing happens.

**Describe the solution you'd like**
A user should hold the ability to give his/her feedback by commenting under a tutorial.

**Describe alternatives you've considered**

**Additional context**

https://user-images.githubusercontent.com/99184676/216443794-ac6e3097-2ffb-49a6-98b8-00d3e4ac8f72.mp4

**Comment by partik03** [comment]
@Sarfraz-droid @Maahi10001 Please Assign this issue to me

**Comment by Sulochan-khadka** [comment]
how do I obtain the environment to suggest the possible solution to the issue

**Comment by someshshukla** [comment]
@Maahi10001 @Sarfraz-droid  please assign me this issue
