### ISSUE TITLE
Improvement in the Popular Events tab 

### ISSUE THREAD

**Issue by AwaneeshSoni** [scorelab/Codelabz#710]
**Describe the bug**
When the width is less than 866px the tab of Popular events becomes a little bad with the UI.
**To Reproduce**
1. Go to 'Codelabz website'
2. Click on 'Inspect elements'
3. Change the width to less than 866px you will see the problem in the popular events tab.
4. See the error

**Expected behavior**
It should be one column when the height is reduced.
**Screenshots**
How it is 
![before](https://user-images.githubusercontent.com/72563109/216810076-de2171c7-6296-4190-a61b-8fd8508603b8.png)

How it should be

![after](https://user-images.githubusercontent.com/72563109/216810070-5d461a8d-d586-4092-b18a-78ad76a27a24.png)

**Comment by AwaneeshSoni** [comment]
Please assign this issue to me.

**Comment by AwaneeshSoni** [comment]
{ Closed the issue by mistake }
Please assign it to me.

**Comment by karthiknadar1204** [comment]
@AwaneeshSoni ,are you still working on this issue?

**Comment by AwaneeshSoni** [comment]
@karthiknadar1204 Yes
