### ISSUE TITLE
Overflowing content in delete organization modal

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Codelabz#711]
**Describe the bug**
When attempting to delete an organization, the content within the modal is overflowing, causing a horizontal scrollbar to appear. This negatively impacts the user experience and makes it difficult to access all necessary information within the modal.

**To Reproduce**
1. Go to 'http://localhost:3000'
2. Click on 'Organizations'
3. Click on 'DELETE' button.
4. Observe the overflowing content and horizontal scrollbar in the delete organization modal

**Expected behavior**
The content within the delete organization modal should be contained within the modal window, without causing a horizontal scrollbar to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/91831606/216825202-7f9d1e23-41a2-45f8-bfcb-827ed8bcc08c.png)

**Desktop :**
 - OS: Windows 10
 - Browser chrome

**Additional context**
You should have at least one organization.

**Comment by YaSh8202** [comment]
I want to work on this issue. Please assign it to me.

**Comment by AmitSharma512** [comment]
@YaSh8202 if you dont mine can i take this issue , i have already solved this issue

**Comment by YaSh8202** [comment]
@AmitSharma512 Sure, you can take this issue.

**Comment by Smriti925** [comment]
Hello @YaSh8202, If this issue is not resolved please assign it to me.

**Comment by thakurprathya** [comment]
if the bug still exists, i can solve it, please assign it to me.
