### ISSUE TITLE
Login page Screen Overflows in smaller width devices

### ISSUE THREAD

**Issue by hirentimbadiya** [scorelab/Codelabz#712]
**Describe the bug**
Screen Overflows for the smaller width devices of width <= 500px

**To Reproduce**
1. Go to 'https://dev.codelabz.io/login'
2. Right Click and click inspect
3. make dimensions width near 480px to 500px
4. See that screen overflows

**Expected behavior**
screen should not be overflowing.

**Screenshots**
Overflowing Screen : 
![overflow](https://user-images.githubusercontent.com/86219935/217152818-cf8c93e1-cbee-4dd5-ba95-09b29c452dac.png)

Expected : 
![expected](https://user-images.githubusercontent.com/86219935/217152871-92796c13-dc7e-43bc-9df5-1a0a269354f4.png)

**Desktop (please complete the following information):**
 - OS: windows 10[e.g. iOS]
 - Browser: Chrome[e.g. chrome, safari]
 
**Smartphone (please complete the following information):**
 - Device: iPhone12[e.g. iPhone6]
 - OS:iOS 14.1 [e.g. iOS8.1]
 - Browser: Chrome
 

**Additional context**
to have responsive website need to fix this issue , i am ready and available to fix this issue , please assign me this issue.

**Comment by hirentimbadiya** [comment]
can anyone assign me this issue please , i would like to work on this issue!! thank you in advance :)

**Comment by hirentimbadiya** [comment]
@Maahi10001 , @Sarfraz-droid , @Janvi-Thakkar can you please assign me this issue.

**Comment by Smriti925** [comment]
Please assign this issue to me.

**Comment by SinghYuvraj0506** [comment]
Is the issue still Available. Can i fix it ?

**Comment by Hitanshi-Singh** [comment]
hey can you assign this issue to me?? I would like to work on it

**Comment by hirentimbadiya** [comment]
> hey can you assign this issue to me?? I would like to work on it

i am also waiting to get assigned this issue.
