### ISSUE TITLE
Mirgating the Codebase

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#713]
Hello Everyone,
We are currently undergoing a migration with the current codebase, which includes :

---
- [X] Updating the bundler from @craco to @vitejs
- [X] Switching from mui v4 to v5
- [x] Adding new & Updating the current cypress tests 
#714 
#720
#726 
- [x] Upgrade firebase v8 to v9 
#747
- [x] Updating the documentation.
#739 
- [X] Implementing CI/CD for cypress tests 
 #716 
 #718

---

We will not be merging any PRs to the master branch till then since this will cause additional conflicts while migration

You can see the changes at #640. You can contribute on the above changes by a PR/Issue to `vite` branch instead.
If you're planning to work on any issue, please provide with a brief of your changes as well. 

PS: Don't add any extra bug fixes/feature requests except for the changes noted above to `vite` branch.

**Comment by BabyElias** [comment]
Hey @Sarfraz-droid, if possible, I would like to work on updating the documentation part, but I guess that will be needed once the migration is complete?

**Comment by partik03** [comment]
Hey @Sarfraz-droid ,I wanted to contribute in updating the codebase.How can I start to work on it??

**Comment by Mayshank18** [comment]
Hey @Sarfraz-droid Would like to work on upgrading firebase v8 to v9. Have already worked with such an issue before in live project.

**Comment by aaditya9899** [comment]
i can work upon the documentation part , can you pls tell what all things should be included @Sarfraz-droid

**Comment by mahfoos** [comment]
i can work on the documentation part , can you please let me know what we need to add @Sarfraz-droid

**Comment by malihaeram11** [comment]
@Sarfraz-droid is there any tasks pending or is eveything done?
