### ISSUE TITLE
Organization Icon not Displayed in Menu Bar

### ISSUE THREAD

**Issue by AYRUS06** [scorelab/Codelabz#722]
*Describe the bug*
The current menu bar which appears on clicking on the user avatar displays a block icon instead of the relevant organization icon for my organization's menu item. This makes it difficult for users to quickly identify the organization they are currently in. Therefore, I suggest that the organization icon should be used instead of the block icon.

*To Reproduce*
1. Go to 'http://localhost:3000'
2. Click on the user avatar in the top right corner of the page.
3. Observe that the menu bar appears with a block icon next to the organization menu item.

*Expected behavior*
When users click on the user avatar and the menu bar appears, the organization icon should be displayed next to the organization menu item.

*Screenshots*
![image](https://user-images.githubusercontent.com/91831606/220981632-95fb51d9-0a98-4237-bd75-2b125a056403.png)

*Desktop (please complete the following information):*
 - OS: Windows10
 - Browser chrome

**Comment by nikhilhvr** [comment]
I'd like to contribute to this issue and will start investigating the cause of the problem.

Let me know if you're also working on this. Excited to contribute!

**Comment by thakurprathya** [comment]
If the bug still exists & no one is working on it, please assign it to me.

**Comment by somu5307** [comment]
Is this issue still exist.

**Comment by IswarPatro** [comment]
I would like to work on this issue... Please assign it to me

**Comment by a-verma26** [comment]
Could you please assign me to work on this issue?
