### ISSUE TITLE
Menu options under profile icon changes position on changing the screen size.

### ISSUE THREAD

**Issue by Pheewww** [scorelab/Codelabz#728]
**Describe the bug**
Menu options under profile icon changes position on changing the screen size, they move towards left hand side.

**To Reproduce**
1. Go to deployed site on https://dev.codelabz.io/
2. Click on your profile icon
3. menu options occur related to your profile.
4. try minimizing the screen size

**Expected behavior**
menu option stays at it's place.

**Screenshots**
[Menu_options_bug.webm](https://user-images.githubusercontent.com/67512605/221399828-61c2cd19-988c-436d-ab04-2197c1ff61bd.webm)

**Desktop (please complete the following information):**
 - win 10
 - Browser: Brave

**Comment by M-SAI-SOORYA** [comment]
Can @Maahi10001 @kasundezoysa @e assign me the issue ... the problem is of responsiveness

**Comment by Pheewww** [comment]
I'm already working on this one.
