### ISSUE TITLE
Icons mis-alignments of menu-option under profile icon

### ISSUE THREAD

**Issue by Pheewww** [scorelab/Codelabz#729]
**Describe the bug**
Icons are mis-aligned under menu option.
**To Reproduce**
1. Go to https://dev.codelabz.io/
2. Click on profile menu icon

**Expected behavior**
icons are mis-aligned with their menu-options.

**Screenshots**
![profile_menu_ais-alignments](https://user-images.githubusercontent.com/67512605/221400396-adbd9569-6fe5-4741-bd4d-74825b32094d.png)

broswer: Firefox

**Comment by Pheewww** [comment]
@kasundezoysa @Maahi10001 pls assign this to me. It could involve adjusting the padding, margin, or positioning of these elements.

**Comment by Mayshank18** [comment]
@kasundezoysa @Maahi10001Please assign this to me. It only requires flexbox property. As soon as you assign flex property to the block they get aligned.

**Comment by ShivanshKhankriyal** [comment]
I want to work on this issue please assign it to me, it is only a matter of div being pushed by the other components of the menu bar.

**Comment by ABHISHEK-PANDEY2** [comment]
@Pheewww please fork and clone the repo , the current project version and the deployed version is not same , Find bugs in the current version . And codelabz is not accepting any UI bug fixes currently as it is going through a migration , Join the gitter channel for more info
