### ISSUE TITLE
The SearchBar Overflows

### ISSUE THREAD

**Issue by Mayshank18** [scorelab/Codelabz#730]
**Describe the bug**
The search bar in the landing page overflows after a certain stage when you continue typing in.

**To Reproduce**
1. Go to https://dev.codelabz.io/
2. Sign Up to create a profile.
3. Move to the landing page where you see the navbar
4. Try to type gibberish in the search bar component until it overflows.

**Expected behavior**
The component should not overflow and provide some padding at the end of the search bar component to encapsulate the text in a clean manner.

**Screenshots**
![Screenshot (61)](https://user-images.githubusercontent.com/71022316/221433835-53bf68bf-8ac0-4758-912c-6555b365d5b1.png)

**Comment by ANUSHRAV01** [comment]
@Mayshank18  This SearchBar Overflow problem has been resolved 
![codelabz](https://user-images.githubusercontent.com/100953727/221497232-0e8f59d9-48a4-4527-8b3c-c304d7403eea.png)

try it again for yourself if link don't work
@rijusougata13 u can close this issue

**Comment by ABHISHEK-PANDEY2** [comment]
Do not find bugs in the deployed version , Clone the repo and run locally , the current version is not same as the deployed version.
for any doubts join the gitter channel

**Comment by himanshu1221** [comment]
hey @ANUSHRAV01 Bug is still there 

![Screenshot from 2023-03-01 10-44-30](https://user-images.githubusercontent.com/32031706/222051257-d473503b-9ba9-4687-9a3b-42a34e1fdfe2.png)

<h3>Please assign me this issue if this issue is still open</h3>

**Comment by Pheewww** [comment]
> hey @ANUSHRAV01 Bug is still there
> 
> ![Screenshot from 2023-03-01 10-44-30](https://user-images.githubusercontent.com/32031706/222051257-d473503b-9ba9-4687-9a3b-42a34e1fdfe2.png)
> ### Please assign me this issue if this issue is still open

please read the discussion above. clone the repo and try finding bugs in the current version.
