### ISSUE TITLE
[BUG] Overflow in x direction 

### ISSUE THREAD

**Issue by himanshu1221** [scorelab/Codelabz#734]
**Describe the bug**

whenever we check the responsiveness there is overflow in x direction 

**To Reproduce**
1. Go to 'deployed website'
2. Click on 'inspect'
3. Scroll down to 'left'

**Expected behavior**

there should not be any extra overflow in x direction

**Screenshots**

[BUG.webm](https://user-images.githubusercontent.com/32031706/222050830-77c7a5fd-396c-4049-a988-d5f458974a87.webm)

**Desktop (please complete the following information):**
 - OS: [UBUNTU]
 - Browser [chrome]
 - Version [110.0.5481.177]

**Smartphone (please complete the following information):**
 - Device: [iPhoneX]
 - Browser [chrome]

**Additional context**

<h3>Please review this issue and assign this issue to me i am ready to work on it</h3>

**Comment by Pheewww** [comment]
please find bugs in the current version by cloning the repo. deployed version is different.
