### ISSUE TITLE
[FEAT] Dark theme for home page 

### ISSUE THREAD

**Issue by himanshu1221** [scorelab/Codelabz#735]
**Is your feature request related to a problem? Please describe.**

I went to the website what I can see is this website has no dark theme I find it important so i would love to work on the same 

**Describe the solution you'd like**

with the help of JS and custom CSS, I will add the dark theme to all the pages and a toggle button with which we can toggle to dark theme as well as to a light theme 

**Additional context**

we will add the toggle button in the navbar or in the bottom as the maintainer says and will add an appropriately dark colour to the website 

<h3>Please review the issue and if find it appropriate please assign this task to me, I would love to work on this issue !</h3>

**Comment by shauryag2002** [comment]
@himanshu1221  Hey!! I want to work on this issue. I'm new here so I'm really excited to start contributing. Please assign it to me.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue,please assign it to me
