### ISSUE TITLE
[BUG]UI enhancement

### ISSUE THREAD

**Issue by himanshu1221** [scorelab/Codelabz#736]
**Describe the bug**

Search bar is not in center 

**To Reproduce**
1. Go to 'Signup Page'
3. Scroll to 'top'

**Expected behavior**

it should be in center 

**Screenshots**

![Screenshot from 2023-03-01 13-08-04](https://user-images.githubusercontent.com/32031706/222074663-707df84a-bd58-4669-ac00-839ca634fec6.png)

**Desktop (please complete the following information):**
 - OS: [UBUNTU]
 - Browser [chrome]
 - Version [ 110.0.5481.177 ]

**Additional context**
<h3>please review the issue if you find it valid enough then I would love to work on this issue please assign this issue to me</h3>

**Comment by Pheewww** [comment]
codelabz is not accepting any UI bug fixes currently as it is going through a migration , Join the gitter channel for more info
