### ISSUE TITLE
Unexpected widening of login screen.  

### ISSUE THREAD

**Issue by Pushpendra766** [scorelab/Codelabz#737]
**Describe the bug**
When we are on login page and we got any error, the login card gets wide in order to contain that error in a single line.

**To Reproduce**
1. Go to the Login Page while turning off the emulators(in order to intentionally get the error).
2. Click on Google to log in using Google
4. See the error.

**Expected behavior**
The width of the login card should not change and the error should take multiple lines if needed to show it while keeping the width of login/signup card constant.

**Screenshots**
![image](https://user-images.githubusercontent.com/56391001/222249516-dbf1865c-495a-4cb5-8b58-b3c04a584477.png)

**Comment by Pushpendra766** [comment]
I want to work on this issue, please assign me.

**Comment by IswarPatro** [comment]
I would like to work on this issue... Please assign it to me
