### ISSUE TITLE
 User avatar nav menu not aligned with user avatar

### ISSUE THREAD

**Issue by AYRUS06** [scorelab/Codelabz#738]
**Describe the bug**
When clicking on the user avatar in the top right corner, the nav menu opens but it appears to be misaligned with the user avatar. Specifically, the nav menu is vertically displaced by 3rem from the user avatar, which is causing some visual inconsistencies.

**To Reproduce**
1. Go to 'http://localhost:3000'
2. Click on the user avatar in the top right corner of the page.
3. Observe the position of the nav menu in relation to the user avatar.

**Expected behavior**
The nav menu should open aligned with the user avatar, and there should be no vertical displacement of 3rem.

**Screenshots**
![Codelabz-login2](https://user-images.githubusercontent.com/82778823/222433893-1ae93435-cf60-429e-aacd-b7ffc9bfb2a1.gif)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome

**Additional context**
User should be logged in

**Comment by AYRUS06** [comment]
i want to work on this issue please assign it to me.

**Comment by devilkiller-ag** [comment]
Hi, Can I work on this Issue if not assigned to someone?

**Comment by a-verma26** [comment]
My Approach:
To solve the issue of the misaligned nav menu when clicking on the user avatar in the top right corner, you can follow these steps:

Inspect the HTML and CSS code: Using your browser's developer tools, inspect the code responsible for displaying the user avatar and the nav menu. Look for any CSS rules that might be causing the misalignment.

Adjust the CSS positioning: Once you have identified the CSS rules causing the misalignment, try adjusting the positioning of the nav menu. You may need to experiment with different values for the top or margin-top properties to achieve the desired alignment.

Use responsive design techniques: If the misalignment is occurring only on certain screen sizes or devices, consider using responsive design techniques to adjust the layout of the page based on the device being used.

Can you please assign this issue to me?
