### ISSUE TITLE
My Tutorials and My Profile icon is not centred vertically

### ISSUE THREAD

**Issue by devilkiller-ag** [scorelab/Codelabz#741]
**Describe the bug**
When clicking on the user avatar in the top right corner, the My Tutorials and My Profile Icon appears to be vertically misaligned with the text.

**To Reproduce**
1. Go to '[Codelabz Homepage](https://dev.codelabz.io/)'
2. Sign In with your account
3. Click on your profile icon to open the Menu
4. Observe the position of My Tutorials and My Profile Icon, it's not centered vertically

**Expected behavior**

**Screenshots**
![Code-labz-bug1](https://user-images.githubusercontent.com/43639341/222941746-0c89023f-217e-424f-be6f-b50e169ee3cc.png)
![Codelabs](https://user-images.githubusercontent.com/43639341/222941846-aab93b75-3234-494d-80fd-a6122152f47f.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 22H2 (OS Build 22621.1265)
 - Browser Chrome
 - Version 22

**Smartphone (please complete the following information):**
 - Device: Oppo F19 Pro Plus (Model: CPH2213)
 - OS: ColorOS 13.0
 - Browser: Chrome

**Additional context**
User should be logged In

**Comment by harshithhdasari** [comment]
Hey! could anyone assign me this issue?

**Comment by turjoc120** [comment]
I am interested in working on this issue, @devilkiller-ag

**Comment by devilkiller-ag** [comment]
I have created this issue to work on it. Can someone please assign this to me?

**Comment by turjoc120** [comment]
@devilkiller-ag hey, I guess they are not accepting any fixes rn, some migration is going on, check the Gitter channel
