### ISSUE TITLE
[BUG] Voting bug 

### ISSUE THREAD

**Issue by himanshu1221** [scorelab/Codelabz#742]
**Describe the bug**
Whenever we click on the vote to upvote the post it allows us to click multiple time so that it increases the spam number of upvote 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the 'home page'
2. Click on the 'upvote button multiple times'
3. See the error

**Expected behaviour**
It should allow us to click one at a time 

**Screenshots**

[bug found .webm](https://user-images.githubusercontent.com/32031706/222952806-c0d20cc6-4e0f-4701-8c3b-da6eec397b33.webm)

**Desktop (please complete the following information):**
 - OS: [UBUNTU]
 - Browser [Chrome]
 - Version [110.0.5481.177]

**Comment by turjoc120** [comment]
Hi, @himanshu1221 can i work on it?

**Comment by IswarPatro** [comment]
I want to work on this issue please assign me this issue.

**Comment by Kirito-Excalibur** [comment]
@himanshu1221 I am unable to reproduce the bug. How do you even open the blogs? They are just texts. Not links.

**Comment by himanshu1221** [comment]
> @himanshu1221 I am unable to reproduce the bug. How do you even open the blogs? They are just texts. Not links.

I have not opened the blog i just upvoted the Static blog and found that glitch u can refer to the video which i have shared above
