### ISSUE TITLE
Unable to Read/Upload Image

### ISSUE THREAD

**Issue by YaSh8202** [scorelab/Codelabz#750]
**Describe the bug**
On the organization setting page, user is not able to read or upload the organization profile image (or any file) due to the following issues:
1. In the Firebase config file, the emulator storage is not configured. Specifically, the following line is missing:
`firebase.storage().useEmulator("localhost", 9199);`
This line of code is required to configure the storage emulator, which is necessary for local development and testing.
2. In the storage.rules file, the read and write permissions are set to false. This means that users are not allowed to read or write any data to the storage bucket.

**To Reproduce**
1. Go to 'http://localhost:3000'
2. Click on 'Organization'
3. Upload Image by clicking on 'Choose File'.
4. It will keep showing 'Uploading Info'.

**Expected behavior**
When a user clicks on the upload button to upload an image, the image should be successfully uploaded to the Firebase storage bucket and the profile image on the organization setting page should be updated with the uploaded image.

**Screenshots**

https://user-images.githubusercontent.com/91831606/224011961-4860aa08-e968-4cb9-a177-f1a3ebe46da4.mp4

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser : Chrome

**Additional context**
- this issue is on the 'vite' branch

**Comment by karthiknadar1204** [comment]
Can i work on this issue

**Comment by YaSh8202** [comment]
@Sarfraz-droid @Maahi10001
I would like to work on this issue. Could you please assign it to me?
