### ISSUE TITLE
Unclickable buttons

### ISSUE THREAD

**Issue by Sumit-pd** [scorelab/Codelabz#758]
**Describe the bug**
The "Deactivate account" and "Delete account" buttons are not clickable
**To Reproduce**
1. Go to 'http://localhost:5173/user-dashboard/settings'
2. Hover on  "Deactivate account" and "Delete account" 
3. See error , the buttons are not clickable!

**Expected behavior**
The should have an onclick event or link to a new page or component!

**Screenshots**
![simplescreenrecorder-2023-03-15_17 48 15](https://user-images.githubusercontent.com/88550925/225307570-cd36a5ac-d9ef-47c1-ac46-79ab8f05f0e9.gif)

**Desktop (please complete the following information):**
 - OS:Ubantu
 - Browser :chrome
 - Version:  22.04.1 LTS

**Additional context**

**Comment by Sumit-pd** [comment]
@Sarfraz-droid  @Maahi10001  I would like to work on this issue!

**Comment by Cipher-08** [comment]
Hi there , that seems interesting . would like to work on this issue

**Comment by Vivekkushwaha123** [comment]
Where it should redirect after click delete

**Comment by Vivekkushwaha123** [comment]
@Maahi10001  plz check this PR https://github.com/scorelab/Codelabz/pull/760
