### ISSUE TITLE
GSOC-2023 Proposal tasks

### ISSUE THREAD

**Issue by Maahi10001** [scorelab/Codelabz#759]
# Checklist

- [ ] Database Design for Codelabz.

    - Create an **ER(Entity Relationship) Diagram** understanding how codelabz data flow would work.
        - ER Diagram should cover atleast 3 entities. namely which includes,
            - User
            - Organizations
            - Posts
        - You can additionally add more entities depending on the use cases.
        - Your database design should show how:
            - Users/Organizations will create, like & comment on posts.
        - You can use any diagram makers like Lucid charts, [[Draw.io](http://draw.io/)](http://Draw.io) etc.
        - Optionally, **contributors** can also share their ideas on a feed system/algorithm for codelabz. (How the “Home” feed should display posts for any user).
    

    **NOTE**
    
    We are using **Firebase Firestore** as the database for Codelabz. Make sure the design it accordingly.
    

---

- [ ]  Design Screens for

    - **Codelabz Editor** *(New Notebook screen)*
    - Notifications page
    - Post Page.
    - Explore Screen(Optional)
    
    Contributors can design the above pages in **Figma.** *(Just the design only, there’s no need to implement the screens for proposals)*
    
    **NOTE** 
    
Make sure your Designs match with the existing Codelabz Design System.

**Comment by Sarfraz-droid** [comment]
Hello Everyone! This issue is for contributors participating in GSoC 2023. 
This issue includes the checklist containing the important things to include in your gsoc proposal!

If you have any doubts, you can join our community at https://matrix.to/#/#scorelab_CodeLabz:gitter.im

**Comment by STSARC001** [comment]
Hello Everyone! I am Abhijit Dengale participating in GSoC 2023.
i want to be the part of Your community 

thanks !!

**Comment by Sarfraz-droid** [comment]
This is the tasks for contributors creating their proposals for GSoC. They have to work on both in their proposal

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue

**Comment by umershaikh123** [comment]
> 

is there a figma file for already existing designs ?
and is there a reference design or any guide for the Codelabz Editor (New Notebook screen)

**Comment by real-varshney** [comment]
i want to get assigned on the second task

**Comment by malihaeram11** [comment]
I have made all the er diagrams and figma designs apart from 'Post Page' @Sarfraz-droid @Maahi10001 @charithccmc
Please describe 'Post Page'? is it similar to Home page but consists only of Posts by organization/users??

**Comment by Sarfraz-droid** [comment]
@malihaeram11 the Post page is the individual post the shows when a user clicks on the post on his feed

**Comment by malihaeram11** [comment]
> @malihaeram11 the Post page is the individual post that shows when a user clicks on the post on his feed
Understood, thank you @Sarfraz-droid
