### ISSUE TITLE
continuously increases and decreases the voting system .

### ISSUE THREAD

**Issue by Akshat171** [scorelab/Codelabz#765]
**Describe the bug**
When we decrease the voting option on the post then it will go on the negative side also as it is not stopping at 0 and also it continuously increases and decreases as we press on it.
**To Reproduce**
1. Go to 'any post'
2. Click on the 'down arrow'
3. See the error --negative voting

**Expected behavior**

According to me, the voting point should be a stop at zero and also when we press the arrow it should be increased or decreased only at once by a single person

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [ chrome]
 - Version [22]

**Additional context**
it is not good for any application to have a bug like this and in my opinion, the voting arrow should be accepted only at once by a person.

https://user-images.githubusercontent.com/81281246/227294521-36726d57-ac0d-48b0-b3e5-a5f21158c1c1.mp4

**Comment by 26thavenue** [comment]
@Akshat171  can I work on this

**Comment by Akshat171** [comment]
@26thavenue I have already sent PR on this.
