### ISSUE TITLE
Add Cool CSS for SideList

### ISSUE THREAD

**Issue by Danish-Belal** [scorelab/Codelabz#768]
**Is your feature request related to a problem? Please describe.**
For any webpage, there should be SideList to navigate like Twitter have, along with cool user interaction.

**Describe the solution you'd like**
Add more styling for sideList so and background color to make it interactive.

**Comment by AbhishekBhamare** [comment]
@Danish-Belal  Hey Can I work on this?

**Comment by 26thavenue** [comment]
@Danish-Belal can  you assign me this issue
