### ISSUE TITLE
Logo redirecting

### ISSUE THREAD

**Issue by Varunvaru524** [scorelab/Codelabz#777]
**Describe the bug**
Clicking on the logo of code labs doesn't redirect to the home page or to the top of the page

**To Reproduce**
 Go to any page and click on the page's top left corner logo

**Expected behavior**
On clicking the logo on the top left corner, it should redirect to the home page or to the top of the page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft edge

**Comment by ayesha-firdaus** [comment]
can you please assign me I am interested

**Comment by ayesha-firdaus** [comment]
shall I start working on this? please confirm

**Comment by gaurav19790** [comment]
Can u assign this issue to me

**Comment by PransCh** [comment]
Can u assign this issue to me. I would like to start working on it

**Comment by harshsbhandari** [comment]
@Varunvaru524 can you please assign this issue to me, I am willing to work on this issue. Hope to hear from you soon.

**Comment by Varunvaru524** [comment]
Start working and send the pull request directly.

**Comment by harshsbhandari** [comment]
hey @Varunvaru524, I have setup the project locally, when I run it locally, all I see is a blank white page, also the the link to the project https://dev.codelabz.io/ does not works, can you help

**Comment by PransCh** [comment]
@Varunvaru524 I am also experiencing the same issue as him @harshsbhandari. let us know where we went wrong, Thanks
