### ISSUE TITLE
Notfound page bug

### ISSUE THREAD

**Issue by Varunvaru524** [scorelab/Codelabz#780]
**Describe the bug**
There is no back to the home button on the not found page

**To Reproduce**
Go to a random URL in the codelabz official website and you can see the not found page you can observe that there is so back button or back to home button on the not found page

**Expected behavior**
There should be a back button or back to the home button on the not found page so that the users can click on the button and go to the previous page from where they have came.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge

**Comment by S-Parker7000** [comment]
Assign me this issue

**Comment by shaikahmadnawaz** [comment]
Shall I start working on this issue?
