### ISSUE TITLE
Unusual height of the Navbar on smaller screens on page reload.

### ISSUE THREAD

**Issue by noob-coder-19** [scorelab/Codelabz#788]
**Describe the bug**
Unusual height of the navbar on smaller screens on page reload. However, when you open the navbar, and then close it, the height becomes normal.

**To Reproduce**
1. Go to /signup route (for example)
2. Open devtools once the page loads
3. See the error, if not, refresh the page.
4. Now, click on the burger icon and then close the menu. 
5. Height becomes normal now.

**Expected behavior**
The height should be normal from the start.

**Screenshots**

https://user-images.githubusercontent.com/58938375/229812886-e33fafa0-bc8b-47dd-8fff-2c6796508c50.mov

https://user-images.githubusercontent.com/58938375/229811900-c1fada45-725c-4188-9310-bccade85d251.mov

**Desktop (please complete the following information):**
 - OS: MacOs Ventura
 - Browser: Latest versions of Microsoft Edge, Google Chrome and Brave
 - Version: Latest versions

**Comment by kushalShukla-web** [comment]
hey bro did you created pr for this issue ?

**Comment by nikhilagastya** [comment]
hey i would like to work on this, I am new to Open Source and ig it will help me learn more about it

**Comment by Swayam-Khare** [comment]
I think this PR has fixed the issue:
https://github.com/scorelab/Codelabz/pull/791

**Comment by PransCh** [comment]
hey, I have setup the project locally, when I run it locally, all I see is a blank white page, also the the link to the project https://dev.codelabz.io/ does not works, can you help
