### ISSUE TITLE
button send me the link is not up to date 

### ISSUE THREAD

**Issue by kushalShukla-web** [scorelab/Codelabz#803]
**Is your feature request related to a problem? Please describe.**
when user type email , button will only be disabled when user typed correct form of email . email should contain character , number , and @gmail.com other wise button will not be unable .

**Describe the solution you'd like**
button should be disabled when user type wrong mail format .

**Describe alternatives you've considered**
yeah so just change that button format .

**Additional context**

https://github.com/scorelab/Codelabz/assets/85934954/232c8bcc-af54-4d03-a132-f1cd897d783a

**Comment by Priyanshu471** [comment]
I want to work on this issue please assign it to me, I am new to Open Source and it will help me learn more.

**Comment by kushalShukla-web** [comment]
#802 pr

**Comment by Deeppjp116** [comment]
Hello! I'm eager to contribute to this issue and make a meaningful impact. Could you please provide guidance on how I can get involved in this GitHub open-source project? I'm enthusiastic and ready to contribute!

**Comment by Deeppjp116** [comment]
PR at #808

**Comment by Rohit-Singh-Rawat** [comment]
Hi, i am interested in this issue can u assign to me.

**Comment by kushalShukla-web** [comment]
bro pull request is created for this issue . you can contribute in some other projects

**Comment by kushalShukla-web** [comment]
pull request created
