### ISSUE TITLE
when click on send me the link , user get link for forgottpassword .

### ISSUE THREAD

**Issue by kushalShukla-web** [scorelab/Codelabz#817]
**Is your feature request related to a problem? Please describe.**
when user click on "send me the link" then user get forgot password link , in gmail .

**Describe the solution you'd like**
likely to create component for that and create send me the link in gmail .

**screenshot 
![Screenshot (133)](https://github.com/scorelab/Codelabz/assets/85934954/f34469ac-8a20-476f-96cb-2c917091c110)
 considered**

**Comment by mohit03nandan** [comment]
i want to working with issue please assign me a issue

**Comment by kushalShukla-web** [comment]
go ahead

**Comment by geeky-sambhav** [comment]
Could u pls assign this issue to me??

**Comment by kushalShukla-web** [comment]
go ahead Sambhav

**Comment by GIGA-CODER** [comment]
Even I want to work on this issue , can I proceed with it?

**Comment by cosmos-dx** [comment]
I want to work on it. Please assign me the issue.

**Comment by kushalShukla-web** [comment]
Yes, go ahead.

**Comment by kushalShukla-web** [comment]
please create pull request . cause so many people commented but non of them
create pull requests

**Comment by cosmos-dx** [comment]
its being hard to setup firebase .... its giving auth error . Can you help please I am new  !

**Comment by prabhatkr007** [comment]
if the issue is still there, can you please assign this to me?

**Comment by Huzaif-Ahmed** [comment]
@kushalShukla-web can you please elaborate what do you want us to do?

**Comment by KrishavRajSingh** [comment]
@kushalShukla-web can you elaborate the issue?
