### ISSUE TITLE
Refactor control buttons

### ISSUE THREAD

**Issue by shivareddy6** [scorelab/Codelabz#818]
**Is your feature request related to a problem? Please describe.**
The placement of control buttons (below editor) is not user friendly.
There is no option of marking a step complete

**Describe the solution you'd like**
Move up the control buttons to the steps side panel and include a "complete step" button.

**Comment by samyakshah3008** [comment]
If this is not specific for GSOC 2023 engineers, I would like to take up this issue ticket and fix it 😄  
Cheers.

**Comment by shivareddy6** [comment]
Actually it was a part of my current work, I'm almost done with it too.

**Comment by samyakshah3008** [comment]
Sounds cool, no issues. I would love to contribute by reviewing that PR then:) 

Also let me know if you have any good first issues, I would love to fix them.

**Comment by shivareddy6** [comment]
> Sounds cool, no issues. I would love to contribute by reviewing that PR then:)
> 
> Also let me know if you have any good first issues, I would love to fix them.
> 
> // @shivareddy6

Yeah sure.
