### ISSUE TITLE
change the color of "create" button to white 

### ISSUE THREAD

**Issue by wilsonfurtado2000** [scorelab/Codelabz#822]
**Describe the bug**
<img width="1358" alt="Screenshot 2023-07-06 at 11 59 23 AM" src="https://github.com/scorelab/Codelabz/assets/72563697/4753e6bd-b014-4778-a5f8-0b79bd5e5cf2">
the color of create button should be white , so that is clearly visible to the user
**To Reproduce**
1. click on create new tutorial option , a modal opens you can see the create button in the right bottom corner

**Expected behavior**
change the color of "create" text to white 
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CS-parth** [comment]
Can this issue be assigned

**Comment by NitinRana01125532553** [comment]
Hey, I fixed this issue in this PR #824
check it out

**Comment by kushalShukla-web** [comment]
can i contribute in it ?
