### ISSUE TITLE
what is the work of this search bar ?

### ISSUE THREAD

**Issue by kushalShukla-web** [scorelab/Codelabz#832]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm 
![Screenshot from 2023-07-14 00-12-39](https://github.com/scorelab/Codelabz/assets/85934954/f7870ae2-c4c5-4593-96ad-f4ee539f226f)
always frustrated when [...]
what should this search bar need to do . 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kushalShukla-web** [comment]
guys @Sarfraz-droid  @Maahi10001  what is the work of this search bar ?

**Comment by Sarfraz-droid** [comment]
@kushalShukla-web the search bar is currently inactive because the backend is currently in development. We can start working on the searchbar once the backend will be updated in this GSOC 23 sprint

**Comment by kushalShukla-web** [comment]
i see
