### ISSUE TITLE
Revamping the Explore Page

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#834]
Revamp and build the Explore page as per the new UI

Figma design: https://www.figma.com/file/ih6RajLWwrMBxN7oSxKct3/All?type=design&node-id=407%3A4051&mode=design&t=3tQqLb3G0UnbW2J4-1

**Comment by kushalShukla-web** [comment]
nice , hey i think i can work on this one

**Comment by Ashish-1016** [comment]
> nice , hey i think i can work on this one

Hey @kushalShukla-web are you still working on this issue?. If yes Can we both contribute so that the heavy-lifting get's divided.

**Comment by Sarfraz-droid** [comment]
Hey, this is a GSoC 23 tagged issue, i.e., The GSoC 23 contributors will be working on this. Meanwhile you can look for other issues or create on if you like. Thankyou!
