### ISSUE TITLE
Make side bar in create tutorials page collapsible

### ISSUE THREAD

**Issue by shivareddy6** [scorelab/Codelabz#843]
**Is your feature request related to a problem? Please describe.**
Make side bar in create tutorials page collapsible

**Describe the solution you'd like**
I would like to give an option to collapse the side bar containing steps

**Comment by sanket-1305** [comment]
hey!
I want to solve this issue please assign me this.

**Comment by sanket-1305** [comment]
I want to solve this issue please assign me.

**Comment by shivareddy6** [comment]
I already raised a pr for this.

**Comment by sanket-1305** [comment]
Hey!
I am a beginner in development still working on my basics, It would be very
helpful to me if I can have your guidance on this. Is it possible that we
can talk at your convenience? On whichever platform you say just I want to
learn.

**Comment by shivareddy6** [comment]
solved with https://github.com/scorelab/Codelabz/pull/844
