### ISSUE TITLE
Remove step not working in tutorial creation

### ISSUE THREAD

**Issue by shivareddy6** [scorelab/Codelabz#847]
**Describe the bug**
While creating a tutorial and have multiple steps, remove step option is not removing the step.

**To Reproduce**
1. Login and go to `http://localhost:5173/tutorials`
2. create a tutorial (click on `add new codelabz` and fill the information)
3. create a new step (click on `add new step` and fill the information)
4. Click on `remove step` button
5. The page reloads but the step is not removed

**Expected behavior**
1. When you click on `remove step` button, the step should be removed from the front end
2. In the firestore doc (`tutorials/tut_id/steps/step_id`) of the respective step, the field `deleted` should be marked true

**Video**

https://github.com/scorelab/Codelabz/assets/74174769/570aa1a6-58bc-4245-a2b3-a3f50172ab83

**Comment by Matrx123** [comment]
assign : #847

**Comment by Matrx123** [comment]
Hi @shivareddy6 good afternoon, I did the local setup following the contributing.md file, project is starting, while recreating the issue i am not able to register a user below is attached screenshot. any guidance will be appreciated.

![firebase](https://github.com/scorelab/Codelabz/assets/34768582/dc914998-7fb9-4206-b979-2eb6b4a0672b)

NOTE* : while getting the <FIREBASE_DATABASE_URL> i have created an open testing real time database with region  as "us-central1", below is the screenshot attached for DB.

![DB](https://github.com/scorelab/Codelabz/assets/34768582/8bdb7e4e-604a-4445-827a-0faf9c8c8478)

**Comment by shivareddy6** [comment]
Hello @Matrx123, Did you start firebase emulators?
If not open a new terminal and enter the command `make emulator-import`

**Comment by Matrx123** [comment]
Hi @shivareddy6 Thankyou, i am facing issue in starting the firebase emulators. i am resolving it and get back to you.

**Comment by Matrx123** [comment]
hi @shivareddy6 , i was to run emulators and while registering it went success, but i didn't received the verification link, though it said "link has been send".
I have given my gmail Id while registering.
Emulator logs are also OK stating "verification link has been send to my gmail ID".
Thanks

**Comment by Matrx123** [comment]
hello @shivareddy6 , i am being able to recreate the issue, thanks for the support.
i will try to fix this
thanks

**Comment by Matrx123** [comment]
hi @shivareddy6 i have created a PR against the issue #849 . Thank you very much for your help.
have a good day.

**Comment by shivareddy6** [comment]
[solved](https://github.com/scorelab/Codelabz/pull/849)
