### ISSUE TITLE
Cannot start the project 

### ISSUE THREAD

**Issue by ffalpha** [scorelab/Codelabz#85]
**Describe the bug**
when we try to start the project it fails

**To Reproduce**
1. Start the project using npm start 
2. See the error

**Expected behavior**
Project Wont start 

**Screenshots**
![9999](https://user-images.githubusercontent.com/31257148/120016914-d1f69d80-c002-11eb-83ee-9fab053f21f0.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser :Chrome

**Comment by rijusougata13** [comment]
closing this issue as PR merged :)
