### ISSUE TITLE
Documentation: Link not working in FAQs section.

### ISSUE THREAD

**Issue by Yashasv-Prajapati** [scorelab/Codelabz#852]
**Describe the bug**
In FAQs section, point number 3. In solution, the links for setting up firebase emulator, and starting the emulator does not redirect anywhere useful. It simply loads back to the same page.

**Expected behavior**
Clicking on the link should redirect to their corresponding webpage.

**Screenshots**
![image](https://github.com/scorelab/Codelabz/assets/40720591/d566615c-127e-45f3-ba90-27b65bd2c4f3)

**Comment by shivareddy6** [comment]
Hey @Yashasv-Prajapati, do you want to work on fixing this?
You can find the corresponding webpages in `https://github.com/scorelab/Codelabz/blob/master/CONTRIBUTING.md`

**Comment by Yashasv-Prajapati** [comment]
Yes, sure @shivareddy6, I've already setup the project. I'll start working on this issue now.

**Comment by Yashasv-Prajapati** [comment]
BTW, @shivareddy6, the demo link given in the README is not working, is there some problem with the deployment?

**Comment by shivareddy6** [comment]
Yes, we are working on it.

**Comment by shivareddy6** [comment]
[solved](https://github.com/scorelab/Codelabz/pull/853)
