### ISSUE TITLE
Setup Husky for auto formatting on pre commit 

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#854]
There have been multiple issues while reviewing due to issues with conflicting formats.
 
feature: add Husky for a pre-commit hook to run code formatting and linting before commits. 
reference: https://typicode.github.io/husky/

**Comment by BatukeshwarVats** [comment]
Can you assign this to me.

**Comment by MuntazirHaider** [comment]
Attempt: #854

**Comment by BatukeshwarVats** [comment]
@Sarfraz-droid can you assign this to me.

**Comment by ankit-k56** [comment]
@Sarfraz-droid Is this issue still open , can I work on it?

**Comment by MuntazirHaider** [comment]
As a beginner, I've encountered challenges working with documents and files. I tried but failed I think its your turn Please go ahead @ankit-k56  and thank you  @Sarfraz-droid  and @ABHISHEK-PANDEY2 for your guidance .

**Comment by aaditya9899** [comment]
is this issue still open or anyone working on it?

**Comment by GIGA-CODER** [comment]
is this issue still open or anyone working on it?

**Comment by Pheewww** [comment]
@ankit-k56 @Sarfraz-droid @ABHISHEK-PANDEY2 can u assign this to me, 

just need to add --> "husky": {
  "hooks": {
    "pre-commit": "npm run lint && npm run format"
  }
}

**Comment by Pheewww** [comment]
@ABHISHEK-PANDEY2 can you assign it to me

**Comment by Pheewww** [comment]
@ABHISHEK-PANDEY2 @shivareddy6 it has'nt been solved for long, can i solve it? please assign if nobody is working on it

**Comment by GIGA-CODER** [comment]
I would like to work on this , please assign it me

**Comment by yogi2103** [comment]
@Sarfraz-droid @ABHISHEK-PANDEY2, I want to work on it. Can you please assign it to me?
