### ISSUE TITLE
Faulty Demo Link 

### ISSUE THREAD

**Issue by aryan-bhokare** [scorelab/Codelabz#866]
**Bug Description**
When Clicked on  the demo link given in Readme.md I'm getting redirected to some spam website.

![Screenshot (241)](https://github.com/scorelab/Codelabz/assets/92683836/7c05324c-e5f1-4482-94f6-3e37688e7238)

![Screenshot (240)](https://github.com/scorelab/Codelabz/assets/92683836/4c39ea2b-1074-4a28-ab4e-88d8aeafc093)

**To Reproduce**
1. Go to 'https://github.com/scorelab/Codelabz'
2. Click on link below this 'https://github.com/scorelab/Codelabz#deployment'
3. See spam website

**Expected behavior**
Website of Codelabz should have been shown.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome

**Comment by Sulochan-khadka** [comment]
@aryan-bhokare  seems that the url is broken somewhere. Assign me this issue to work on.

**Comment by umangutkarsh** [comment]
The Readme.md needs to be updated. Is anyone working on this?

**Comment by prabhatkr007** [comment]
@aryan-bhokare if the issue is still there, can you please assign this to me?

**Comment by umangutkarsh** [comment]
@shivareddy6 , where can I find the link that leads me to the deployed website.
