### ISSUE TITLE
Missing Key prop in various components of the project.

### ISSUE THREAD

**Issue by skbhagat0502** [scorelab/Codelabz#869]
**Title:** Missing "**key**" props in React components

**Description:**
I have reviewed the code and identified that the "key" prop is missing in the following React components which is creating warnings in the console also they can cause bugs if not corrected:

**ActivityList**
**TagCard**
**EventsCard**
**UserCard**

I have made the required changes by adding the "**key**" props wherever they are necessary to avoid potential bugs and improve the stability of our application.

Changes Made:

In the ActivityList component, I added the "key" prop to the corresponding elements in the list.
In the TagCard component, I added the "key" prop to the corresponding elements in the list.
In the EventsCard component, I added the "key" prop to the corresponding elements in the list.
In the UserCard component, I added the "key" prop to the corresponding elements in the list.

**Testing:**
I have tested the updated components to ensure that they now function correctly and that the "key" props provide unique identifiers for each item in the lists. The changes have been verified and are ready for review.

**Please review the code changes and merge the pull request when appropriate.**

**Comment by skbhagat0502** [comment]
I have made the pull request. Please review it.

**Comment by skbhagat0502** [comment]
Hey @shivareddy6, I have made the changes in the pull request as you said. Please review and merge the pull request.

**Comment by shivareddy6** [comment]
solve with https://github.com/scorelab/Codelabz/pull/872
