### ISSUE TITLE
Missing the terms and conditions page link in the singup page.

### ISSUE THREAD

**Issue by skbhagat0502** [scorelab/Codelabz#871]
**Subject**:- The **terms and conditions** page link is missing in the signup page.

Description:- In the singup page on the codelabz website the terms and conditions page link is missing. The text **terms and conditions** should be bold and it should redirect to the terms and conditions page of the codelabz website. 
As you can see here.

![image](https://github.com/scorelab/Codelabz/assets/109683163/7d33d58b-ddcf-422f-ac3e-1bd6ec9a0291)

These things should be changed. 
I want to work on this. Please provide me the terms and conditions page link so that I can resolve this issue as I am not able to find it on the web or in the codebase.

**Comment by harshsharma-11** [comment]
@skbhagat0502 @kasundezoysa @charithccmc @Niweera @AsithaIndrajith where to communicate ,is there any channel like slack where problems like setting up can be solved

**Comment by skbhagat0502** [comment]
@shivareddy6 What about this issue. Can I work on this. If yes can you provide me the link of the terms and conditions page of the codelabz.

**Comment by shivareddy6** [comment]
actually we are currently focusing on building codelabz completely. @Sarfraz-droid, we are yet to draft terms and conditions.

**Comment by skbhagat0502** [comment]
ok @shivareddy6

**Comment by harshsharma-11** [comment]
@shivareddy6 when will this repo open to contribute

**Comment by shivareddy6** [comment]
> @shivareddy6 when will this repo open to contribute

It never stopped accepting contributions @harshsharma-11.

**Comment by shivareddy6** [comment]
We can work on this issue once we are ready with terms and conditions
