### ISSUE TITLE
Improper alignment of app bar's menu

### ISSUE THREAD

**Issue by shivareddy6** [scorelab/Codelabz#873]
**Describe the bug**
The right menu of app bar is not aligned properly. It's displayed away from avatar.

**To Reproduce**
1. Login using some credentials
2. Click on  the avatar
3. The menu displayed is not near the avatar.

**Expected behavior**
1. The cursor should be **pointer** when hovered on the avatar
2. The menu should be displayed closer to the avatar

**Screenshots**
![image](https://github.com/scorelab/Codelabz/assets/74174769/7a2043b1-b14c-4fa6-a0e2-5cccf437eb12)

It should look similar to the follownig:
![image](https://github.com/scorelab/Codelabz/assets/74174769/53a459b3-d56d-4c7f-b959-d001c9649b9b)

**Comment by Popokok** [comment]
Hi, I would like to work on this issue.

**Comment by Huzaif-Ahmed** [comment]
hey i would like to contribute towards this issue

**Comment by Aady7** [comment]
Is this issue resolved if not would like to work on it.

**Comment by Albert-2** [comment]
i would love to contribute please assign me this issue 
THANK YOU...!!:)
