### ISSUE TITLE
Firebase Setup in Contributing.md

### ISSUE THREAD

**Issue by Huzaif-Ahmed** [scorelab/Codelabz#874]
**Issue Description:**
I encountered difficulty setting up Firebase emulators while working with this project. The `contributing.md` file lacks detailed instructions for configuring Firebase emulators, which could be a barrier for other contributors. I would like to propose adding comprehensive steps for setting up Firebase emulators to make the development environment more accessible.

**Suggested Solution:**
I suggest enhancing the `contributing.md` file with step-by-step instructions for setting up Firebase emulators.

**Comment by Dhaneshwarguiyan** [comment]
Hey i have set up everything but unable to log in can anyone help!

The login button takes me no where.
![Screenshot from 2023-10-07 22-55-08](https://github.com/scorelab/Codelabz/assets/116065351/79e3e7d1-3443-4a46-a811-e802ef00667e)

**Comment by shivareddy6** [comment]
> Hey i have set up everything but unable to log in can anyone help!
> 
> The login button takes me no where. ![Screenshot from 2023-10-07 22-55-08](https://user-images.githubusercontent.com/116065351/273400222-79e3e7d1-3443-4a46-a811-e802ef00667e.png)

Heyy @Dhaneshwarguiyan, you need to run emulators on a different terminal. You can use `make emulator-import` to run emulators

**Comment by ira-mane** [comment]
is this issue still up ?

**Comment by shivareddy6** [comment]
its been solved with https://github.com/scorelab/Codelabz/pull/880
