### ISSUE TITLE
Logout Confirmation Modal

### ISSUE THREAD

**Issue by skbhagat0502** [scorelab/Codelabz#877]
**Subject** :- Feature Request: Logout Confirmation Modal

**Description:**
Currently, the website includes a logout button to allow users to sign out. To enhance the user experience and prevent accidental logouts, I propose the implementation of a logout confirmation modal.

Details:
Upon clicking the logout button, a modal should appear, asking the user to confirm their intention to log out. The modal should include a clear message such as "Are you sure you want to log out?" along with buttons for "Confirm" and "Cancel."

Benefits:

1. User-Friendly: Reduces the likelihood of accidental logouts.
2. Enhanced Security: Provides an additional layer of confirmation for sensitive actions.
3. Consistency: Aligns with modern web practices for user interactions.

**Comment by skbhagat0502** [comment]
@shivareddy6 Can I work on this?

**Comment by shivareddy6** [comment]
Hey @skbhagat0502, thanks for your feature request! While we think a logout confirmation modal is a great idea, our current focus is on integrating the front-end and back-end, which is our top priority.
Improving the user interface is definitely on our to-do list, but we want to make sure the website's core functionality is solid first.
Your suggestion is valued, and we'll keep it in mind for future updates. If you have more ideas, please share them with us. Your feedback matters!

**Comment by skbhagat0502** [comment]
@shivareddy6 surely!, From now I will focus more on integrating the frontend with the backend.I am highly interested in contributing to this project. If you have any specific things  in your mind that you want me to look into, I will love to help you with that first.
