### ISSUE TITLE
Save Button Margin Top Issue

### ISSUE THREAD

**Issue by skbhagat0502** [scorelab/Codelabz#878]
**Description:**
At a glance, the Save button in the form appears visually odd due to an excessive margin top. This styling anomaly becomes particularly noticeable when viewing the form. The disproportionate spacing disrupts the overall aesthetic harmony of the form.

**Steps to Reproduce:**
Navigate to the dasboard page.
Observe the Save button.
Notice the irregular margin top causing a peculiar visual appearance.

![image](https://github.com/scorelab/Codelabz/assets/109683163/9c4d54cb-c884-46cc-9c69-57328957872a)

**Expected Behavior:**
The Save button should maintain consistent and visually pleasing spacing, ensuring a polished look across various viewing distances.

![image](https://github.com/scorelab/Codelabz/assets/109683163/66a5ae9d-19c0-4e27-885a-e194a04ca294)

This look good in this. It should be same as this looks.

![image](https://github.com/scorelab/Codelabz/assets/109683163/c5d7bc61-a91e-41e7-9b77-bf6ff7345dbd)

**Comment by skbhagat0502** [comment]
I am working on this.

**Comment by skbhagat0502** [comment]
@shivareddy6

**Comment by skbhagat0502** [comment]
@shivareddy6 , I have made the pull request. Kindly review.

**Comment by shivareddy6** [comment]
solved with https://github.com/scorelab/Codelabz/pull/879
