### ISSUE TITLE
fullscreen toggling issue

### ISSUE THREAD

**Issue by Huzaif-Ahmed** [scorelab/Codelabz#881]
**Describe the bug**

**To Reproduce**
1. Go to 'tutorials'
2. Click on 'create tutorial'
3. Click on 'full screen icon'

**Expected behavior**
We Expect it to toggle between full screen and exit full screen with icon change

**Screenshots**
I

https://github.com/scorelab/Codelabz/assets/104403864/c749da6f-1c08-4e6c-9416-397f59090c05

**Additional context**

**Comment by Huzaif-Ahmed** [comment]
i have made the changes can you please assign it to me

**Comment by Huzaif-Ahmed** [comment]
@shivareddy6  made the required changes please suggest if any modulations required

**Comment by shivareddy6** [comment]
solved with https://github.com/scorelab/Codelabz/pull/882
