### ISSUE TITLE
No margin between the button in "Add New Step" modal.

### ISSUE THREAD

**Issue by Aady7** [scorelab/Codelabz#885]
**Describe the bug**
The modal the appears on clicking Add New Steps has to buttons "cancel" and "create" with no margin between them.

**To Reproduce**
1. Go to Tutorials
2. Click on "Add New Step"
3. See error

**Expected behavior**
The two button in the modal should have a little margin of about 7-10px between them.

**Screenshots**
<img width="508" alt="Screenshot 2023-10-09 194818" src="https://github.com/scorelab/Codelabz/assets/118021126/4027a637-29ae-42f0-8bee-d70eaaa94501">

**Desktop (please complete the following information):**
 - Windows11
 - Chrome
 -Version 117.0.5938.134 (Official Build) (64-bit)

**Comment by Aady7** [comment]
I would like to work on this issue.

**Comment by Aady7** [comment]
@shivareddy6 there are many more changes required in this modal like:-
1) The top margins are all uniform for input fields and buttons , the margin between title and time seems to be little larger.
2) In the time field the negative values for the time are also allowed  (we can set time like -4 minutes ) it id needed to be fixed.
and the margin between the buttons..
I would like to solve these issues too should I create a new issue or edit this issue.

**Comment by perminder-17** [comment]
As per my thoughts I have seen the website... There are many changes to be done... I guess the backend and frontend is not yet integrated. We need a lot to work on website. So why not to work with backend first and integrate them. @shivareddy6 ??

**Comment by perminder-17** [comment]
What are ur thoughts. Is I am right? @shivareddy6

**Comment by shivareddy6** [comment]
> What are ur thoughts. Is I am right? @shivareddy6

@perminder-17, we already have a backend design but the implementations is not done completely. We are thinking to open issues to implement different parts but since backend is coupled, it becomes a necessity to understand the whole model completely which might take up very long time. We will figure out something soon and update.
