### ISSUE TITLE
Implement modals to remove users from organization

### ISSUE THREAD

**Issue by shivareddy6** [scorelab/Codelabz#890]
**Is your feature request related to a problem? Please describe.**
Removing users from organization is not implemented yet.

**The solution should solve following**  
- [ ] Display 2 buttons similar to **Add New** but to remove users
- [ ] Only Owner should be able to view **Remove** button of admins 
- [ ] Only admins and owners should be able to view **Remove** button of contributors
- [ ] Implement respective modals to remove the users
- [ ] Connect it to backend function (more details given below)

**Navigating to the Implementation Page**
1. Login with a user credentials (with an organization)
2. Navigate to http://localhost:5173/org/settings/<organization>
3. Click on **Users** Option

**Backend Integration Details**
* The backend integration for removing users from the organization is handled by the removeOrgUser function.
* This function can be found in src\store\actions\orgActions.js. 
* If you are running emulators, you can check if the data is getting removed by visiting `http://localhost:4000/firestore`

**Additional context**
Check the [data base model](https://github.com/scorelab/Codelabz/wiki/Database-Design#org_users) for more information about user permissions

**Comment by perminder-17** [comment]
Hey @shivareddy6 please assign me

**Comment by Aady7** [comment]
Would like to work on the issue.

**Comment by shivareddy6** [comment]
I would suggest you to go through the codebase and device a basic plan on how you want to solve this issue. Please post a comment highlighting your plan of action. Its better to have more clarity before getting assigned and start solving the issue right.

**Comment by Aady7** [comment]
Hii @shivareddy6 as you suggested I had gone through the code base and devised a plan to tackle the issue:-
Frontend Implementation:-
For the frontend I thought of two ways of adding the remove user button 
 1. We can add a "remove" button just behind the add new button. On clicking a modal should appear where we can put the details of the user we want to delete and call required delete function.
 2. I also thought one more way that is adding a remove button beside the names of admins and contributors clicking on which the respective user get removed.(This will eliminate the need of modal) we can keep the ui of button simple and light.
For Backend:-
From the org_user colllection's "permission" array we can get the level of permission a particular user have , that will decide whom we can show the remove button then we can call removeOrgUser for the particular user that we want to delete, removing the user from cl_user collection.

**Comment by perminder-17** [comment]
Hi @shivareddy6 I have gone through the code. 
I will fix this issue by:-
**Front-end:**
1.Users will be stored in the database.
2..Use Redux Firestore to retrieve the permissions of the logged-in user to determine whether the "remove" button should be displayed. This can be achieved through the ProfileUserReducer available in the ProfileReducer folder.
3.Add a "delete" icon next to user names for contributors and admins.
4..Upon clicking the "delete" button, a modal will appear, asking for confirmation: "Are you sure you want to delete this user?"

**Backend:**
1.While reviewing the backend code, I found an issue in the removeOrgUser() function. The dispatch type is incorrect and needs correction.
2.The user will be removed from the organization.

**Comment by shivareddy6** [comment]
> @shivareddy6 i just have one doubt I'd like to clarify that these two issues, "Implement modal to add users to organizations" and "Implement modal to remove users from organizations," are closely linked. If we implement the "add users" modal first, it will lay the groundwork and provide a foundation for the "remove users" modal. This can make the implementation of the "remove users" modal smoother and more efficient.
> 
> In a typical user workflow, users need to be added before they can be removed, and implementing the "add users" modal first aligns with this user flow. .

correct!
But if you still want to work on it, you can manually add data into firestore (to simulate users getting added) and check if your implementation is alright. But as you said the complete testing can only be done after implementing add users.

**Comment by shivareddy6** [comment]
> Hii @shivareddy6 as you suggested I had gone through the code base and devised a plan to tackle the issue:- Frontend Implementation:- For the frontend I thought of two ways of adding the remove user button
> 
> 1. We can add a "remove" button just behind the add new button. On clicking a modal should appear where we can put the details of the user we want to delete and call required delete function.
> 2. I also thought one more way that is adding a remove button beside the names of admins and contributors clicking on which the respective user get removed.(This will eliminate the need of modal) we can keep the ui of button simple and light.
>    For Backend:-
>    From the org_user colllection's "permission" array we can get the level of permission a particular user have , that will decide whom we can show the remove button then we can call removeOrgUser for the particular user that we want to delete, removing the user from cl_user collection.

Maybe adding a remove button will be better.

**Comment by shivareddy6** [comment]
> Hi @shivareddy6 I have gone through the code. I will fix this issue by:- **Front-end:** 1.Users will be stored in the database. 2..Use Redux Firestore to retrieve the permissions of the logged-in user to determine whether the "remove" button should be displayed. This can be achieved through the ProfileUserReducer available in the ProfileReducer folder. 3.Add a "delete" icon next to user names for contributors and admins. 4..Upon clicking the "delete" button, a modal will appear, asking for confirmation: "Are you sure you want to delete this user?"
> 
> **Backend:** 1.While reviewing the backend code, I found an issue in the removeOrgUser() function. The dispatch type is incorrect and needs correction. 2.The user will be removed from the organization.

I liked your approach as well, you can start working on it and we can look at this once "add user" is solved.

**Comment by perminder-17** [comment]
Ok @shivareddy6

**Comment by KrishavRajSingh** [comment]
is this open?
