### ISSUE TITLE
Add more detailed steps when setting up the Firebase Emulator

### ISSUE THREAD

**Issue by umangutkarsh** [scorelab/Codelabz#891]
**Is your feature request related to a problem? Please describe.**
Some more steps need to be added in the `CONTRIBUTING.md` file.

<br />

**Describe the solution you'd like**
1. Go to [CONTRIBUTING.md/firebase-emulator](https://github.com/scorelab/Codelabz/blob/master/CONTRIBUTING.md#firebase-emulator-setup).
2. Add more detailed steps

**Comment by umangutkarsh** [comment]
@shivareddy6 , I've created the PR. Please review it and let me know if anything else is required. The `CONTRIBUTING.md` is updated according to the errors I faced while setting up the dev environment.
Thanks.

**Comment by umangutkarsh** [comment]
@shivareddy6 ,  I'm getting emulator setup problem, please check my findings on `gitter`

**Comment by shivareddy6** [comment]
@umangutkarsh, can you mention this issue in your pr. Only prs with valid issues are considered so its easy to get attention if this is mentioned your pr.

**Comment by umangutkarsh** [comment]
@shivareddy6 . Please take out your time and review the pr. It would be helpful. Thanks.
