### ISSUE TITLE
Content of steps in tutorials getting disappeared when toggling between different steps.

### ISSUE THREAD

**Issue by turingAlan** [scorelab/Codelabz#894]
**Describe the bug**
When user adds some content in the step-in tutorials and then switch to another step now when user try to navigate to the same step the content in the editor automatically becomes blank.

**To Reproduce**
1. Go to a new tutorial.
2. Add some content to the step-in editor mode.
3. Go to some another step.
4. Now try switching to the former step in editor mode.
5. The editor would be empty

**Expected behavior**
Editor should retain whatever we have written in it.

**Screenshots**

https://github.com/scorelab/Codelabz/assets/97225974/cbdedb60-dced-4ee5-ba6d-2bb741929a4d

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge, Chrome and Safari

**Comment by turingAlan** [comment]
Hi, @shivareddy6 can you assign this issue to me I have made the necessary changes to solve this issue.

**Comment by ABHISHEK-PANDEY2** [comment]
@turingAlan I think it is supposed to work like this, Each new step is written separately.

**Comment by turingAlan** [comment]
What I am talking about is when we switch between the steps the editor should also have the already written text in them so the user could know what the have previously written and edit that accordingly.

**Comment by ABHISHEK-PANDEY2** [comment]
@turingAlan ok got it, I think the data passed in the editor is not being displayed properly you can work on this one.

**Comment by shivareddy6** [comment]
Uploading Codelabz - Brave 2023-10-15 09-35-25.mp4…

Though there is a slight delay, it is retaining the information @turingAlan

**Comment by turingAlan** [comment]
@shivareddy6 I think then in my case yjs is not able to retrieve data from firestore.
![image](https://github.com/scorelab/Codelabz/assets/97225974/ddabac35-727d-43e5-81e9-cb473fb28a86)
