### ISSUE TITLE
Enhance New Codelabz Button Functionality for Unauthenticated Users

### ISSUE THREAD

**Issue by skbhagat0502** [scorelab/Codelabz#897]
**Description:**
Currently, when an unauthenticated user clicks on the "New Codelabz" button, a modal is displayed to add a new tutorial. However, since tutorial creation requires authentication, this flow is not user-friendly also we know that the user can't publish a tutorial if not authenticated. To improve the user experience, we should implement the following changes:

1. **Authentication Check:**
   - Before displaying the modal, we should check if the user is authenticated.

2. **Redirect to Login Page:**
   - If the user is not authenticated, redirect them to the login page.

3. **Toast Message:**
   - Along with the redirection, display a toast message informing the user that they need to log in to create a tutorial. The message should be clear and concise, such as: "Login to create a tutorial."

**Steps to Reproduce:**
1.Go to the home page of the application.
2. Click on the "New Codelabz" button.

**Expected Behavior:**
- If authenticated, display the modal for tutorial creation.
- If not authenticated, redirect to the login page with a toast message prompting the user to log in to create a tutorial.

**Additional Information:**
- This enhancement aims to improve the user experience by guiding unauthenticated users to the appropriate action and providing clear instructions.

**Note:**
Please consider implementing these changes to create a more seamless and user-friendly workflow for tutorial creation.

**Comment by skbhagat0502** [comment]
Hi @shivareddy6 , @ABHISHEK-PANDEY2 , @Sarfraz-droid I think this is a good issue and should be resolved. I want to work on this issue. Please assign this issue to me.

**Comment by DhairyaMajmudar** [comment]
@shivareddy6 @skbhagat0502 @ABHISHEK-PANDEY2 @Sarfraz-droid would love to work on this issue. Pls. assign this to me

**Comment by shivareddy6** [comment]
> Hi @shivareddy6 , @ABHISHEK-PANDEY2 , @Sarfraz-droid I think this is a good issue and should be resolved. I want to work on this issue. Please assign this issue to me.

Sure you can work on it. I would also suggest you to include a video clip describing your issue(for future issues too) which will make it easier to understand it.

**Comment by skbhagat0502** [comment]
I have started working on this issue.

**Comment by skbhagat0502** [comment]
@shivareddy6 , I have fixed the issue. But in this issue I have used react toast so when the pull request #896 will be merged then only this can be merged as it's functionality depends on that pull request. Please review the pull request #896 and then after merging that please review this.

**Comment by shivareddy6** [comment]
> @shivareddy6 , I have fixed the issue. But in this issue I have used react toast so when the pull request #896 will be merged then only this can be merged as it's functionality depends on that pull request. Please review the pull request #896 and then after merging that please review this.

Sure.
