### ISSUE TITLE
Letter "P" is mis-aligned within the word "PAGE"

### ISSUE THREAD

**Issue by Pheewww** [scorelab/Codelabz#898]
**Describe the bug**
Letter "P" is mis-aligned within the word "PAGE"

**To Reproduce**
1. Go to 'http://localhost:5173/bookmarks'
2. See error

**Expected behavior**

**Screenshots**

![Letter_P_Broken](https://github.com/scorelab/Codelabz/assets/67512605/bdc58807-0e96-4133-840c-93f1b154dd85)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. Firefox, Chrome]

**Comment by Pheewww** [comment]
Please assign it to me, i have completed fixing it.

**Comment by ABHISHEK-PANDEY2** [comment]
@Pheewww Thanks for raising an issue but That's supposed to be that way.

**Comment by Pheewww** [comment]
> @Pheewww Thanks for raising an issue but That's supposed to be that way.

Really, thanks for update.

**Comment by shivareddy6** [comment]
Misinterpretation of the issue
