### ISSUE TITLE
Content disappears in Editor Mode.

### ISSUE THREAD

**Issue by perminder-17** [scorelab/Codelabz#904]
**Describe the bug**
When using the website's editor mode, there is an issue where the content disappears after switching to preview mode and then returning to editor mode. Switch to editor mode to begin "abcd" step should only come when nothing is writen on editor mode but when we go to the editing mode the whole text disappears. A person who preview his work and want's to change something cannot do that.

**To Reproduce**
1. Go to 'Website'
2. Click on 'NEW CODELABZ'
3. Create a tutorial. 
4. Click on editor mode. 
5. Write something as the content.
6. click on preview mode and again go to editor mode.

**Expected behavior**
The content that was previously written in editor mode should still be visible when returning to it.

**Screenshots**

[issue2.webm](https://github.com/scorelab/Codelabz/assets/127239756/5d806afb-9ef2-428f-a3ce-d0e05b56fdbd)

**Comment by turingAlan** [comment]
@perminder-17 this is not a bug here yjs is used for saving the data in description box and in order to use yjs you need to setup a firestore database. I have discussed this issue in #894.

**Comment by perminder-17** [comment]
@turingAlan i saw your issue #894. This was because of firebase. In this issue, the default behavior is only when u come back to editor from preview, your content vanishes. The issue #894 is not occurring on my system as I have completely setup the firebase. @shivareddy6

**Comment by perminder-17** [comment]
@turingAlan is this retaining the value on your system.

**Comment by turingAlan** [comment]
@perminder-17 previously I haven't setup my firestore db but after setting the db it satrted to retain the vaue.

**Comment by perminder-17** [comment]
> @perminder-17 previously I haven't setup my firestore db but after setting the db it satrted to retain the vaue.

So, can u please check that it is retaining the value going to preview and then to editor. Bcz I have also setup the firebase in my system it's still not retaining. If in your system it retains I will close this issue. Please check in your system.

**Comment by turingAlan** [comment]
@perminder-17 yes, it is retaining the value I have checked that. In order to access this, you need to make a firestore db in your firebase project.
