### ISSUE TITLE
Inconsistent Data Removal - Remove Step Feature

### ISSUE THREAD

**Issue by perminder-17** [scorelab/Codelabz#905]
**Describe the bug**
The "Remove Step" feature currently exhibits inconsistent behavior, which affects the integrity of the application's data management. This inconsistency arises from the fact that, while it removes the step from the frontend, it merely marks the step as "deleted" in the backend (Firebase) by setting a deleted flag to true. When a user initiates the "Remove Step" action, a modal dialog warns them that this action cannot be undone. However, the current implementation contradicts this by retaining a soft-deleted copy of the step in the backend.

**Expected behavior**
To align the application's behavior with user expectations and best practices, it is recommended that the "Remove Step" feature should not only remove the step from the frontend but also delete it entirely from the backend. This ensures that the data remains consistent and adheres to the principle of data minimization. It will also reduce data storage and enhance the data consistency and alignment with user expectations.

**Screenshots**

[issue3.webm](https://github.com/scorelab/Codelabz/assets/127239756/a662e3b4-90ef-451c-94d1-f351dffacf73)

**Comment by perminder-17** [comment]
Hi @shivareddy6 and @ABHISHEK-PANDEY2 @Sarfraz-droid I have done working on it. If u see this as an issue I can make the PR.

**Comment by shivareddy6** [comment]
> Hi @shivareddy6 and @ABHISHEK-PANDEY2 @Sarfraz-droid I have done working on it. If u see this as an issue I can make the PR.

Sure, sounds like an issue to me

**Comment by perminder-17** [comment]
> > Hi @shivareddy6 and @ABHISHEK-PANDEY2 @Sarfraz-droid I have done working on it. If u see this as an issue I can make the PR.
> 
> Sure, sounds like an issue to me

Okay, I am going to make a pr then

**Comment by Doraemon012** [comment]
@shivareddy6 I've opend a PR for this issue, please take a look.

**Comment by shivareddy6** [comment]
solved with https://github.com/scorelab/Codelabz/pull/977
