### ISSUE TITLE
Notification unread and Mark All read Feature request

### ISSUE THREAD

**Issue by Dhanush834** [scorelab/Codelabz#907]
**Feature Description :**

1. In Notification Box there is an option to **_mark as read_** But there there no Option for **_mark as unread_** for user to read after sometime for remanding
2. Another Option Should be Provided to Mark all notification as Read in a single Click .   

**Describe the solution you'd like**

1. When user Clicks on **_mark as unread_** notification should be marked unread
2. When User Clicks on **_Mark ALL Read_** all Notification should be read.

**Feature Request Page :**
Working Demo of the Feature Requested : 

https://github.com/scorelab/Codelabz/assets/124449985/7051a6eb-e42d-4157-8faf-924b6126d548

This Image is Taken after coding the feature ( With Working ) :

![image](https://github.com/scorelab/Codelabz/assets/124449985/3a554834-1bdc-4055-a03c-197f2d8eeb2d)

**CONCLUSION** 
If you guys find this feature useful I am ready to make a PR for this for Reviewing

**Comment by Dhanush834** [comment]
@Sarfraz-droid @shivareddy6 @ABHISHEK-PANDEY2 Please let me know if this feature is Good for implementing . If so I will raise a PR for code review

**Comment by shivareddy6** [comment]
Thanks for pointing out the issue but the backend for notifications is not done yet. I believe this can be solved completely once the backend is working else we'll just be updating the read status in the front end.
