### ISSUE TITLE
[ Feat : Long message to the user when cancelling an Auth request ]

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#915]
**Is your feature request related to a problem? Please describe.**
When a user initiate a login through any of the auth option and cancels it midway then a message is popping up saying "Firebase: The popup has been closed by the user before finalizing the operation. (auth/popup-closed-by-user)" which is not a good user experience.

**Describe the solution you'd like**
Instead of the long message, it can show small text saying " Login cancelled !"

**Additional context**
![image](https://github.com/scorelab/Codelabz/assets/123815256/0d88b11d-3352-4326-94e7-25d0a740b5f9)
Login or signup button is enabling on initiating authentication through auth options and I am not sure if the credentials are being sent in the process cause if it is then unused data may populate the db.

**Comment by perminder-17** [comment]
Can i work on this?

**Comment by Huzaif-Ahmed** [comment]
I would like to work on this issue can you assign it to me? if not can I work along @perminder-17 ?
