### ISSUE TITLE
[ Feat : UI fixes of Forgot Password at Login or Signup card ]

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#927]
**Is your feature request related to a problem? Please describe.**
No, changing it won't effect in any functionality of the app, it's just changes the UI of Forgot Password link of the Login or Signup card at /login Page. That will make it more look like a link.

**Describe the solution you'd like**
Forgot password link should be at the end of the Grid, it is inside of and a different color to show that it is a link ( like a blue color ).

**Describe alternatives you've considered**
Can also use underline under link to show it's a color.

Currently what it is like -
![image](https://github.com/scorelab/Codelabz/assets/123815256/e6f7d5cf-43df-4b09-bb2b-7e436658bce6)

Something similar to this -
![image](https://github.com/scorelab/Codelabz/assets/123815256/1f3dc478-7d14-4e76-aa81-3ebb0865e39b)

**Comment by om-chauhan1** [comment]
Can i solve this issue? If yes, then kindly assign this to me.

**Comment by om-chauhan1** [comment]
I have done. Can i raise pr to the main branch ?

**Comment by sarwar-jahin-port** [comment]
@charithccmc @rohitPandey469  I've addressed the issue and submitted a PR for your review. Your feedback is highly appreciated.

**Comment by rohitPandey469** [comment]
Well I am not sure why it's not fixed yet!!!
