### ISSUE TITLE
[ Bug : Failed redirecting to user after login through social options ]

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#928]
**Describe the bug**
When a user login or signup through facebook, twitter and github at /login then it redirects back the user to /login page instead of /dashboard page which is happening in the case of login through google where the user needs to fill further details after login.

**To Reproduce**
1. Go to http://localhost:5173/login.
2. Click on github or facebook or twitter login icon.
3. Click on +Add an account or select an account option.
4. The user redirects back to /login rather than /dashboard page which is happening in the case of google login.

**Expected behavior**
The user should needs to be redirected to /dashboard page to fill further info, after logging through facebook or twitter or github similar to google login.

**Video**
 

https://github.com/scorelab/Codelabz/assets/123815256/5c7a432d-62b0-49e8-b7f3-ec79f3a08e44

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version : 22H2

**Comment by rohitPandey469** [comment]
Hello Sir, would like to work on this issue
/attempt#928

**Comment by GIGA-CODER** [comment]
Please assign this issue to me , I have almost resolved it

**Comment by rohitPandey469** [comment]
Hey, this issue isn't assigned to anyone

**Comment by vaishnavi192** [comment]
@rohitPandey469 you opened this issue means you are going to solve it right? or other people can also solve?

**Comment by GIGA-CODER** [comment]
@vaishnavi192 even other people can solve the issue . It doesn't matter who has raised the issue , anybody can solve it

**Comment by rohitPandey469** [comment]
I am waiting for it to get assigned
