### ISSUE TITLE
Bug: Width and height of hover state of icons on signup and login page are not proper

### ISSUE THREAD

**Issue by pateldivyesh1323** [scorelab/Codelabz#929]
**Description**
Hover state of icons on signup and login page does not have proper width and height.

**To Reproduce**
1. Go to '/signup'
2. Hover on google, facebook, twitter, github icons.

**Expected behavior**
Shadow on hover should have proper width and height

**Screenshots**
![Screenshot (71)](https://github.com/scorelab/Codelabz/assets/109150688/3847506b-6d92-4506-ac02-75cf8e494450)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 10

**Additional context**
Opening the issue directly without discussing on gitter, because it is very small bug

**Comment by DhairyaMajmudar** [comment]
Hi @shivareddy6 , @ABHISHEK-PANDEY2 , @Sarfraz-droid . I want to work on this issue. Please assign this issue to me.

**Comment by pateldivyesh1323** [comment]
@DhairyaMajmudar Thankyou for your interest, but I already raised a PR. Please find another open issues.

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar Thankyou for your interest, but I already raised a PR. Please find another open issues.

Okay I will look for an another issue. Thanks
