### ISSUE TITLE
Bug: React does not recognize the `data-testId` prop on DOM element

### ISSUE THREAD

**Issue by pateldivyesh1323** [scorelab/Codelabz#937]
**Describe the bug**
`data-testId` should be written as `data-testid` to be recognized by react. It has been used at 416 places inconsistently i.e., sometimes it is written like data-testid(which is fine) but it is written like data-testId(which throws the error). If this is considered as a valid issue, I would like to work on it.

**To Reproduce**
1. Go to 'home page'
2. Open console

**Screenshots**
![image](https://github.com/scorelab/Codelabz/assets/109150688/c8607d27-8a0d-483e-b978-a1fafafd3cc3)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 10

**Comment by GIGA-CODER** [comment]
I have fixed this issue

**Comment by KrishavRajSingh** [comment]
is this open?
