### ISSUE TITLE
Make Website Responsive for Every Screen Size

### ISSUE THREAD

**Issue by omChauhanDev** [scorelab/Codelabz#948]
Improve the overall responsiveness of the whole website, make it perfect for every screen size.

**To Reproduce**
1. Go to website
2. Do Sign up/ Log in
3. Go inspect element 
4. Try to change the dimensions of the screen.

**Expected behavior**
The expected outcome is the perfect website for every type of screen from small mobile to large monitors. No component/content should overflow or get cut in any screen size.

**Screenshots**
Few screenshots to illustrate the problem:- 
1. When screen size = 1024px x 865px --> Common Screen Size
![image](https://github.com/scorelab/Codelabz/assets/119471995/ed7699cb-53e1-4ceb-b6ae-b03825405a73)
 
2. In iPhone 12 pro
![image](https://github.com/scorelab/Codelabz/assets/119471995/37fde71c-a8ad-41d2-a5a5-1b2e234a841b)

3. In iPad air --> We can clearly see that the content is not fully visible (it got translated to top)
![image](https://github.com/scorelab/Codelabz/assets/119471995/bf04cddf-55da-4a83-88d0-30b187898c71)

4. Again, the text got cut inside user Setting tab --> Screen size Laptop: 1024px x 865px
![image](https://github.com/scorelab/Codelabz/assets/119471995/57d1890e-75fd-4d09-a887-18a357812dea)
 

**Desktop: **
 - OS: Window 11
 - Browser: Edge 
 - Version 119.0.2151.58 (Official build) (64-bit)

**Comment by riyaaaa123** [comment]
hey, if the issue isn't solved yet, can i please work on it?

**Comment by om-chauhan1** [comment]
Don't worry the issue of responsivenesss has already been resolved in this pr only i have to make it pass all the test cases. It only got delayed due to my end sems. And now when they are over i will resolve them as soon as possible. So, you can either create some new issues or focus to solve the existing ones.
Thanks
