### ISSUE TITLE
ToggleButton value cannot be less than 0 (not be a negative value)

### ISSUE THREAD

**Issue by manzil-infinity180** [scorelab/Codelabz#953]
**Describe the bug**

**To Reproduce**

1. Go to '/'
2. Click on ''

**Expected behavior**

**Screenshots**
# Current Behaviour 

https://github.com/scorelab/Codelabz/assets/119070053/fc50791e-7c82-4e3c-ab43-b55d90f72f48

# Desired Behaviour 

https://github.com/scorelab/Codelabz/assets/119070053/63030b99-a2fc-4aa4-8dce-240234195f4f

**Desktop (please complete the following information):**

- OS: [MacOS]
- Browser [ chrome]
- Version [ 22]

**Smartphone (please complete the following information):**

- Device: [HONOR *C]

- Browser [Chrome]

**Additional context**

- Assign me - I want to work on that

**Comment by manzil-infinity180** [comment]
assign me please

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by GriffinAnnshual** [comment]
Hey @manzil-infinity180 I would like to work on this issue. Could you please assign it to me?
