### ISSUE TITLE
Comment message(text) should be disapper after submitting the comment 

### ISSUE THREAD

**Issue by manzil-infinity180** [scorelab/Codelabz#955]
**Describe the bug**
- Here Current Behaviour 
If we enter any comment ,the entered text is stayed as it is - which is not looking good 

Expected Behaviour : 
* whenever any user entered text then it should be disappear from the text box whatever we write and added as a comment and Current behaviour is that whatever we wrote it appeared as it is 

https://github.com/scorelab/Codelabz/assets/119070053/54c2f8ab-fd94-446d-ac63-9fff6b22cd23

* whenever the string(text message) of length 0(zero) it will throw some message to write the comment (for example - if length is zero we can disable the comment button or throw some message comments can not be empty)
<img width="1026" alt="Screenshot 2023-12-25 at 1 10 23 AM" src="https://github.com/scorelab/Codelabz/assets/119070053/8ae46fd2-c775-4447-b8c0-4395aaf3f3f6">

https://github.com/scorelab/Codelabz/assets/119070053/e53488d4-98f0-4a7b-9d13-ac17dd33b5ce

- expected 
 After submitting the comment , the text which we write have to remove automatically just after clicking on submit icon or enter 

**To Reproduce**

1. Go to '/tutorial/'
2. Click on 'Comment Box'

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mahir2006-star** [comment]
Hello @manzil-infinity180 . Can you assign this issue to me? I believe I will be able to resolve it I have experiencing in building such systems.

**Comment by Ramsha42001** [comment]
Hello. Can you assign this issue to me?
