### ISSUE TITLE
Not validating user handle, whether it already exists or not

### ISSUE THREAD

**Issue by Aditya-Sakpal** [scorelab/Codelabz#956]
**Describe the bug**
The application is not validating whether the user handle already exists or not

**To Reproduce**

1.Go to dashboard page 
2.Enter the user handle that already exists 

**Expected behavior**
Message should appeared that tells 'The handle 'user_handle' is already taken'

**Video Reference**

https://github.com/scorelab/Codelabz/assets/112710558/e8190755-cad6-4dca-8725-b68fe76c5c0b

**Comment by nilerudra** [comment]
I would like to work on this. Could you please assign it to me?

**Comment by amannayak2003** [comment]
Assignments that require creativity, dedication, and strategic thinking are where I can thrive best , May i be assigned to solve this Bug

**Comment by imsidkg** [comment]
When I click save , i see no progress. The page does not redirect , it is stuck at "saving" mode
