### ISSUE TITLE
Twitter logo needs to be updated

### ISSUE THREAD

**Issue by sivangbagri** [scorelab/Codelabz#960]
**Describe the bug**
twitter logo needs to be updated to new one : X

**To Reproduce**

1. Go to 'Login'

**Screenshots**
<img width="431" alt="image" src="https://github.com/scorelab/Codelabz/assets/61118650/1ac8b0d1-1d17-46e9-b111-e145b1ae3bfb">

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Additional context**
I am working on this issue

**Comment by Muditakhatri** [comment]
Is it possible for me to be assigned?

**Comment by hashnj** [comment]
scorelab.org has a footer with twitter logo that too can be listed for updation
![Screenshot 2023-12-01 1445123](https://github.com/scorelab/Codelabz/assets/124368571/05e43b28-1dfc-4d43-b480-4f8111ec8422)

**Comment by amannayak2003** [comment]
hello @sivangbagri, Assignments that require creativity, dedication, and strategic thinking are where I can thrive best
