### ISSUE TITLE
minor typo in  create organisation form

### ISSUE THREAD

**Issue by LaPulgaaa** [scorelab/Codelabz#964]
**Describe the bug**
Minor typo in organisation form in dashboard section

**To Reproduce**

1. Go to main landing page
2. Click on login
3. Upon entering your details and clicking on " i want to create an organisation"
4. the create organisation form appears which has a typo

**Screenshots**
![codelabz](https://github.com/scorelab/Codelabz/assets/123243429/6453a80a-0715-4419-a611-64d602f99cba)

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?
