### ISSUE TITLE
Bug:typo error while importing ExploreOrgs in the index.stories.jsx file

### ISSUE THREAD

**Issue by swetagit186** [scorelab/Codelabz#971]
**Describe the bug**
There is a typo error while importing the ExploreOrg functionality in the 3rd line of the index.stories.jsx file.

**To Reproduce**

1. Go to 'index.stories.jsx file'
2. Scroll down to '3rd line'
3. See error

**Expected behavior**
It should be :-
import ExploreOrg from "../../../components/MyFeed/oldExploreOrgs";
in place of :-
import ExploreOrg from "../../../components/MyFeed/ExploreOrgs";

**Screenshots**
Before:-
<img width="1087" alt="Screenshot 2023-12-06 at 6 45 28 PM" src="https://github.com/scorelab/Codelabz/assets/122719637/ac46ac19-48da-40e1-8ad0-2e17410111dd">
After:-
<img width="1414" alt="Screenshot 2023-12-06 at 6 46 47 PM" src="https://github.com/scorelab/Codelabz/assets/122719637/31653ec6-21e3-4d0f-9331-854ef0328c46">

**Desktop (please complete the following information):**

- macOS
- chrome browser
- 2020

**Additional context**
Please correct the typo here since there persists an error in displaying the ui in the storybook unless this is corrected.

- Feature_Request / Bug_Report - [includes in repository]

  - Would you like to work on the issue?
    - [x] Yes
    - [ ] No
    - [ ] Other:

**Comment by ShivamBisen** [comment]
hello, can i fix this issue ??

**Comment by swetagit186** [comment]
I am working on this issue and PR has already been raised.

**Comment by chetansource** [comment]
is the issue is still open, can i work on the issue..?
