### ISSUE TITLE
Drag feature does not work whenever we drag any image for upload 

### ISSUE THREAD

**Issue by manzil-infinity180** [scorelab/Codelabz#976]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

https://github.com/scorelab/Codelabz/assets/119070053/08260a48-091b-41dc-bccf-c16afa0a1087

**Comment by ShivamBisen** [comment]
Can I be assigned this issue?

**Comment by DhananjayDogne** [comment]
I want to work on this issue kindly assign me this issue

**Comment by Faisal-imtiyaz123** [comment]
Can you explain it. You haven't written anything to explain the issue . Plz elaborate a bit.

**Comment by Vaibhav-Bothra** [comment]
I want to work on this issue. I have done drag and upload feature in past projects. Kindly assign me this issue.

**Comment by manzil-infinity180** [comment]
Hi @shivareddy6, @ABHISHEK-PANDEY2 , @Sarfraz-droid , can i use dropzone js for this feature ,please help me  or anyother i just know dropzone for this type of feature

**Comment by ABHISHEK-PANDEY2** [comment]
@manzil-infinity180 please elaborate the issue .

**Comment by rohitPandey469** [comment]
@manzil-infinity180 If we hover directly over the button then it will work
