### ISSUE TITLE
[ Feat: Improve Hover Effects for Authentication Icons ]

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#981]
**Is your feature request related to a problem? Please describe.**
The current hover effects for authentication icons are not optimal, resulting in an unsatisfactory visual experience. When hovering over the icons, there is no smooth transition, and the background color is prominently visible, causing a visual inconsistency.

**Describe the solution you'd like**
I propose to enhance the hover effects for authentication icons by introducing a smooth transition and addressing the background visibility issue. The improved hover styling will contribute to a more polished and visually appealing user interface.

**Describe alternatives you've considered**
Alternative solutions considered include:
Adjusting the transition properties to achieve a smoother effect.
Modifying the background styling to ensure a more cohesive and visually pleasing appearance.

**Additional Context**

https://github.com/scorelab/Codelabz/assets/123815256/1605d63d-a4cb-4838-b9bb-a6ac2a060acb

**Working**
YES

**Comment by rohitPandey469** [comment]
@shivareddy6 @ABHISHEK-PANDEY2  @rijusougata13 Review it, will submit the PR soon.

**Comment by rohitPandey469** [comment]
👋 Hey @shivareddy6, @ABHISHEK-PANDEY2, @rijusougata13, once the UI changes get the green light, I'm ready to mirror these enhancements on the Signup page—your approval is key!

**Comment by ABHISHEK-PANDEY2** [comment]
@rohitPandey469 could you make the oval-shaped background circular for every icon ?

**Comment by rohitPandey469** [comment]
@ABHISHEK-PANDEY2 Sure Sir, will make the PR soon, an oval shaped background

**Comment by rohitPandey469** [comment]
https://github.com/scorelab/Codelabz/assets/123815256/d0551495-f486-46d7-b2d2-106e0882c094


Upon your approval, I would extend these enhancements to the signup page as well for a consistent and polished user experience. May I proceed with the implementation?
