### ISSUE TITLE
POPUP MODAL for "Tutorial succesfully created"

### ISSUE THREAD

**Issue by Aryann15** [scorelab/Codelabz#984]
**Is your feature request related to a problem? Please describe.**
After publishing a tutorial we must get a popup saying , "tutorial succesfully created", right now its just a toggle button 

**Describe the solution you'd like**
A proper popup modal saying tutorial sucessfully created and two button, maybe ,"return to dashboard , or unpublish 

**Additional context**
[Screencast from 2023-12-23 22-24-28.webm](https://github.com/scorelab/Codelabz/assets/82017158/d521a308-8487-488a-bc0e-d203d30c17fd)

**Comment by Aryann15** [comment]
Hey @shivareddy6 @ABHISHEK-PANDEY2 , I'm interested in implementing this. May I have your approval to proceed with this enhancement? Thanks

**Comment by ABHISHEK-PANDEY2** [comment]
I think there is a toast already implemented for other actions, can you create a toast whenever a tutorial is published? @Aryann15

**Comment by Aryann15** [comment]
[Screencast from 2023-12-31 08-48-13.webm](https://github.com/scorelab/Codelabz/assets/82017158/f46991e8-ed05-44c8-8b0e-0affa433758c)
how about this ? @ABHISHEK-PANDEY2

**Comment by Aryann15** [comment]
Please view it in full screen mode and lookout for the bottom left, it gets shaded out in this video,
