### ISSUE TITLE
Improve consistency of homepage fonts

### ISSUE THREAD

**Issue by SoarinSkySagar** [scorelab/Codelabz#990]
# BUG:
In the homepage, the UI does not look good. The line spaces and boldness are very inconsistent.

1. Go to homepage, there in the right pane, the font properties are very out of place. 

# Expected behavior
The font should be smooth and consistent with the entire page, and I can do just that by increasing the line spaces, adjusting the boldness and changing font sizes, and also borders and/or ight background color would be good

# Screenshots
<img width="325" alt="image" src="https://github.com/scorelab/Codelabz/assets/117727361/6048c349-2996-4e86-ab4e-e09fc14ab1f8">

# Desktop (please complete the following information):

- OS: Windows 11
- Browser: Brave
- Version: 22

**Comment by lokeshsharma19** [comment]
is this issue open 
i want to contribute to this
