### ISSUE TITLE
Feature Addition: Text Editor Improvements for Interactive Tutorials

### ISSUE THREAD

**Issue by SURAJ-SHARMA27** [scorelab/Codelabz#993]
**Is your feature request related to a problem? Please describe.**
The previous text editor lacked essential formatting options such as varied text sizes, text highlighting, text color, text alignment, bullets, subscript, superscript, font family, and hyperlink functionality. This limitation resulted in the inability to create interactive and visually appealing tutorials as only plain text could be published.
**Describe the solution you'd like**
I have enhanced the text editor in the new tutorial page by adding the following functionalities:
- Header options ranging from level 1 to level 7.
- Formatting options for bold, italic, underline, and strike-through.
- Blockquote functionality.
- Ordered and unordered list options.
- Subscript and superscript options.
- Color and background options for text.
- Font selection dropdown.
- Text alignment options.
- Inserting images, code blocks, and hyperlinks.
- A 'clean' option to remove formatting.
- These additions provide a more comprehensive set of tools for creating visually rich and interactive tutorials.

**Additional context**
The new features contribute to making the tutorial page more versatile and user-friendly. Users can now customize text styles, add images and code snippets, and include hyperlinks, allowing for a more interactive and visually appealing learning experience. The pull request includes changes to the text editor code as per the provided specifications.

**Comment by SURAJ-SHARMA27** [comment]
@shivareddy6  can you assign this issue to me.

**Comment by lokeshsingh3721** [comment]
This functionality already added  by me  in #974 . You can pick another issue.
