### ISSUE TITLE
No limitation to the upvote or downvote and no hover text in the buttons

### ISSUE THREAD

**Issue by PoulavBhowmick03** [scorelab/Codelabz#995]
**Describe the bug**
When we add a new Codelabz, there is a functionality of upvote and downvote. But right now, there is not limitation for an user. They can upvote or downvote n number of times.
Also, there is no hover text in the share, bookmark and comment buttons in the same.
**To Reproduce**

1. Go to 'http://localhost:5173/tutorials' and add on "add new codelabz"
2. Click on '(http://localhost:5173/)'
3. Scroll down to the codelabz and the upvote, downvote, comment bookmark and share buttons

**Expected behavior**
The upvote or downvote button should allow users to only be able to vote once, and then they can either keep that or change their vote.
The comment, bookmark and share button should show their names when hovering over it

**Screenshots**
![image](https://github.com/scorelab/Codelabz/assets/133862694/781a03d2-fb81-4214-89b4-43b0d04704ac)
**Desktop (please complete the following information):**
![image](https://github.com/scorelab/Codelabz/assets/133862694/59b215cc-cf28-48dd-aa1d-4b6d6e9e017b)

- OS: Windows
- Browser Brave
- Version- Latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ABHISHEK-PANDEY2** [comment]
@PoulavBhowmick03 If you are going to work on this, try to implement it with backend logic and connect it to the backend.

**Comment by PoulavBhowmick03** [comment]
@ABHISHEK-PANDEY2 Okay, I would do that. Yes I will be working on this, do I need to get assigned before I start working on it?

**Comment by ABHISHEK-PANDEY2** [comment]
I assigned it to you, you can work on it.

**Comment by PoulavBhowmick03** [comment]
Thanks!

**Comment by PoulavBhowmick03** [comment]
@ABHISHEK-PANDEY2 Hello, I have the frontend code ready for this, I just need a little more time to understand and work on the backend in firebase. In the meanwhile, can I raise a PR for the frontend code? and then work on the backend later? Would that be okay?

**Comment by PoulavBhowmick03** [comment]
Like, I have written the function to fetch and store the upvote or downvote, but I am not exactly sure where to pass that or import the model from. That's why.. Can I work on the backend for this a bit later?
