### ISSUE TITLE
Dynamically add comments with real time updates

### ISSUE THREAD

**Issue by Ashish-Ranjan007** [scorelab/Codelabz#996]
**Is your feature request related to a problem? Please describe.**
1. The user needs to manually refresh the page to see their posted comment.
2. The input field retains outdated text even after submission.
3. There is no feedback provided to inform the user about the success or failure of the action.

**Steps to reproduce the behavior**
1. Navigate to a tutorial from the home page or create a new tutorial if none exist.
2. Try to post a comment on the tutorial.

**Describe the solution you'd like**
1. Dynamically add comment in real time to view changes without page refresh.
4. Clear the input field upon submission of the comment.
5. Notify the user indicating the success or failure of the action.

**Additional context**
https://github.com/scorelab/Codelabz/assets/58631166/b130ea78-bc66-48ee-8abf-32c63bbf1a7a

**Comment by Ashish-Ranjan007** [comment]
@shivareddy6 @ABHISHEK-PANDEY2 Hi, I am interesting in implementing these features. Can you please assign me this?

**Comment by ABHISHEK-PANDEY2** [comment]
Go ahead @Ashish-Ranjan007

**Comment by Ashish-Ranjan007** [comment]
Thanks, I will start working on it.
