### ISSUE TITLE
User Creation Fails Without Firebase Emulators Setup; Country Value Logging on Every Change

### ISSUE THREAD

**Issue by karthxk07** [scorelab/Codelabz#998]
## Describe the bug
When attempting to create a user without the Firebase emulators set up, the user creation fails, preventing the user from being saved. Additionally, the country value is logged to the console on every change.

## To Reproduce
* Attempt to create a user without Firebase emulators set up.
* Observe the failure in saving the user.

## Expected behavior
The user creation should be successful, even without Firebase emulators set up. The application should gracefully handle scenarios where emulators are not configured.

## Screenshots
[Screencast from 2023-12-31 13-32-08.webm](https://github.com/scorelab/Codelabz/assets/109301536/abbdedc3-e596-4c75-8dcd-16689734a66e)

## Desktop

OS: Linux amd64 (Debian 12)
Browser: Brave Browser

## Additional context
It would be helpful to check if anyone else is facing a similar error and to investigate the logs or error messages from the server or client side. Additionally, ensure that the application has proper error handling for scenarios where Firebase emulators are not set up.

Consider checking the relevant code sections where user creation is handled and where the country value is logged to the console for any potential issues or misconfigurations.

**Comment by Huzaif-Ahmed** [comment]
I would like to work on this issue can you assign it to me

**Comment by karthxk07** [comment]
Umm I was actually planning to work on that @Huzaif-Ahmed :confused:
